### ISSUE TITLE
Reihenfolge der Dropdowns ändern

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#10]
Zurzeit sind gewisse Dropdowns noch seltsam geordnet. Ich habe die Vermutung, das die Ordnung anhand des GeolCodes gemacht wird. Da dies aber eine kontinuierliche Nummer ist und nicht im Kontext mit der Reihenfolge sein muss, müsste man wohl ein zusätzliches Attribut in diese Liste aufnehmen, welches die Reihenfolge definiert. Weil wir bei der Lithostrati viele Werte haben, sollte es eine 4stellige Zahl sein, also bspw 0001. Hier die Reihenfolgen, die angepasst werden müssten. bei den anderen dropdowns stimmt die Reihenfolge, da dort die GeolCodes aufsteigend vorliegen

Location:
reference_elevation 
20117001	ibor117	OKT	Oberkante Terrain 
20117002	ibor117	ROK	Rohroberkante
20117003	ibor117	ROT	Rotary Table
30000013	ibor117	KB	Kelly Bushing
20117004	ibor117	SD	Schachtdeckel
20117005	ibor117	a	anderes
20117006	ibor117	kA	keine Angaben

Borehole:
drilling_purpose 
22107006	ebor107	HA	Handbohrung
22107003	ebor107	RS	Rammsondierung
22107011	ebor107	RKS	Rammkernsondierung
22107013	ebor107	SCHL	Immlochhammer-Bohrung
22107008	ebor107	RB	Rotary Bohrung
22107015	ebor107	AIR	Rotary Bohrung Lufthebend
22107004	ebor107	RKB	Rotary Kernbohrung
22107016	ebor107	SKB	Rotary Seilkernbohrung
22107007	ebor107	SCHT	Schachtbohrung
22107009	ebor107	SS	Baggerschlitz
22107012	ebor107	GR	Greiferbohrung
22107014	ebor107	PFAHL	Pfahlbohrung
22107017	ebor107	SCHN	Schneckenbohrung
22107019	ebor107	a	andere
22107018	ebor107	kA	keine Angaben  

drilling_methode 
22103001	ebor103	Gtec	Geotechnik
22103002	ebor103	GtheExp	Geothermie Exploration
30000000	ebor103	GtheInj	Geothermie Injektion
30000001	ebor103	GthePro	Geothermie Produktion
30000002	ebor103	DHE	Erdwärmesonde
30000003	ebor103	CCSExp	CCS Exploration
30000004	ebor103	CCSInj	CCS Injektion
30000005	ebor103	CCSPro	CCS Produktion
30000006	ebor103	TunExp	Tunnel Exploration
22103003	ebor103	belS	belastete Standorte
22103004	ebor103	Hyd	Hydrogeologie
30000007	ebor103	Gw	Grundwasser
30000008	ebor103	Pw	Trinkwasser
22103005	ebor103	Min	Mineralwasser
30000009	ebor103	Hot	Thermalwasser
22103006	ebor103	Roh	Mineralische Rohstoffe
22103007	ebor103	HCExp	Kohlenwasserstoff Exploration
30000010	ebor103	HCInj	Kohlenwasserstoff Injektion
30000011	ebor103	HCPro	Kohlenwasserstoff Produktion
30000012	ebor103	SciExp	Wissenschaftliche Exploration
22103008	ebor103	Nat	Naturgefahren
22103009	ebor103	F	Forschung
22103010	ebor103	a	anderer
22103011	ebor103	kA	keine Angaben

Stratigraphie:
USCS 
23101018	mcla101	Pt	Torf
23101001	mcla101	CH	fetter Ton
23101002	mcla101	CM	magerer Ton
23101003	mcla101	CL	siltiger Ton
23101017	mcla101	OL	organischer Ton
23101015	mcla101	ML	Silt
23101004	mcla101	CL-ML	toniger Silt
23101016	mcla101	OH	organischer Silt
23101035	mcla101	MH	elasitscher Silt
23101019	mcla101	S	Sand
23101020	mcla101	SC	toniger Sand
23101021	mcla101	SC-SM	siltiger bis toniger Sand
23101022	mcla101	SM	siltiger Sand
23101023	mcla101	SP	schlecht abgestufter Sand
23101024	mcla101	SP-SC	schlecht abgestufter Sand mit Ton
23101025	mcla101	SP-SM	schlecht abgestufter Sand mit Silt
23101029	mcla101	SW	gut abgestufter Sand
23101030	mcla101	SW-SC	gut abgestufter Sand mit Ton
23101031	mcla101	SW-SM	gut abgestufter Sand mit Silt
23101005	mcla101	G	Kies
23101006	mcla101	GC	toniger Kies
23101007	mcla101	GC-GM	siltiger bis toniger Kies
23101008	mcla101	GM	siltiger Kies
23101009	mcla101	GP	schlecht abgestufter Kies
23101010	mcla101	GP-GC	schlecht abgestufter Kies mit Ton
23101011	mcla101	GP-GM	schlecht abgestufter Kies mit Silt
23101012	mcla101	GW	gut abgestufter Kies
23101013	mcla101	GW-GC	gut abgestufter Kies mit Ton
23101014	mcla101	GW-GM	gut abgestufter Kies mit Silt
23101027	mcla101	St	Stein
23101028	mcla101	St-Bl	Steine und Blöcke
23101026	mcla101	Bl	Block
23101033	mcla101	FELS	Fels
23101032	mcla101	kunst	künstlich Auffüllung
23101034	mcla101	kA	keine Angaben

layer_grain_size 
21109001	mlpr109	f	fein
21109002	mlpr109	f-m	fein-mittel
21109003	mlpr109	m	mittel
21109004	mlpr109	m-g	mittel-grob
21109005	mlpr109	g	grob
21109006	mlpr109	f-m-g	fein-mittel-grob
21109008	mlpr109	f-g	fein-grob
21109007	mlpr109	kA	keine Angaben

Casing:
kindCasingLayer 
25000100	casi200	BC	Vollrohr
25000101	casi200	Scr	Filterrohr
25000102	casi200	CP	Standrohr
30000014	casi200	LH	Liner-Hanger
25000106	casi200	a	anderer
25000107	casi200		keine Angaben

**Comment by danjov** [comment]
Reihenfolge der GeolCodes  `reference_elevation` und `drilling_purpose` wurden am 06.12.2022 auf Prod angepasst:
```sql

-- Update ordering of existing codes
-- Schema: ibor117 (reference_elevation)
-- Free up order 4
UPDATE bdms.codelist
SET order_cli = order_cli + 1
WHERE schema_cli = 'ibor117' AND order_cli > 3;

UPDATE bdms.codelist
SET	order_cli = 4
WHERE id_cli = 30000013;

-- Schema: extended.drilling_method (drilling_purpose)
-- Reorder all codes because we have to many changes
UPDATE bdms.codelist
SET order_cli = 1
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Handbohrung';

UPDATE bdms.codelist
SET order_cli = 2
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Rammsondierung';

UPDATE bdms.codelist
SET order_cli = 3
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Rammkernsondierung';

UPDATE bdms.codelist
SET order_cli = 4
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Immlochhammer-Bohrung';

UPDATE bdms.codelist
SET order_cli = 5
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Rotary Bohrung';

UPDATE bdms.codelist
SET order_cli = 6
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Rotary Bohrung Lufthebend';

UPDATE bdms.codelist
SET order_cli = 7
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Rotary Kernbohrung';

UPDATE bdms.codelist
SET order_cli = 8
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Rotary Seilkernbohrung';

UPDATE bdms.codelist
SET order_cli = 9
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Schachtbohrung';

UPDATE bdms.codelist
SET order_cli = 10
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Baggerschlitz';

UPDATE bdms.codelist
SET order_cli = 11
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Greiferbohrung';

UPDATE bdms.codelist
SET order_cli = 12
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Pfahlbohrung';

UPDATE bdms.codelist
SET order_cli = 13
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'Schneckenbohrung';

UPDATE bdms.codelist
SET order_cli = 14
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'andere';

UPDATE bdms.codelist
SET order_cli = 15
WHERE schema_cli = 'extended.drilling_method' AND text_cli_de = 'keine Angaben';
```

**Comment by danjov** [comment]
@gysimichael Die Reihenfolge der `mcla101` Codes wurde bereits mit #179 angepasst. Welche Reihenfolge stimmt?

**Comment by gysimichael** [comment]
23101018 mcla101 Pt Torf
23101001 mcla101 CH fetter Ton
23101002 mcla101 CM magerer Ton
23101003 mcla101 CL siltiger Ton
23101017 mcla101 OL organischer Ton
23101015 mcla101 ML Silt
23101004 mcla101 CL-ML toniger Silt
23101016 mcla101 OH organischer Silt
23101035 mcla101 MH elasitscher Silt
23101019 mcla101 S Sand
30000310 mcla101 S-SC schwach toniger Sand
23101020 mcla101 SC toniger Sand
23101021 mcla101 SC-SM siltiger bis toniger Sand
30000311 mcla101 S-SM schwach siltiger Sand
23101022 mcla101 SM siltiger Sand
23101023 mcla101 SP schlecht abgestufter Sand
23101024 mcla101 SP-SC schlecht abgestufter Sand mit Ton
23101025 mcla101 SP-SM schlecht abgestufter Sand mit Silt
23101029 mcla101 SW gut abgestufter Sand
23101030 mcla101 SW-SC gut abgestufter Sand mit Ton
23101031 mcla101 SW-SM gut abgestufter Sand mit Silt
23101005 mcla101 G Kies
30000308 mcla101 G-GC schwach toniger Kies
23101006 mcla101 GC toniger Kies
23101007 mcla101 GC-GM siltiger bis toniger Kies
30000309 mcla101 G-GM schwach siltiger Kies
23101008 mcla101 GM siltiger Kies
23101009 mcla101 GP schlecht abgestufter Kies
23101010 mcla101 GP-GC schlecht abgestufter Kies mit Ton
23101011 mcla101 GP-GM schlecht abgestufter Kies mit Silt
23101012 mcla101 GW gut abgestufter Kies
23101013 mcla101 GW-GC gut abgestufter Kies mit Ton
23101014 mcla101 GW-GM gut abgestufter Kies mit Silt
23101027 mcla101 St Stein
23101028 mcla101 St-Bl Steine und Blöcke
23101026 mcla101 Bl Block
23101033 mcla101 FELS Fels
23101032 mcla101 kunst künstlich Auffüllung
23101034 mcla101 kA keine Angaben

Diese Reihenfolge passt nun. Habe die 4 neuen Codes in die Richtige Reihenfolge platziert.

**Comment by gysimichael** [comment]
21112012	mlpr112	wie	weiss
21112011	mlpr112	sch	schwarz
21112004	mlpr112	dgr	dunkelgrau
21112005	mlpr112	gra	grau
21112009	mlpr112	hgr	hellgrau
21112003	mlpr112	dbr	dunkelbraun
21112002	mlpr112	bra	braun
21112008	mlpr112	hbr	hellbraun
21112014	mlpr112	dbei	dunkelbeige
21112001	mlpr112	bei	beige
21112013	mlpr112	hbei	hellbeige
21112010	mlpr112	ock	ocker
21112015	mlpr112	doli	dunkeloliv
21112016	mlpr112	oli	oliv
21112017	mlpr112	holi	hellolive
21112018	mlpr112	dgru	dunkelgrün
21112019	mlpr112	gru	grün
21112020	mlpr112	hgru	hellgrün
21112021	mlpr112	drot	dunkelrot
21112022	mlpr112	brarot	braunrot
21112023	mlpr112	mag	magenta
21112024	mlpr112	gel	gelb
21112025	mlpr112	hgel	hellgelb

**Comment by danjov** [comment]
Reihenfolge der GeolCodes  `mcla101 (USCS)`, `mlpr109 (layer_grain_size)`, `casi200 (kindCasingLayer)` und `mlpr112` wurden am 07.12.2022 auf Prod angepasst:
```sql
-- Schema: mcla101 (USCS)
-- Reorder all codes because there are to many changes
UPDATE bdms.codelist
SET order_cli = 1
WHERE schema_cli = 'mcla101' AND text_cli_de = 'Torf';

UPDATE bdms.codelist
SET order_cli = 2
WHERE schema_cli = 'mcla101' AND text_cli_de = 'fetter Ton';

UPDATE bdms.codelist
SET order_cli = 3
WHERE schema_cli = 'mcla101' AND text_cli_de = 'magerer Ton';

UPDATE bdms.codelist
SET order_cli = 4
WHERE schema_cli = 'mcla101' AND text_cli_de = 'siltiger Ton';

UPDATE bdms.codelist
SET order_cli = 5
WHERE schema_cli = 'mcla101' AND text_cli_de = 'organischer Ton';

UPDATE bdms.codelist
SET order_cli = 6
WHERE schema_cli = 'mcla101' AND text_cli_de = 'Silt';

UPDATE bdms.codelist
SET order_cli = 7
WHERE schema_cli = 'mcla101' AND text_cli_de = 'toniger Silt';

UPDATE bdms.codelist
SET order_cli = 8
WHERE schema_cli = 'mcla101' AND text_cli_de = 'organischer Silt';

UPDATE bdms.codelist
SET order_cli = 9
WHERE schema_cli = 'mcla101' AND text_cli_de = 'elasitscher Silt';

UPDATE bdms.codelist
SET order_cli = 10
WHERE schema_cli = 'mcla101' AND text_cli_de = 'Sand';

UPDATE bdms.codelist
SET order_cli = 11
WHERE schema_cli = 'mcla101' AND text_cli_de = 'schwach toniger Sand';

UPDATE bdms.codelist
SET order_cli = 12
WHERE schema_cli = 'mcla101' AND text_cli_de = 'toniger Sand';

UPDATE bdms.codelist
SET order_cli = 13
WHERE schema_cli = 'mcla101' AND text_cli_de = 'siltiger bis toniger Sand';

UPDATE bdms.codelist
SET order_cli = 14
WHERE schema_cli = 'mcla101' AND text_cli_de = 'schwach siltiger Sand';

UPDATE bdms.codelist
SET order_cli = 15
WHERE schema_cli = 'mcla101' AND text_cli_de = 'siltiger Sand';

UPDATE bdms.codelist
SET order_cli = 16
WHERE schema_cli = 'mcla101' AND text_cli_de = 'schlecht abgestufter Sand';

UPDATE bdms.codelist
SET order_cli = 17
WHERE schema_cli = 'mcla101' AND text_cli_de = 'schlecht abgestufter Sand mit Ton';

UPDATE bdms.codelist
SET order_cli = 18
WHERE schema_cli = 'mcla101' AND text_cli_de = 'schlecht abgestufter Sand mit Silt';

UPDATE bdms.codelist
SET order_cli = 19
WHERE schema_cli = 'mcla101' AND text_cli_de = 'gut abgestufter Sand';

UPDATE bdms.codelist
SET order_cli = 20
WHERE schema_cli = 'mcla101' AND text_cli_de = 'gut abgestufter Sand mit Ton';

UPDATE bdms.codelist
SET order_cli = 21
WHERE schema_cli = 'mcla101' AND text_cli_de = 'gut abgestufter Sand mit Silt';

UPDATE bdms.codelist
SET order_cli = 22
WHERE schema_cli = 'mcla101' AND text_cli_de = 'Kies';

UPDATE bdms.codelist
SET order_cli = 23
WHERE schema_cli = 'mcla101' AND text_cli_de = 'schwach toniger Kies';

UPDATE bdms.codelist
SET order_cli = 24
WHERE schema_cli = 'mcla101' AND text_cli_de = 'toniger Kies';

UPDATE bdms.codelist
SET order_cli = 25
WHERE schema_cli = 'mcla101' AND text_cli_de = 'siltiger bis toniger Kies';

UPDATE bdms.codelist
SET order_cli = 26
WHERE schema_cli = 'mcla101' AND text_cli_de = 'schwach siltiger Kies';

UPDATE bdms.codelist
SET order_cli = 27
WHERE schema_cli = 'mcla101' AND text_cli_de = 'siltiger Kies';

UPDATE bdms.codelist
SET order_cli = 28
WHERE schema_cli = 'mcla101' AND text_cli_de = 'schlecht abgestufter Kies';

UPDATE bdms.codelist
SET order_cli = 29
WHERE schema_cli = 'mcla101' AND text_cli_de = 'schlecht abgestufter Kies mit Ton';

UPDATE bdms.codelist
SET order_cli = 30
WHERE schema_cli = 'mcla101' AND text_cli_de = 'schlecht abgestufter Kies mit Silt';

UPDATE bdms.codelist
SET order_cli = 31
WHERE schema_cli = 'mcla101' AND text_cli_de = 'gut abgestufter Kies';

UPDATE bdms.codelist
SET order_cli = 32
WHERE schema_cli = 'mcla101' AND text_cli_de = 'gut abgestufter Kies mit Ton';

UPDATE bdms.codelist
SET order_cli = 33
WHERE schema_cli = 'mcla101' AND text_cli_de = 'gut abgestufter Kies mit Silt';

UPDATE bdms.codelist
SET order_cli = 34
WHERE schema_cli = 'mcla101' AND text_cli_de = 'Stein';

UPDATE bdms.codelist
SET order_cli = 35
WHERE schema_cli = 'mcla101' AND text_cli_de = 'Steine und Blöcke';

UPDATE bdms.codelist
SET order_cli = 36
WHERE schema_cli = 'mcla101' AND text_cli_de = 'Block';

UPDATE bdms.codelist
SET order_cli = 37
WHERE schema_cli = 'mcla101' AND text_cli_de = 'Fels';

UPDATE bdms.codelist
SET order_cli = 38
WHERE schema_cli = 'mcla101' AND text_cli_de = 'künstliche Auffüllung';

UPDATE bdms.codelist
SET order_cli = 39
WHERE schema_cli = 'mcla101' AND text_cli_de = 'keine Angaben'

-- Schema: mlpr109 (layer_grain_size)
-- Switch order of last two codes
UPDATE bdms.codelist
SET	order_cli = order_cli + 1
WHERE id_cli = 21109007;

UPDATE bdms.codelist
SET	order_cli = order_cli - 1
WHERE id_cli = 21109008;

-- Schema: casi200 (kindCasingLayer)
-- Update ordering of existing codes
UPDATE bdms.codelist
SET	order_cli = order_cli + 1
WHERE schema_cli = 'casi200' AND order_cli > 3;

UPDATE bdms.codelist
SET	order_cli = 4
WHERE id_cli = 30000014;

-- Schema: mlpr112
-- Update ordering of existing codes
UPDATE bdms.codelist
SET order_cli = 1
WHERE schema_cli = 'mlpr112' AND text_cli_de = 'weiss';

UPDATE bdms.codelist
SET order_cli = 2
WHERE schema_cli = 'mlpr112' AND text_cli_de = 'schwarz';

UPDATE bdms.codelist
SET order_cli = 3
WHERE schema_cli = 'mlpr112' AND text_cli_de = 'dunkelgrau';

UPDATE bdms.codelist
SET order_cli = 4
WHERE schema_cli = 'mlpr112' AND text_cli_de = 'grau';

UPDATE bdms.codelist
SET order_cli = 5
WHERE schema_cli = 'mlpr112' AND text_cli_de = 'hellgrau';

UPDATE bdms.codelist
SET order_cli = 6
WHERE schema_cli = 'mlpr112' AND text_cli_de = 'dunkelbraun';

UPDATE bdms.codelist
SET order_cli = 7
WHERE schema_cli = 'mlpr112' AND text_cli_de = 'braun';

UPDATE bdms.codelist
SET order_cli = 8
WHERE schema_cli = 'mlpr112' AND text_cli_de = 'hellbraun';

UPDATE bdms.codelist
SET order_cli = 9
WHERE schema_cli = 'mlpr112' AND text_cli_de = 'dunkelbeige';

UPDATE bdms.codelist
SET order_cli = 10
WHERE schema_cli = 'mlpr112' AND text_cli_de = 'beige';

UPDATE bdms.codelist
SET order_cli = 11
WHERE schema_cli = 'mlpr112' AND text_cli_de = 'hellbeige';

UPDATE bdms.codelist
SET order_cli = 12
WHERE schema_cli = 'mlpr112' AND text_cli_de = 'ocker';
```
