### ISSUE TITLE
Completion löschen ist inkonsistent

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#1003]
Ein Casing kann aktuell nur gelöscht werden, wenn es in keiner Instrumentation oder Observation referenziert wird. Wenn aber die Completion mit dem Casing gelöscht wird, dann werden die Fremdschlüssel auf das Casing mitgelöscht.

**Comment by RBordoni** [comment]
Test Version: 2.0.559
Neu werden die Fremdschlüssel beim Löschen eines Casing konsequent mitgelöscht

**Comment by gysimichael** [comment]
sehr gut, danke
