### ISSUE TITLE
Konzept für Bohrlochgeometrie

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#1016]

**Comment by gysimichael** [comment]
1. Standort: Koordinaten und Referenz Ansatzhöhe sind relevant für dei Berechnung der Bohrlochgeometrie
2. Bohrung:
            a.) Bohrmethode, Bohrgut, Datum Bohrbeginn, Datum Bohrende, Bohrdurchmesser, Inklination am Bohransatzpunkt (kann aus DB gelöscht werden), Einfallsrichtung am Bohransatzpunkt (kann aus DB gelöscht werden), Ink. Richtung Genauigkeit (kann aus DB gelöscht werden) können aus Bohrung entfernt werden
            b.) Bohrlochteufe [m TVD], Top Fels(unverwittert) [m TVD] und Top Fels (verwittert) [m TVD] soll, basierend auf dem Bohrpfad, berechnet werden
3. Stratigraphie:
            a.) Lithologie: Alle Teufen sollten sowhol als MD als auch als TVD dargestellt werden können; Wechsel der angezeigten Eihnheit soll über Header ansteuert werden
            b.) Chronostratigraphie: Alle Teufen sollten sowhol als MD als auch als TVD dargestellt werden können; Wechsel der angezeigten Eihnheit soll über Header ansteuert werden
            c.) Lithostratigraphie: Alle Teufen sollten sowhol als MD als auch als TVD dargestellt werden können; Wechsel der angezeigten Eihnheit soll über Header ansteuert werden
4. Hydrogeologie:
            a.) Wasserzutritt: Je nach eingabe von MD oder m ü.M. soll das andere Feld automatisch berechnet werden
            b.) Hydrotest: Je nach eingabe von MD oder m ü.M. soll das andere Feld automatisch berechnet werden
            c.) Grundwassermessung: Je nach eingabe von MD oder m ü.M. soll das andere Feld automatisch berechnet werden
            d.) Feldmessung: Je nach eingabe von MD oder m ü.M. soll das andere Feld automatisch berechnet werden
5. Ausbau:
            a.) Verrohrung: Alle Teufen sollten sowhol als MD als auch als TVD dargestellt werden können; Wechsel der angezeigten Eihnheit soll über Header ansteuert werden
            b.) Instrumentierung: Alle Teufen sollten sowhol als MD als auch als TVD dargestellt werden können; Wechsel der angezeigten Eihnheit soll über Header ansteuert werden
            c.) Hinterfüllung: Alle Teufen sollten sowhol als MD als auch als TVD dargestellt werden können; Wechsel der angezeigten Eihnheit soll über Header ansteuert werden

6. Bohrlochgeometrie:
            a). Pro Teleskopierte Einheit braucht es folgende Attribute:
                        - Sektionsname (neu), Bohrmethode, Bohrspühlung (neu), Datum Bohrbeginn, Datum Bohrende, Bohrgut, Bohrdurchmesser, Bohrkerndurchmesser (neu), Überbohrt/Überkernt (neu)
                        - Wenn Überbohrt/Überkernt (neu) auf ja gestellt ist, alle Attribute nochmals, ausser Sektiosname
            b.) Wenn keinen geometrie exisitert, sollte Bohrung automatisch als vertikal angenommen werden.
            c.) Geometrie erfassen:
                        - 3 mögliche Input Formate:
                                   - X, Y, Z (relativ oder absolut zur aktuellen Koordinaten)
                                   - Azimut und Inklination
                                   - Roll, pitch, yaw (https://mecharithm.com/learning/lesson/explicit-representations-orientation-robotics-roll-pitch-yaw-angles-15)
                        - Speicherung der Daten als X, Y, Z in der Datenbank
                        - Berechnung des aktuellen Bohrpfades (für MD und TVD referenzierung) mit «minimal curvature» Algorithmus (https://maxwellsci.com/print/rjaset/v2-679-686.pdf)
            d.) Grafische Darstellung:
                        - 2D Crossplots XY, XZ, YZ und freie Gradwahl auf XY Achse und Z
                        - 3D Option des Bohrpfades

7. Reiter aufteilung:
            a.) Sektionskarten
            b.) Geometrie
            c.) Visualisierung der Geometrie ev. Visualisierung der Sektionen auf der Seite

**Comment by gysimichael** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/U80864~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/U80864~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


water | Wasser | eau | acqua
-- | -- | -- | --
all oil | Öl | huiles | oli
pneumatic – air | pneumatisch - Luft | pneumatique - air | pneumatico - aria
pneumatic – gas | pneumatisch - Gas | pneumatique - gaz | pneumatico - gas
pneumatic – mist | pneumatisch - Nebel | pneumatique - brouillard | pneumatico - nebbia
pneumatic – foam | pneumatisch - Schaum | pneumatique - mousse | pneumatico - schiuma
water-based non-dispersed - bentonite,   polymers | nicht dispergiert auf Wasserbasis - Bentonit, Polymere | non dispersé à base d'eau - bentonite, polymères | non dispersi a base d'acqua - bentonite, polimeri
water-based non-dispersed - NaCl, KCl,   bentonite, polymer | nicht dispergiert auf Wasserbasis - NaCl, KCl, Bentonit, Polymer | non dispersé à base d'eau - NaCl, KCl, bentonite, polymères | non dispersi a base d'acqua - NaCl, KCl, bentonite, polimeri
water-based non-dispersed - K-silicate,   Na-silicate, polymer | nicht dispergiert auf Wasserbasis - K-Silikat, Na-Silikat, Polymer | non dispersé à base d'eau - silicate de K, silicate de Na, polymère | non dispersi a base d'acqua - K-silicato, Na-silicato, polimero
water-based dispersed - lignite,   lignosulfonate, bentonite, polymers, phosphate | dispergiert auf Wasserbasis - Braunkohle, Lignosulfonat, Bentonit,   Polymere, Phosphat | dispersé à base d'eau - lignite, lignosulfonate, bentonite, polymères,   phosphate | dispersa a base acquosa - lignite, lignosolfonato, bentonite, polimeri,   fosfati
water-based dispersed - lime, gypsum,   NaCl, CaCl2, lignite, lignosulfonate, bentonite, polymers | dispergiert auf Wasserbasis - Kalk, Gips, NaCl, CaCl2, Braunkohle,   Lignosulfonat, Bentonit, Polymere | dispersé à base d'eau - chaux, gypse, NaCl, CaCl2, lignite,   lignosulfonate, bentonite, polymères | dispersa a base acquosa - calce, gesso, NaCl, CaCl2, lignite,   lignosolfonato, bentonite, polimeri
oil-based - low toxicity | auf Ölbasis - geringe Toxizität | à base d'huile - faible toxicité | a base di olio - bassa tossicità
oil-based - invert emulsion | auf Ölbasis - Invertemulsion | à base d'huile - émulsion inversée | a base di olio - emulsione inversa
oil-based - dispersed oil | auf Ölbasis - dispergiertes Öl | à base d'huile - huile dispersée | a base di olio - olio disperso
oil-based – diesel | auf Ölbasis - Diesel | à base d'huile - diesel | a base di olio - diesel
oil-based – synthetic | auf Ölbasis - synthetisch | à base d'huile - synthétique | a base di olio - sintetico
oil-based - non-aqueous | auf Ölbasis - nicht wässrig | à base d'huile - non aqueuse | a base di olio - non acquoso
  |   |   |  
resin | Harz | résine | resina
section name | Sektionsname | nom de la section | nome della sezione
core diameter | Bohrkerndurchmesser | diamètre de la carotte | diametro della carota
reaming/overcoring | aufgebohrt/überkernt | alésage/surcarottage | alesatura/tecnica di overcoring
drilling mud type | Bohrspülung Typ | type de boue de forage | tipo di fango di perforazione
drilling mud subtype | Bohrspülung Subtyp | sous-type de boue de forage | sottotipo di fango di perforazione



</body>

</html>

**Comment by gysimichael** [comment]
water
all oil
pneumatic
water-based non-dispersed
water-based dispersed 
oil-based

Wären "drilling mud type", die Einträge hinter dem - wären dann "drilling mud subtype".

UI technisch sollten, wenn man die Auswahl beim "drilling mud type" gewählt hat, dann nur noch auf die möglichen subtypes beschränken

**Comment by gysimichael** [comment]
die codelisten bezeichungen könnte man auch gleich an den neuen standart anpassen:
-extended.status -> borehole_status
-extended.purpose -> borehole_purpose
-extended.drilling_method ->drilling_method
-custom.qt_bore_inc_dir -> brauchts wohl gar nicht meht mit dem neuen Modul
-custom.cuttings -> borehole_cuttings_core

**Comment by RBordoni** [comment]
Die Konzeptphase ist abgeschlossen. Die weiteren Arbeiten werden durch die obigen Issues abgedeckt.
