### ISSUE TITLE
Fehler bei erneutem Speichern von Hydrotests

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#1021]
**Steps to reproduce**
1. Hydrotest mit Resultat erfassen, speichern
3. Hydrotest bearbeiten und irgendwas ändern, speichern

**Expected behavior**
Änderungen können gespeichert werden

**Current behavior**
Es kommt eine Fehlermeldung und die Änderung kann nicht gespeichert werden: _An error occurred while saving the entity changes._

**Comment by gysimichael** [comment]
ist in Ordnung, danke
