### ISSUE TITLE
Feedback Funktion zurückbauen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#1024]
Entscheid Michael Gysi per Mail 14.02.2024: Die Feedback-Funktion in Boreholes braucht es nicht mehr und kann zurückgebaut werden.

**Comment by MiraGeowerkstatt** [comment]
Mit #1088 und https://github.com/geoadmin/config-bdms/pull/19 abgeschlossen.

**Comment by MiraGeowerkstatt** [comment]
Mit https://github.com/geoadmin/suite-bdms/pull/1088 und https://github.com/geoadmin/config-bdms/pull/19 abgeschlossen.

**Comment by gysimichael** [comment]
danke
