### ISSUE TITLE
Hight reference system Eintrag wird nicht angezeigt

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#1037]
Mir ist gerade Aufgefallen, das bei Location -> Hight reference system keinen Eintrag angezeigt wird

![Image](https://github.com/geoadmin/suite-bdms/assets/108096632/f9311503-eac9-4569-99d0-3791d6880315)

**Comment by MiraGeowerkstatt** [comment]
@gysimichael 

Ist es richtig, dass das Feld rein informativ (d.h. nicht editierbar) ist?
Im aktuellen Prod-Release (2.0.506)  vom Dezember 2023 ist es auf jeden Fall schon so:
![Image](https://github.com/geoadmin/suite-bdms/assets/49144408/ca07e2c3-d9e0-4b6b-bf80-fd4aa12d8e08)

**Comment by gysimichael** [comment]
ja genau, es gibt zurzeit nur dieses Referenzsystem, und soll in die DB geschrieben werden, und im UI angezeigt, aber nicht editierbar sein

**Comment by gysimichael** [comment]
Funktioniert wieder, danke!
