### ISSUE TITLE
Feld `is_last` bei Chronostratigraphy, Lithostratigraphy, FaciesDescription und LithlogyDescription entfernen

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#1039]
Scheinbar wird das Feld `is_last` bei Chronostratigraphy, Lithostratigraphy, FaciesDescription und LithlogyDescription nicht (mehr) verwendet und soll deshalb gelöscht werden.

**Comment by gysimichael** [comment]
danke!
