### ISSUE TITLE
Geolcodes in Codelist-Tabelle - Veraltete Einträge überprüfen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#105]
In der Codelist-Tabelle sind zum Teil alte Einträge vorhanden, die nicht mehr verwendet werden ("borehole_from" und "layer_form" und evtl. weitere). Die Einträge (oder ein Teil davon?) sind veraltet und die Übersetzungen werden evtl. über die andere Liste gemacht (json). 
Es gilt dem Nachzugehen und die geeignete Bereinigung vorzunehmen!

**Comment by gysimichael** [comment]
Das sind einträge, die über die UI Übersetzung geregelt sind bei Borehole_from und layer_from. Layer_kind weiss ich nicht woher es kommt, sehe aber Zurzeit keine Verwendung. Ist wohl ein Relikt aus der Vergangenheit

**Comment by RBordoni** [comment]
Duplikat von #42
