### ISSUE TITLE
sub-logo und icon in boreholes.swissgeol.ch einbauen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#1052]
Bitte sowohl sub-logo für boreholes.swissgeol.ch als auch das icon, wo möglich einbauen.

.svg, .png und .ai sind unter: https://ebpgroup.sharepoint.com/:u:/r/sites/CH_P_223443/Freigegebene%20Dokumente/General/[Logos.zip](https://ebpgroup.sharepoint.com/:u:/r/sites/CH_P_223443/Freigegebene%20Dokumente/General/Logos.zip?csf=1&web=1&e=TEHwlk)?csf=1&web=1&e=TEHwlk

**Comment by gysimichael** [comment]
![Image](https://github.com/geoadmin/suite-bdms/assets/108096632/7788cb21-8751-409a-99e4-4c2082283607)

das favicon oben im Reiter ist noch das alte und müsste mit dem favicon ersetzt werden

**Comment by MiraGeowerkstatt** [comment]
Versuche mal ein force reload (Shift F5) dann sollte es gehen.

**Comment by gysimichael** [comment]
funktioniert, danke!

**Comment by gysimichael** [comment]
sieht echt cool aus, hab Freude!!!
