### ISSUE TITLE
Cookies werden beim Logout nicht vollständig bereinigt

### ISSUE THREAD

**Issue by flenny** [geoadmin/suite-bdms#1054]
Die Cookies für https://*****.auth.eu-west-1.amazoncognito.com/ werden beim Logout aus der Applikation nicht gelöscht, was dazu führt, dass bei einem erneuten Login sofort wieder eingeloggt wird (ohne Möglichkeit den Benutzer zu wechseln).

**Comment by gysimichael** [comment]
klappt sehr gut, danke
