### ISSUE TITLE
DescriptionQuality in LithologyFields umbenennen

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#1056]
> Unter settings -> Editor -> Lithologiefelder müsste das zweite Feld nicht "description_quality" sondern "completeness" sein.
> 
> Das Gleiche müsste man sowohl bei settings -> Editor -> Suchfilter Lithologie und bei Editor -> Suchfilter Lithologie ändern
> 
> Da wir den Viewer eh umbauen, muss dieser nicht korrigiert werden

_Original aus https://github.com/geoadmin/suite-bdms/issues/254#issuecomment-1961824430_

Ging bei der Umsetzung von https://github.com/geoadmin/suite-bdms/pull/1014 vergessen.

**Comment by gysimichael** [comment]
danke für die Umsetzung!
