### ISSUE TITLE
Invalid FormFields aus FieldArrays werden nicht rot eingefärbt

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#1063]
In den HydrotestResultaten und CasingElementen werden die Pflichtfelder nicht mit einem roten Hintegrund dargestellt, wenn sie leer sind. Habe keinen Lösung dazu gefunden und deshalb einen Issue bei React Hook Form erstellt: https://github.com/react-hook-form/react-hook-form/issues/11568

**Comment by gysimichael** [comment]
sehr gut und nütuzlich, danke!
