### ISSUE TITLE
Login-Screen entfernen

### ISSUE THREAD

**Issue by Philippluca** [geoadmin/suite-bdms#1068]
- [x] Navigation auf Applikation leitet direkt zum OIDC Login weiter.
- [x] Login Screen Admin Seite zurückbauen.
- [x] Login Screen Content API zurückbauen.
- [x] Neue / Disabled Benutzer über fehlende Rechte informieren.

Linker Teil dieser View wird nicht mehr gebraucht. 
Grüner Login-Button soll nicht erscheinen jedoch einen automatischen Login zur Folge haben.
![image](https://github.com/geoadmin/suite-bdms/assets/2191817/a540ace4-7f23-4814-bbb2-94171f10414f)

**Comment by gysimichael** [comment]
funktionniert bestens, danke!
