### ISSUE TITLE
Feld Öffentlich im Publikationsworkflow entfernen.

### ISSUE THREAD

**Issue by Philippluca** [geoadmin/suite-bdms#1070]

**Comment by RBordoni** [comment]
Info:
Im letzten Schritt des Publikations-Workflows erscheinen die Buttons _**Weiterleiten**_ und _**Öffentlich**_.
Beide Buttos führen eine Weiterleitung aus:
- Bei _**Weiterleiten**_ ist der nachträglich erscheinende Slider immer links auf "Versteckt" 
- Bei _**Öffentlich**_ ist der nachträglich erscheinende Slider immer rechts auf "Sichtbar"

![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/d2d1375d-5b41-4cc1-8694-f5612e314b8a)

Strange ist es nachher. Das Bewegen des Sliders ist nicht persistent. Komme ich jeweils neu auf die Bohrung, ist er wieder zurückgesetzt. 

![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/f22c56ce-b78a-49d1-b092-dcc1a66aef2e)

Frage: Alles muss weg?

**Comment by RBordoni** [comment]
Ja , alles muss weg. D.h.:

1. Es gibt nur noch _Ablehnen_ und Weiterleiten
![image](https://github.com/geoadmin/suite-bdms/assets/31883445/8a6cfc44-8e92-4530-9b9b-007d4b304570)

2. Der Slider gibt es nicht mehr
![image](https://github.com/geoadmin/suite-bdms/assets/31883445/9f50d0f2-a96f-40a3-a0d9-910e4e95f97d)

**Comment by gysimichael** [comment]
sieht gut aus, danke!
