### ISSUE TITLE
Lithology Filter im Viewer Modus führen zu Fehler

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#1090]
**Repro Staps:**

1. Viewer Modus
2. Serch Filter Lithology aufklappen
3. Beliebiges Filterfeld ausfüllen oder auswählen

**Beobachtet:**

![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/b41035e8-731b-4643-ba50-c1787688b0b6)

**Comment by gysimichael** [comment]
funktioniert, danke! wow, an was man alles denken muss, respektive was so Klammern auslösen können...
