### ISSUE TITLE
falsche codeliste im dropdown

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#11]
Im Editor Modus unter Bohrung technisches Attribut "qt_depth" gibt es ein falsches Dropdown. Es sollten die Werte von ebor108 dargestellt werden und nicht die von ebor115.

Alle Werte ebor105 können gelöscht werden da sie nicht gebraucht werden.

**Comment by gysimichael** [comment]
Auch im Viewer Mode bei den Filtern bei borehole qt_depth ist falsches drop down hinterlegt, gleich wie oben erwähnt

**Comment by danjov** [comment]
Im Dropdown werden die Werte von `custom.qt_depth` angezeigt. In der DB haben wir keine Codeliste mit dem Schema `ebor108` oder `ebor115`.  
Ich habe in deinem Excel mit den neuen Geolcodes nachgeschaut und dort sehe ich die `ebor108`-Werte. Die Werte entsprechen dem Schema `custom.qt_depth`, ausser dass der Wert _unbekannt_ in der aktuellen DB fehlt.

Ich denke das müssen wir kurz zusammen anschauen.

**Comment by gysimichael** [comment]
Ah, ok, dann war supsi mit der Umsetzung nicht konsequent. Also custom.qt_top_bedrock ist ebor108, custom.qt_depth ist ebor 115, somit kann custom.qt.depth gelöscht werden und bei diesem dropdown sowohl bei der Eingabe wie auch bei den Filtern mit custom.qt_top_bedrock ersetzt werden.
Eventuell dies erst durchführen, wenn auch die Namen gemäss meiner Liste geändert wurden

**Comment by danjov** [comment]
Hängt mit #140 zusammen

**Comment by gysimichael** [comment]
bin mir nicht sicher ob das so ist; das ging bei Supsi vergessen, zu fixen... zumindest im Dropdown  unter Bohrung technisches Attribut "qt_depth" müsste man dies ändern, dass es gleich ist wie bei total_depth_tvd_qt, das hängt glaube ich nicht mit #140 zusammen, zumindest nicht für das Feld

**Comment by danjov** [comment]
Alles klar. Das Löschen von `qt_depth` wird dann mit #140 erledigt, da es dort bereits korrekt dokumentiert ist.

**Comment by gysimichael** [comment]
müsste man da ev. noch die DB in diesem Feld neu migrieren, weil nun die Codelisteneinträge geändert haben?

**Comment by MiraGeowerkstatt** [comment]
Nein, an der DB haben wir in diesem Issue nichts geändert. Die Codelist "qt_depth" ist jetzt einfach im Client nicht mehr in Gebrauch und könnte aus der DB gelöscht werden. Das ist aber in #140 dokumentiert.

**Comment by gysimichael** [comment]
Ich meine mehr, in diesem Feld hatte es ja Einträge in der Datenbank. Da nun im Dropdown die GeolCodes geändert haben, müsste man da dann nicht alle Datenbankeinträge in diesem Feld neu schreiben. Diese lauten ja wohl noch auf die alten GeolCodes, oder mache ich da ein Durcheinander?

**Comment by gysimichael** [comment]
wie ich sehe hat das Werte drin, somit habe ich da wohl etwas falsch überlegt, oder ihr automatisch das mit dem Austausch der Werteliste gemacht.

Scheint alles in Ordnung zu sein, Danke!

**Comment by gysimichael** [comment]
Habe nun doch nochmal die DB von boreholes.swissgeol.ch und dev.boreholes.swissgeol.ch verglichen, da stimmen die Zahlen unter der verschiedenen Wert im Dropdown nicht. Es scheint man müsste da wohl doch nochmal die Migration der Wert für diese Attribut von der prod DB richtig machen.

**Comment by gysimichael** [comment]
Eventuell müsste man das dann auch gleich auf der Prod DB umsetzten, damit wir dies dann auch auf der Haupt DB richtig haben.

**Comment by MiraGeowerkstatt** [comment]
Die Spalte "qt_depth" der Tabelle 'borehole' wurde am 16.12.22 auf DEV, TEST und PROD migriert. Neu werden die Codes der Schemas 'custom.qt_top_bedrock' statt wie bislang 'custom.qt_depth'  verwendet.

! Auf PROD werden die Werte im  'qt_depth' Dropdown erst dann richtig angezeigt, wenn die neuste Version des Clients dort released wurde!

```sql

-- Update Boreholes
-- Translate column 'qt_depth' from schema 'custom.qt_depth' to 'custom.qt_top_bedrock'.
UPDATE bdms.borehole
SET qt_depth_id_cli = 22108001
WHERE qt_depth_id_cli = 22115001;

UPDATE bdms.borehole
SET qt_depth_id_cli = 22108002
WHERE qt_depth_id_cli = 22115002;

UPDATE bdms.borehole
SET qt_depth_id_cli = 22108003
WHERE qt_depth_id_cli = 22115003;

UPDATE bdms.borehole
SET qt_depth_id_cli = 22108004
WHERE qt_depth_id_cli = 22115004;

UPDATE bdms.borehole
SET qt_depth_id_cli = 22108005
WHERE qt_depth_id_cli = 22115005;
```
