### ISSUE TITLE
Dropdown für Lithologie ist im Bulk Editing nicht hierarchisch eingerückt

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#110]
**Repro Steps:**

1. Als Editor eine Bohrung selektieren (Häkchen setzen)
2. Bulk editing starten
3. Lithology top bedrock auswählen

**Erwartet:**
Die auswahlliste ist hierarchisch strukturiert wie beim normalen Editieren

![Image](https://user-images.githubusercontent.com/31883445/195099091-a46dc268-ec64-4ffb-bf13-8fb40a5c1fc0.png)

**Beobachtet:**
Die Hierarchien sind nicht abgebildet

![Image](https://user-images.githubusercontent.com/31883445/195099275-cc31b2a6-af6e-4e28-9ee3-32329079d658.png)

**Anmerkung:** Ebenso bei _Lithostartigrphy top bedrock_ und _Chronostratigraphy top bedrock_

**Comment by RBordoni** [comment]
Im Rahmen des Neubaus der diversen Strati, fallen gewisse dieser Felder evtl. weg. Die Anpassungen sind nur vorzunehmen, wenn die Felder nicht wegfallen.

**Comment by RBordoni** [comment]
Besprechung 27.10.2022: Die Felder werden beim Stratigraphieprofil verschwinden, nicht aber beim Borehole. Darum sind sie im Bulk editing anzupassen.

**Comment by gysimichael** [comment]
cool, danke fürs umsetzten. Sieht gut aus.
