### ISSUE TITLE
Erfassung von Bohrloch Sektionen

### ISSUE THREAD

**Issue by patrickackermann** [geoadmin/suite-bdms#1102]
Siehe auch https://github.com/geoadmin/suite-bdms/issues/1016

- Neuer Reiter Sektionen
- Pro Teleskopierte Einheit braucht es folgende Attribute:
  - Sektionsname (neu, einziges Pflichtfeld)
  - Bohrmethode
  - Bohrspühlung Typ (neu)
  - Bohrspühlung Subtyp (neu)
  - Datum Bohrbeginn
  - Datum Bohrende
  - Bohrgut
  - Bohrdurchmesser
  - Bohrkerndurchmesser (neu)
  - Tiefe von
  - Tiefe zu
  - Überbohrt/Überkernt (neu)
 
- Wenn Überbohrt/Überkernt (neu) auf ja gestellt ist, alle Attribute nochmals, ausser Sektiosname
- Entsprechende Felder im Reiter Bohrung entfernen
  - Bohrmethode
  - Bohrgut (Bohrklein, Kern)
  - Datum Bohrbeginn
  - Datum Bohrende
  - Bohrdurchmesser

**Comment by patrickackermann** [comment]
@gysimichael Kann eine Sektion nur einmal _Überbohrt/Überkernt_ sein oder kann bei den Attributen der Überbohrung/Überkernung wieder _Überbohrt/Überkernt_ ausgewählt werden, was zur Folge hat, dass die Attribute erneut nochmals aufgeführt werden?

**Comment by gysimichael** [comment]
ja, das kann sein, somit ist das zweite richitg

**Comment by gysimichael** [comment]
@patrickackermann in der Disskusion mit dem Kanton Aargau tauchte die Frage auf, ob man Durchmesser im UI sowol als mm aber auch Zoll darstellen könnte?
Das würde bedeuten, dass man neben dem Eingabefeld ein weiters Feld hat, das Anzeigt, welche Einheit und es automatisch umgerechnet wird. Sprich in der DB immer mm, aber im Frontend je nach Anzeige. 
Das würde auch bedeuten, das die Eingabe in der Einheit, die im Feld daneben steht, erfolgen kann.

Fals möglich, müsste man das dann auch beim Casing bei den Durchmessern anwenden können

**Comment by gysimichael** [comment]
@patrickackermann das bezüglich überbohrt/überkernt könnte man ähnlich lösen wie bei casing element oder Field measurments, oder was meinst du?

**Comment by gysimichael** [comment]
@patrickackermann absolut richtig, es braucht noch From depth [m MD] und To depth [m MD], diese auch bei overcoring

**Comment by patrickackermann** [comment]
> das bezüglich überbohrt/überkernt könnte man ähnlich lösen wie bei casing element oder Field measurments, oder was meinst du?

Ja, ich orientiere mich am Casing. Die Attribute, die beim overcoring wiederholt werden (alle auser Name) stelle ich in einer Tabelle dar. Ursprünglich hatte ich geplant beim Auswählen von _Überbohrt_ eine neue Zelle zu generieren. Ein Expliziter _Add_ und _Löschen_ Button wie in Casing oder Field Measurements ist für den Benutzer aber wahrscheinlich intuitiver.

> absolut richtig, es braucht noch From depth [m MD] und To depth [m MD], diese auch bei overcoring

Ich habe die Felder in die Beschreibung aufgenommen.

**Comment by gysimichael** [comment]
@patrickackermann bei den Dropdowns der Bohrspülung bitte auch noch "keine Angabe" und "andere" mit dazu nehmen, um konsistent mit den anderen Dropdowns zu sein

**Comment by gysimichael** [comment]
@patrickackermann auch als Erkenntnis aus den vorhergehenden Modulen wäre es gut, wenn beim überbohren die Intervalle von der Sektion automatisch übernommen werden, als Vorschlag, diese aber überschrieben werden können, ähnlich wie das bei Lithologie oder Chronostratigraphie der Fall ist. Hier aber sowohl Top wie auch Bottom

**Comment by patrickackermann** [comment]
https://github.com/geoadmin/suite-bdms/issues/1102#issuecomment-1999909991
> [...] ob man Durchmesser im UI sowol als mm aber auch Zoll darstellen könnte?

@gysimichael Ist das als Hilfe beim Eingeben, wenn man Daten in Zoll hat oder auch beim Anzeigen?
Ich bin mir nicht sicher was mehr sinn macht, für jedes Durchmesser Feld je eine Auswahl für die Einheit oder Eine Auswahl, die die Einheit auf dem ganzen _Sections_ Panel umstellt?

**Comment by patrickackermann** [comment]
@gysimichael Mit dem Entfernen der nun überflüssigen Felder in _Bohrung_ würde ich diese Spalten in der _borehole_ Tabelle entfernen und in die neuen _sections_ Tabellen migrieren. Als Sektionsname würde ich einfach "Sektion" einfügen.

**Comment by gysimichael** [comment]
> [#1102 (comment)](https://github.com/geoadmin/suite-bdms/issues/1102#issuecomment-1999909991)
> 
> > [...] ob man Durchmesser im UI sowol als mm aber auch Zoll darstellen könnte?
> 
> @gysimichael Ist das als Hilfe beim Eingeben, wenn man Daten in Zoll hat oder auch beim Anzeigen? Ich bin mir nicht sicher was mehr sinn macht, für jedes Durchmesser Feld je eine Auswahl für die Einheit oder Eine Auswahl, die die Einheit auf dem ganzen _Sections_ Panel umstellt?

Cool wäre, wenn man irgendwo übergeornet die möglichkeit hätte, das System umzustellen:
1. mm / "
2. m / ft
3. MD / TVD

Und soll alle Werte sowohl in der Anzeige wie auch in der Angabe inkluisve Beschriftungen wechseln würden. in der DB würde aber mm, m und MD gespeichert.

**Comment by gysimichael** [comment]
> @gysimichael Mit dem Entfernen der nun überflüssigen Felder in _Bohrung_ würde ich diese Spalten in der _borehole_ Tabelle entfernen und in die neuen _sections_ Tabellen migrieren. Als Sektionsname würde ich einfach "Sektion" einfügen.

Ich verstehe nicht ganz was du damit meinst. Eventuell sollten wir kurz telefonieren.

Mein Verständnis:

- Die Felder, die nun aus dem UI bei "borehole" entfernt wurden, können in der DB borehole tabelle entfernt werden, das ist richtig
- für die verbleibenden frage ich mich, ob es nicht sinnvoller ist, diese in der DB borehole tabelle zu lassen, die Felder auf dem UI aber zu Location zu migrieren?
- Diesen neuen Reiter könnte man dann "Borehole Info & Location" nennen
- Die Geometrie wäre dann ein separaten Reiter

**Comment by patrickackermann** [comment]
Ich habe das Umstellen der Einheit in ein Separates Issue verschoben: https://github.com/geoadmin/suite-bdms/issues/1102#issuecomment-2040378958

**Comment by gysimichael** [comment]
@patrickackermann es geht nun doch, weiss nicht was vorher das Problem war mit der Section. Nun sehe ich es aber und funktioniert.

Folgendes ist mir aufgefallen:

- scrollbar fehlt in Generell, könnte man aber zu Location migrieren
- bei EN bei water-based fehlt das "non-dispersed", bei den anderen Übersetzungen ist dies aber korrekt
- Bei den subtypes muss der Type nicht wiederholt werden und kann somit weggelassen werden.

Sonst gut geworden

**Comment by gysimichael** [comment]
@patrickackermann "drilling_end_date" / "spud_date"

Wäre es nicht sinnvoll, das Attribut in der common.json anzupassen als "drilling_starte_date"?

**Comment by patrickackermann** [comment]
@gysimichael Ich weiss nicht, im Code wird _Datum Bohrbeginn_ überall als _spud date_ bezeichnet. und in der englischen Übersetzung ist es auch das _Spud date_ im UI. Wenn "Spud date" ein anerkannter Fachbegriff für den Bohrstart ist hätte ich es eher gelassen.

**Comment by gysimichael** [comment]
@patrickackermann spud date ist nur der erste Ansatz der Bohrung. Da wir das nun pro Sektion machen, ist der Begriff falsch, daher auch die Frage wegen der Anpassung, um Verwirrung zu vermeiden

**Comment by gysimichael** [comment]
Englische Übersetzung ist schon korrigiert und wird hoffentlich bald gemerged

**Comment by patrickackermann** [comment]
Ich benenne das _spud date_ gleich überal um, auch in der DB

**Comment by gysimichael** [comment]
> Ich benenne das _spud date_ gleich überal um, auch in der DB

super, danke
