### ISSUE TITLE
borehole m:n Tabelle neu bezeichnen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#1110]
Um das Datenmodell besser lesen zu können sollte die Tabelle borehole_codelist mit borehole_ids_codelist ersetzt werden. So erkennt man, dass hier die IDs der Bohrungen erfasst wurde

**Comment by danjov** [comment]
Zuerst ist zu prüfen, ob die IDs weiterhin in der `codelist`-Tabelle geführt werden sollen → https://github.com/geoadmin/suite-bdms/issues/138#issuecomment-1362774348

**Comment by MiraGeowerkstatt** [comment]
> Zuerst ist zu prüfen, ob die IDs weiterhin in der `codelist`-Tabelle geführt werden sollen → [#138 (comment)](https://github.com/geoadmin/suite-bdms/issues/138#issuecomment-1362774348)

Die borehole_identifier in eine separate Tabelle auszulagern erfordert leider Änderungen tief im python api, daher werde ich in diesem Issue die Tabelle lediglich umbennen. 
 Nach oder zusammen mit [#1026](https://github.com/geoadmin/suite-bdms/issues/1026) kann die Änderung dann gemacht werden.

**Comment by MiraGeowerkstatt** [comment]
@gysimichael Ich werde die Tabelle zu  " borehole_identifiers_codelist" statt " borehole_ids_codelist" in Ordnung?
Der Grund ist, dass ich die Spalten der Tabelle nach neuer Konvention auch umgennen und es dort einen foreign key mit dem schönen Namen id_id gäbe ;-). Ich denke identifiers ist allgemein klarer.

**Comment by gysimichael** [comment]
macht absolut Sinn, danke für die Umsetzung.
