### ISSUE TITLE
Completion kopieren

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#1125]
Beim Kopieren einer Completion treten folgende Probleme auf:
- CasingElements werden nicht mitkopiert
- Wenn die Completion ein Casing enthält, welches wiederum von der Instrumentation und/oder Backfill referenziert wird, muss beim Kopieren die CasingId in der kopierten Instrumentation/Backfill zur CasingId des kopieren Casings aktualisiert werden (aktuell bleibt die CasingId des Original-Casings, was ein ungültiger Zustand ist).

**Comment by gysimichael** [comment]
wenn ich aktuell eine Bohrung kopiere, werden weder Ausbau noch Hydrogeologie mitkopiert. Könnte mir vorstellen, dass dies eine grössere Übung wird und nicht sicher, ob wir das zum jetztigen Zeitpunkt schon machen sollen

**Comment by gysimichael** [comment]
auch das funktionniert einwandfrei, danke!
