### ISSUE TITLE
Completion-Link mit Hash laden öffnet falsches Tab

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#1138]
Repro:
1. http://localhost:3000/editor/{boreholeId}/completion/{completionId}#instrumentation im Browser aufrufen

Erwartet:
Instrumentation-Tab ist aktiv

Fehler:
Casing-Tab ist aktiv

**Comment by MiraGeowerkstatt** [comment]
Nach  #1187 erneut angehen.

**Comment by gysimichael** [comment]
funktioniert bestens! Danke
