### ISSUE TITLE
Viewer-Ansicht Rückbauen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#1154]
Als erster Schritt der Zusammenführung vom **Viewer** und **Editor** soll der Viewer entfernt werden. 
Danach erfolgt der Ausbau und die Optimierung der Editor-Ansicht gemeinsam mit den UX-Experten.

- [x]  Editor zur Defaultsansicht machen und Viewer Ansicht "verstecken"
- [x]  Naming und Routes anpassen
- [x]  WMS Settings in Editormode verschieben
- [x]  Toten Code aus Client Löschen
- [x]  Toten Code aus Legacy Api Löschen
- [x]  C# Api Authorization kontrollieren
- [x]  e2e Tests für Viewer-Rolle im Editor Modus
- [x] Multiselect, bulkedit, copy, delete Funktionen im Borehole table für Viewer ausbauen

**Comment by MiraGeowerkstatt** [comment]
@RBordoni @gysimichael  Ihr werdet feststellen, dass auf der DEV Umgebung der Viewer Modus nicht mehr erreichbar ist. Ich bin an der Umsetzung dran, gemäss der Checkliste oben. Die Arbeit ist noch nicht abgeschlossen, d.h. Urls und Namen stimmen noch nicht überall (so gibt es beispielsweise noch die Route /editor und auch in den Settings gibt es noch die Rubrik "Editor"). 
Das gehe ich als nächstes an. Falls euch aber sonst etwas auffällt, gerne melden.

**Comment by gysimichael** [comment]
@MiraGeowerkstatt : der Link https://dev-boreholes.swissgeol.ch/30867 funktioniert, wenn man dann aber tiefer in die verschiedenen Reitern reinkommen will mit einem Link, geht es nicht: https://dev-boreholes.swissgeol.ch/30867/borehole

Ist das normal oder ein Bug?

**Comment by flenny** [comment]
@gysimichael Nein das sollte so nicht sein 😅. Ich habe den Bug soeben erfasst (#1187).
