### ISSUE TITLE
Beschreibungstext beim Reaktivieren eines Benutzers fehlt

### ISSUE THREAD

**Issue by flenny** [geoadmin/suite-bdms#117]
![image](https://user-images.githubusercontent.com/1365121/195357808-893acd55-c6e6-46a9-8f33-691922301ca3.png)

Translation Key `enablingUser` in den Translations (en,de,it.fr) ergänzen.
Vorschlag für Text: Soll der Benutzer '{username}' wieder aktiviert werden?

**Comment by RBordoni** [comment]
Wird nicht einfach die falsche Key-Bezeichnung verwendet? Es gibt eine `msgEnablingUser`, vielleicht ist diese die richtige.

**Comment by flenny** [comment]
Das ist genau so 👍🏼 Perfekt merci 🎉

**Comment by gysimichael** [comment]
sieht gut aus, danke für die Umsetzung
