### ISSUE TITLE
altes favicon beim Help

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#1175]
**Steps to reproduce**
1. Press the "New borehole" button
2. Click on "Help"

**Expected behavior**
New window opens with the correct favicon

**Current behavior**
New window opens with the old favicon

**Screenshots**

![Image](https://github.com/geoadmin/suite-bdms/assets/108096632/aefc2dc3-fca6-41e0-a665-793e40bf09b1)

**Comment by RBordoni** [comment]
Test Version: 2.0.677: Ok. Anmerkung: Ich musste die Seite im Browser explizit nochmals neu Laden, damit das neue Icon erscheint.

**Comment by gysimichael** [comment]
Hat auch bei mir funktioniert. Danke
