### ISSUE TITLE
Fehler bei der direkten Navigation zu URLs bestehend aus mehreren Unterordnern

### ISSUE THREAD

**Issue by flenny** [geoadmin/suite-bdms#1187]
**Steps to reproduce**
1. Go to [dev-boreholes.swissgeol.ch/setting/admin](https://dev-boreholes.swissgeol.ch/setting/admin)

**Expected behavior**
The web application redirects to the login page or signs-in automatically. The admin section in the settings menu shows up.

**Current behavior**
A white/blank page is shown.

**Additional information**
:white_check_mark:  https://dev-boreholes.swissgeol.ch/setting
:x:  https://dev-boreholes.swissgeol.ch/setting/
:x:  https://dev-boreholes.swissgeol.ch/setting/admin
:white_check_mark:  https://dev-boreholes.swissgeol.ch/30867
:x:  https://dev-boreholes.swissgeol.ch/30867/borehole

**Comment by RBordoni** [comment]
Test Version Version: 2.0.665: Verhalten immer noch gleich.

**Comment by MiraGeowerkstatt** [comment]
Einen Client Routingfehler habe ich in #1194 gefixt. Das Verhalten ist seitdem auf dem beim lokalen Entwickeln korrekt. Auf der Dev-Umgebung (etc) besteht das Problem aber weiterhin. Das Normalisieren der redirect URi in #1200 hat das Problem auch nicht behoben.

**Comment by flenny** [comment]
Bei Laden der Applikation auf DEV bei Adressen mit zusätzlichen Directories werden die Assets an falscher Stelle gesucht. Bspw. `https://dev-boreholes.swissgeol.ch/setting/assets/index-DXNvtnaG.js`
![image](https://github.com/geoadmin/suite-bdms/assets/1365121/596dcdc4-c5ce-4071-9271-2076c24800c6)

**Comment by gysimichael** [comment]
geht nun einwandfrei, danke!
