### ISSUE TITLE
Entwickler Debug Funktionalität abstellen

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#1195]
Debug Eintrag aus dem Menu entfernen.

![Image](https://github.com/geoadmin/suite-bdms/assets/49144408/9ab7a6c6-22c4-4db9-83a6-c373ca271e6c)

Entweder Funktionalität aus dem Code entfernen, oder mit "deprecated" kennzeichnen und bei neuen Entwicklungen nicht mehr nutzen.

**Comment by gysimichael** [comment]
Danke
