### ISSUE TITLE
Anzeigen vereinheitlichen für Stratigraphy, Instrument, Casing, Backfill

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#121]
Wenn das Editieren noch nicht gestartet ist, soll die Anzeige überall entsprechend gleich sein: "No stratigraphy available" "No casing available" "No instrumentation available" "No backfill available" Entsprechende Attribute sind zu erstellen, falls noch nicht vorhanden.
Sobald das Editieren gestartet wurde sollen die bisherigen texte angezeigt werden.

**Comment by gysimichael** [comment]
sieht gut aus, danke für die Umsetzung
