### ISSUE TITLE
Neuer Confirmation Dialog für Delete Borehole  in der Detailansicht

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#1320]
![Image](https://github.com/swisstopo/swissgeol-boreholes-suite/assets/49144408/f8397d35-e58a-4d1e-9f14-8d4f9d83f74c)

Siehe: https://www.figma.com/design/cEiOoOazAQZqpRY92ZhBeO/SwissGeol?node-id=7390-40928&t=3tvCATppEjQKRcHP-0

**Comment by gysimichael** [comment]
danke
