### ISSUE TITLE
"Show all" Knopf bei Instrumentation einblenden, auch wenn kein Casing existiert

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#139]
**Repro Steps:**
1. Bohrung ohne Casing und Instrumentation
2. Start editing
3. Instrumentation

**Erwartet:**
Im oberen Bereich ist es nicht weiss. Der "Show all" Knopf ist bei Instrumentation ausgegraut eingeblendet, auch wenn kein Casing existiert

![Image](https://user-images.githubusercontent.com/31883445/197775728-e5b8670e-4de5-41b4-8517-1051a3f571e0.png)

**Comment by gysimichael** [comment]
![Image](https://user-images.githubusercontent.com/108096632/200380638-14e0ac3b-d030-4ee2-b3a0-4304ccfdb001.png)

Zurzeit kleben die Einträge noch ein bisschen zu nahe beim Button wenn man stopp Editing klickt. Könnte man das noch anpassen?

**Comment by gysimichael** [comment]
Perfekt! Danke.
