### ISSUE TITLE
Eingabe im Frontend einfügen unter Instrumente

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#14]
Im Editor Modus unter Instrumente sollte nach "casingName" noch das Attribut "casingID" inklusive Eingabemöglichkeit inkludiert werden. Dies ist nötig, damit ein Instrument einem Casingrohr explizit zugeordnet werden kann.

**Comment by gysimichael** [comment]
Wenn Name of completion ausgewählt wird, und die Auswahl des Casing ID freigegeben wird2, löscht es die Einträge unter den vorhergehenden Feldern



![Image](https://user-images.githubusercontent.com/108096632/200799466-f7cdd46f-f63e-4b8d-b23f-4eee5e0e202c.png)

Wenn man keine Name of Completion auswählt, funktioniert alles, respektive speichert die Daten (siehe Bohrung Test_2022.11.09)

**Comment by MiraGeowerkstatt** [comment]
Der Bug tritt jeweils nur beim zuletzt hinzugefügten Instrument auf.

**Comment by gysimichael** [comment]
funktioniert bei mir nicht, immer wenn ich casing auswähle, löscht es alle Einträge. Teilweise endet es auch in einem Whiteout

**Comment by MiraGeowerkstatt** [comment]
Wegen zu wenig Speicherplatz wurde der Client auf https://dev.boreholes.swissgeol.ch/ nicht korrekt aktualisiert und ich fürchte du hast auf einer alten Version getestet. Die aktuellste Version ist jetzt drauf und wir werden uns drum kümmern, das in Zukunft regelmässig "aufgeräumt" wird und das Speicherproblem nicht mehr auftreten sollte.  Ich würde dich bitte noch einmal zu testen.

**Comment by RBordoni** [comment]
Verbleibender Fehler:
Repro Steps:
1. Start Edit
2. Bei einem Datensatz mit Completion und Instrumentation zwei Instruments einfügen
3. _Name of completion_ und _Casing ID_ bei allen auswählen
4. Beim letzten _Name of completion_ auf _No Casing_ setzen

Erwartet:
Es kann keine _Casing ID_ eingegeben werden

Beobachtet:
Es kann eine _Casing ID_ eingegeben werden

**Comment by gysimichael** [comment]
Das funktionier nun, super! Vielen Dank
