### ISSUE TITLE
Bezeichnungen der Gruppen der Geolcodes anpassen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#140]
Kann auch später umgesetzt werden.

Die Bezeichnungen der Gruppen der Geolcodes sind gemäss untenstehender Tabelle anzupassen.
Die GeoWerkstatt überlegt sich, wie die neuen Begriffe in der Applikation/DB verankert werden.
Die anderen Anpassungen (IDs rausnehmen und Löschen der nicht verwendeten) werden in #42 abgehandelt.

<html>
<body>

ld | new | comments
-- | -- | --
borehole_from |   | Deleted
casi200 | casing_type |  Renamed in #1025
casi201 | casing_material |  Renamed in #1025
custom.cuttings | borehole_cuttings_core |  See [#1026](https://github.com/geoadmin/suite-bdms/issues/1026)
extended.purpose | drilling_purpose |  See [#1026](https://github.com/geoadmin/suite-bdms/issues/1026)
extended.status | borehole_status |  See [#1026](https://github.com/geoadmin/suite-bdms/issues/1026)
ebor106 | yes_no |  Deleted
extended.drilling_method | drilling_method |  See [#1026](https://github.com/geoadmin/suite-bdms/issues/1026)
custom.qt_top_bedrock | depth_precision |  See [#1026](https://github.com/geoadmin/suite-bdms/issues/1026)
custom.qt_depth |   | Deleted
custom.qt_bore_inc_dir | inclination_precision |  See [#1026](https://github.com/geoadmin/suite-bdms/issues/1026)
fill100 | backfill_type |  Renamed in #1025
fill200 | backfill_material |  Renamed in #1025
gradation | gradation | Renamed in #1025
kind | borehole_type |  Renamed in #1030
srs | spatial_reference_system |   Renamed in #1030
hrs | height_reference_system |  Renamed in #1030
restriction | restriction | No change
qt_location | location_precision |  Renamed in #1025
qt_elevation | elevation_precision |  Renamed in #1025
ibor117 | reference_elevation_type |  Renamed in #1025
cantons | cantons |  No change
country | countries  |  Renamed in #1030
inst100 | instrument_type |  Renamed in #1025
inst101 | instrument_status |  Renamed in #1025
layer_kind |   | See #254
mcla101 | uscs_type |  Renamed in #1025
mcla104 | uscs_determination |  Renamed in #1025
mcla107 | debris |  Renamed in #1025
mlpr101 | plasticity |  Renamed in #1025
mlpr102 | compactness |  Renamed in #1025
mlpr103 | consistency |  Renamed in #1025
mlpr105 | humidity |  Renamed in #1025
mlpr106 | alteration |  Renamed in #1025
mlpr108 | organic_components |  Renamed in #1025
mlpr109 | grain_size |  Renamed in #1025
mlpr110 | grain_shape |  Renamed in #1025
qt_description | description_quality |  Renamed in #1025
mlpr112 | colour |  Renamed in #1025
mlpr115 | grain_angularity |  Renamed in #1025
mlpr116 | cohesion |  Renamed in #1025
custom.chronostratigraphy_top_bedrock | chronostratigraphy |  See [#1026](https://github.com/geoadmin/suite-bdms/issues/1026)
custom.lithology_top_bedrock |  lithology |  See [#1026](https://github.com/geoadmin/suite-bdms/issues/1026)
custom.lithostratigraphy_top_bedrock |  lithostratigraphy |  See [#1026](https://github.com/geoadmin/suite-bdms/issues/1026)
borehole_identifier | borehole_identifier |  No change

</body>
</html>

Sprint 0: Analyse und split in einzelne Issues

**Comment by RBordoni** [comment]
custom.qt_depth ist nicht mehr in use → löschen

**Comment by danjov** [comment]
Für die Umbenennung soll der Aufwand zuerst geschätzt werden.

**Comment by MiraGeowerkstatt** [comment]
In einem ersten Schritt werden custom.qt_depth, ebor106 und borehole_form gelöscht.

**Comment by gysimichael** [comment]
super danke

**Comment by RBordoni** [comment]
Sprint 0: Analyse und split in einzelne Issues

**Comment by MiraGeowerkstatt** [comment]
Wir haben die Situation analysiert und entschieden eine Teilumsetzung gemäss Tabelle oben sofort umzusetzen. Ein Teil muss nochmals zurückgestellt werden, da es einen sehr grossen Umbau von Python API aufs C# Api bedeuten würde, welcher ggf. separat geschätzt und priorisiert werden müsste. Habe die Details und bisherige Erkenntnisse in #1026 festgehalten.

**Comment by gysimichael** [comment]
sehr gut, vielen Dank, das macht es viel Einfacher etwas zu finden
