### ISSUE TITLE
Neuer Tab unter Instruments erstellen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#15]
Wenn beim Dropdown "Name of Completion" "no casing" gewählt wird, sollte ein Tab mit mit dem Geolcode  "22104001" benannt erscheinen. Falls ein Ausbauprofil vorliegt, wir diese Tab zurzeit automatisch erstellt. Für "no casing" gibt es aber diese Möglichkeit nicht.

**Comment by MiraGeowerkstatt** [comment]
Statt dem Geolcode "22104001" haben wir die bereits vorhandene UI Übersetzung "no_casing" für den Namen des Tabs gewählt. 
Bisher ist es so, dass die Werte die im Dropdown "Name of Completion" zur Auswahl stehen, jeweils dem  Namen des Tabs entsprechen. 
Mit dem Namen "no_casing" bleiben wir so konsistent.

**Comment by gysimichael** [comment]
gute Lösung! Finde ich gut so und funktioniert. Danke
