### ISSUE TITLE
Änderung von Layer properties auf neue API Version umstellen.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#151]
Das Updaten von Layers ist über das neue C# Api möglich.  Es wird aber noch nicht konsequent in der Applikation verwendet.

In dieser[ Komponente](https://github.com/geoadmin/suite-bdms/blob/main/src/client/src/commons/form/profile/components/profileAttributes/components/profileAttributeList/profileAttributeList.js) wird derzeit noch das alte Api verwendet.

**Comment by RBordoni** [comment]
Testresultat: Ein Datum setzen beim Casing geht nicht

**Repro Steps:**
1. Completion > Casing > ein neues Casing erfassen
2. Completion start date mit Date Picker erfassen

**Beobachtet:**
![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/972edaf3-b53e-4ffa-81f4-c017f6d65e40)
