### ISSUE TITLE
Falsche Koordinaten bei neuem Borehole

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#1547]
Reproduktion:
1. Detailansicht von Borehole mit abgefüllten Koordinaten öffnen
2. Zurück in die Übersichtsseite navigieren
3. Neues Borehole erstellen

Erwartet:
Die Koordinaten sind leer

Fehler:
Die Koordinaten enthalten die Werte des Boreholes aus Schritt 1. 

Hinweis:
Das Problem tritt nur auf, wenn die Werte sonst NULL wären. Wenn das Borehole bereits Koordinaten hat, funktioniert alles wie gewünscht.

**Comment by gysimichael** [comment]
funktioniert, danke!
