### ISSUE TITLE
Instrument Tab upgrade

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#16]
Wenn kein Instrument erfasst ist, müsste der folgende Text eingeblendet werden: 
"Für die Erfassung eines Instruments bitte das Plus-Symbol oben rechts klicken"
"Pour l'enregistrement d'un instrument veuillez cliquer sur le symbole dans le coin supérieur gauche"
"Per la registrazione di uno strumento cliccare il pulsante con il simbolo in alto a sinistra"
"For the recording of a instrument please click the plus symbol at the top left"

Dazu muss ein neues technische Attribut erstellt werden, für casing heisst dies msgCasingEmpty. Wenn ich in der Liste sehe, gibt es schon ein Attribut dafür "msgInstrumentsEmpty", das mit dem oben aufgelisteten Übersetzungen ersetzt werden soll. Zurzeit ist das Attribut "nothingToShow" erfasst und kann gelöscht werden

Wenn kein Casing erfasst ist, kann kein Instrument erfasst werden. Das sollte aber möglich sein auch ohne Casing Profil. Eventuell müsste dies dann mit suite-bdms#15 case verbunden werden mit dem neuen tab für "no casing"

**Comment by RBordoni** [comment]
Richtig ist wohl im deutschen Satz "... oben links klicken", nicht oben rechts.

**Comment by gysimichael** [comment]
genau, oben links wäre richtig

**Comment by gysimichael** [comment]
sieht gut aus, danke für die Umsetzung

**Comment by gysimichael** [comment]
gibt es einen Grund, wieso der Plus-Knopf nicht ganz oben platziert wurde, wie das bei Casing und Backfill der Fall ist?
