### ISSUE TITLE
Backfill Tab upgrade

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#17]
Wenn kein Backfill erfasst ist, müsste der folgende Text eingeblendet werden:
"Für die Erfassung einer Hinterfüllung bitte das Plus-Symbol oben rechts klicken"
"Pour l'enregistrement d'une remplissage veuillez cliquer sur le symbole dans le coin supérieur gauche"
"Per la registrazione di uno riempimento cliccare il pulsante con il simbolo in alto a sinistra"
"For the recording of a backfill please click the plus symbol at the top left"

Zurzeit wird "msgStratigraphyEmty" angezeigt, was falsch ist. Am besten neues Attribut erstellen mit "msgBackfillEmty"

**Comment by RBordoni** [comment]
Richtig ist wohl im deutschen Satz "... oben links klicken", nicht oben rechts.

**Comment by gysimichael** [comment]
genau, oben links ist richtig

**Comment by RBordoni** [comment]
Ich würde vorschlagen das gleiche wie bei Instrumentation, wenn noch nichts erfasst ist:


![Image](https://user-images.githubusercontent.com/31883445/195329877-be4c56ae-143b-4e12-816f-990f05bf30c0.png)

**Comment by gysimichael** [comment]
sieht gut aus, danke für die Umsetzung
