### ISSUE TITLE
Datenmigration: Migration der Identifier bei den Bohrungen

### ISSUE THREAD

**Issue by flenny** [geoadmin/suite-bdms#170]
Bohrungen die aktuell _ID Canton_ (100000005) und/oder _ID GeoQuat_ (100000006) als Identifier zugewiesen haben, sollen neu auf _ID InfoGeol_ (100000003) resp. _ID Original_ (100000004) umgebogen werden. Die Liste der _borehole_identifier_ und die technischen Ids in der Tabelle _bdms.codelist_ bleiben in der jetztigen From bestehen.

Migration der Daten in der Verknüpfungstabelle bdms.borehole_codelist:
- 100000005 -> 100000003
- 100000006 -> 100000004

![image](https://user-images.githubusercontent.com/1365121/201347700-9432ab99-8f62-4d4d-a90c-5a3fe36d78a6.png)

**Comment by gysimichael** [comment]
gibt es einen Grund wieso 100000001 und 100000002 fehlen oder würde sich auch gleich lohnen diese Lücke zu schliessen, indem an aufrückt?

**Comment by danjov** [comment]
@gysimichael Vermutlich waren für 100000001 und 100000002 einmal Identifier eingetragen, die aber mittlerweile gelöscht wurden. Wir schlagen vor, die Lücke nicht zu schliessen. Da einmal vergebene Identifier, wenn auch mittlerweile gelöscht, nicht nochmals vergeben werden sollten.
Zudem tut uns die Lücke rein technisch gesehen nicht weh und das Aufrücken der Identifier würde vermutlich auch einigen Aufwand bedeuten, da die aktuelle Applikation sehr viel Annahmen bezüglich der Identifier trifft.
Geht das für dich in Ordnung?

**Comment by gysimichael** [comment]
passt für mich!

**Comment by gysimichael** [comment]
auf dev. sieht das gut aus. denke aber man muss das dann auf Prod nochmals machen, wenn die GeODin Datenbank da ist oder wie sieht das aus?

**Comment by gysimichael** [comment]
Könnte man nun auf test.boreholes.swissgeol.ch dies auch noch machen mit der Fugro Datenbank? Die scheint nu ja mehrheitlich in Ordnung zu sein und wird nicht mehr neu von Fugro erstellt

**Comment by gysimichael** [comment]
ich denke, mit der Aufschaltung auf Prod kann man die IDs nun auf test und Prod für die Workgroup swisstopo_Hiwi_Datman anpassen. Bei der Workgroup GeODin ist nun aber alles richtig und muss nichts angepasst werden

**Comment by danjov** [comment]
Das sollte mit dem nächsten Release auf Prod automatisch geschehen. @flenny korrigiere mich, falls ich etwas falsch verstanden habe.

**Comment by gysimichael** [comment]
ist das nicht ein one-off auf der neuen DB und hätte sich dann erledigt? Zurzeit auf Prod für swisstopo_Hiwi_Datman das noch falsch.
Dies Situation ist glaube ich entstanden, weil wohl die Identifier zu einem Zeitpunkt auf Test Prod und Dev nicht gleich waren...

**Comment by danjov** [comment]
Genau, das stimmt. Die Datenmigration muss jedoch angepasst werden, damit nur die Daten für _swisstopo_Hiwi_Datman_ angepasst werden und nicht alle.

**Comment by danjov** [comment]
Die IDs der workgroup _swisstopo_Hiwi_Datman_ wurden am 08.12.2022 auf Prod migriert:
```sql
UPDATE bdms.borehole_codelist bc
SET id_cli_fk = 100000003
FROM bdms.borehole
WHERE bc.id_bho_fk = id_bho AND bc.id_cli_fk = 100000005 AND id_wgp_fk IN (SELECT id_wgp FROM bdms.workgroups WHERE name_wgp = 'swisstopo-Hiwi-Datman');

UPDATE bdms.borehole_codelist bc
SET id_cli_fk = 100000004
FROM bdms.borehole
WHERE bc.id_bho_fk = id_bho AND bc.id_cli_fk = 100000006 AND id_wgp_fk IN (SELECT id_wgp FROM bdms.workgroups WHERE name_wgp = 'swisstopo-Hiwi-Datman');

```

**Comment by gysimichael** [comment]
Danke!
