### ISSUE TITLE
Punkt auf Karte kann verschoben werden, auch denn der Editiermodus noch nicht aktiv ist.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#177]
Repo: Als Editor ein Bohrloch bearbeiten. Editiermodus noch nicht einschalten. Punkt auf der Karte verschieben auf "Apply" klicken.

Erwartet: Punkt lässt sich nicht verschieben, Benutzer:in wird gewarnt, das der Editiermodus nicht aktiv ist.

Beobachtet: Punkt lässt sich verschieben, erst beim Klick auf "Apply" erscheint die Warnung. Die Koordinaten werden zwar nicht in die Textfelder übernommen, der Punkt bleibt aber an der Stelle an die er geschoben wurde.

![Image](https://user-images.githubusercontent.com/49144408/203333259-1b7ae0f2-11a0-418f-b03b-cbb45276ff0f.gif)

**Comment by RBordoni** [comment]
Es ist zudem noch gefährlich. Wenn danach "Start editing" geklickt wird, gelangt man in den Editiermodus und der Wert wird direkt angepasst. D.h. man verliert den ursprünglichen Wert!

**Comment by gysimichael** [comment]
Das scheint zu funktionieren, jedoch wenn ich dann start editing klicke, kann man einen zweiten Punkt setzten und wenn man dann den Reiter wechselt und zurück kehrt, gibt es keinen Punkt mehr...



![Image](https://user-images.githubusercontent.com/108096632/207936641-60d2f856-1e98-4430-929e-bf71417c9e8a.png)



![Image](https://user-images.githubusercontent.com/108096632/207936693-b9b6211e-87ec-4c3e-8bef-808426580bb0.png)

**Comment by MiraGeowerkstatt** [comment]
@RBordoni  Es gibt hier verschiedenste Pfade die zu unterschiedlichem Verhalten führen können. 
- Geometrie auf der Karte wählen, aber nicht apply drücken, dann "stop Edit" . 
- Geometrie ändern, nicht apply drücken und ohne "stop Edit" die Seite verlassen und zurückkehren. 
- Geometrie wählen, apply drücken dann Seite mit oder ohne "stop Edit" verlassen und zurückkehren.
- Alle analogen Fälle wenn eine vorhandene Geometrie modifiziert wird. 

Also gern noch mal alle Möglichen Fälle durchtesten. ich hoffe ich habe alles erwischt!

**Comment by RBordoni** [comment]
@MiraGeowerkstatt Es macht einen Unterschied, wie ich die Seite ohne Stop editing verlasse und wieder zurückkehre:

- Mit  "Done" funktioniert alles einwandfrei → Punkt ist danach wieder am richtigen Ort
- Mit Wechsel zu Reiter "Borhole" und zurück zu "Location" → Kein Punkt mehr sichtbar und Zoomstufe verändert. Erst wenn ich dann mit Done rausgehe und wieder zurückkehre stimmt es wieder

**Comment by MiraGeowerkstatt** [comment]
Noch ein weiterer Spezialfall :( Ich schaus an.

**Comment by RBordoni** [comment]
Noch ein Spezialfall - Repro Steps:

1. Beliebige Bohrung öffnen
2. Start editing
3. In der Einzelkarte Punkt verschieben
4. Stop editing

Beobachtet:
Gleich nach dem Stop editing ist der Punkt verschiebbar. Wechselt man hingegen mit Done zur Liste und geht erneut in die Bohrung, ist der Punkt nicht mehr verschiebbar.

**Comment by MiraGeowerkstatt** [comment]
Wird erst nach Abschluss von #217  angegangen.

**Comment by gysimichael** [comment]
Scheint behoben zu sein, Danke!
