### ISSUE TITLE
Dringend: GeolCodes erstellen um GeODin DB zu integrieren

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#179]
Bitte folgende GeolCodes Einträge in der Liste mcal101 nachführen:

30000310	mcla101	S-SC	schwach toniger Sand	sable peu argileux	sabbia leggermente argillosa	slightly clayey sand
30000311	mcla101	S-SM	schwach siltiger Sand	sable peu limoneux	sabbia leggermente limosa	slightly silty sand
30000308	mcla101	G-GC	schwach toniger Kies	gravier peu argileux	ghiaia leggermente argillosa	slightly clayey gravel
30000309	mcla101	G-GM	schwach siltiger Kies	gravier peu limoneux	ghiaia leggermente limosa	slightly silty gravel

Folgendes wäre die preferierte Reihenfolge im Dropdown:

1	23101001	mcla101	CH	fetter Ton	argile grasse	argilla grassa	fat clay
2	23101002	mcla101	CM	magerer Ton	argile maigre	argilla magra	lean clay
3	23101003	mcla101	CL	siltiger Ton	argile limoneuse	argilla limosa	silty clay
4	23101004	mcla101	CL-ML	toniger Silt	limon argileux	limo argilloso	clayey silt
5	23101005	mcla101	G	Kies	gravier	ghiaia	gravel
6	30000308	mcla101	G-GC	schwach toniger Kies	gravier peu argileux	ghiaia leggermente argillosa	slightly clayey gravel
7	30000309	mcla101	G-GM	schwach siltiger Kies	gravier peu limoneux	ghiaia leggermente limosa	slightly silty gravel
8	23101006	mcla101	GC	toniger Kies	gravier argileux	ghiaia argillosa	clayey gravel
9	23101007	mcla101	GC-GM	siltiger bis toniger Kies	gravier limono-argileux	ghiaia limoso argillosa	silty, clayey gravel
10	23101008	mcla101	GM	siltiger Kies	gravier limoneux	ghiaia limosa	silty gravel
11	23101009	mcla101	GP	schlecht abgestufter Kies	gravier mal gradué	ghiaia mal classata	poorly graded gravel
12	23101010	mcla101	GP-GC	schlecht abgestufter Kies mit Ton	gravier mal gradué avec argile	ghiaia mal classata con argilla	poorly graded gravel with clay
13	23101011	mcla101	GP-GM	schlecht abgestufter Kies mit Silt	gravier mal gradué avec limon	ghiaia mal classata con limo	poorly graded gravel with silt
14	23101012	mcla101	GW	gut abgestufter Kies	gravier bien gradué	ghiaia ben classata	well-graded gravel
15	23101013	mcla101	GW-GC	gut abgestufter Kies mit Ton	gravier bien gradué avec argile	ghiaia ben con argilla	well-graded gravel with clay
16	23101014	mcla101	GW-GM	gut abgestufter Kies mit Silt	gravier bien gradué avec limon	ghiaia ben con limo	well-graded gravel with silt
17	23101015	mcla101	ML	Silt	limon	limo	silt
18	23101016	mcla101	OH	organischer Silt	limon organique	limo organico	organic silt
19	23101017	mcla101	OL	organischer Ton	argile organique	argilla organica	organic clay
20	23101035	mcla101	MH	elasitscher Silt	limon élastique	limo elastico	elastic silt
21	23101018	mcla101	Pt	Torf	tourbe	torba	peat
22	23101019	mcla101	S	Sand	sable	sabbia	sand
23	30000310	mcla101	S-SC	schwach toniger Sand	sable peu argileux	sabbia leggermente argillosa	slightly clayey sand
24	30000311	mcla101	S-SM	schwach siltiger Sand	sable peu limoneux	sabbia leggermente limosa	slightly silty sand
25	23101020	mcla101	SC	toniger Sand	sable argileux	sabbia argillosa	clayey sand
26	23101021	mcla101	SC-SM	siltiger bis toniger Sand	sable limono-argileux	sabbia limo argillosa	silty, calyey sand
27	23101022	mcla101	SM	siltiger Sand	sable limoneux	sabbia limosa	silty sand
28	23101023	mcla101	SP	schlecht abgestufter Sand	sable mal gradué	sabbia mal classata	poorly graded sand
29	23101024	mcla101	SP-SC	schlecht abgestufter Sand mit Ton	sable mal gradué avec argile	sabbia mal classata con argilla	poorly graded sand with clay
30	23101025	mcla101	SP-SM	schlecht abgestufter Sand mit Silt	sable mal gradué avec limon	sabbia mal classata con limo	poorly graded sand with silt
31	23101026	mcla101	Bl	Block	bloc	blocco	boulder
32	23101027	mcla101	St	Stein	pierre	pietra	cobbles
33	23101028	mcla101	St-Bl	Steine und Blöcke	pierre et bloc	pietre e blocchi	cobbles and boulders
34	23101029	mcla101	SW	gut abgestufter Sand	sable bien gradué	sabbia ben classata	well-graded sand
35	23101030	mcla101	SW-SC	gut abgestufter Sand mit Ton	sable bien gradué avec argile	sabbia ben classata con argilla	well-graded sand with clay
36	23101031	mcla101	SW-SM	gut abgestufter Sand mit Silt	sable bien gradué avec limon	sabbia ben classata con limo	well-graded sand with silt
37	23101032	mcla101	kunst	künstlich Auffüllung	remplissage artificiel	riempimento artificiale	artificial landfill
38	23101033	mcla101	FELS	Fels	rocher	roccia	bed rock
39	23101034	mcla101	kA	keine Angaben	sans indication	senza indicazioni	no specified

**Comment by danjov** [comment]
Die GeolCodes wurden am 25.11.2022 14:30 Uhr auf der Dev-, Test- und Prod-Umgebung mit nachfolgendem Skript ergänzt und neu sortiert:
```sql
-- Update ordering of existing codes to make room for the new cdoes
-- Free up order 6 and 7
UPDATE bdms.codelist
SET order_cli = order_cli + 2
WHERE schema_cli = 'mcla101' AND order_cli > 5;

-- Free up order 23 and 24
UPDATE bdms.codelist
SET order_cli = order_cli + 2
WHERE schema_cli = 'mcla101' AND order_cli > 22;

-- Insert new geolcodes
INSERT INTO bdms.codelist (id_cli, geolcode, schema_cli, code_cli, text_cli_en, text_cli_de, text_cli_fr, text_cli_it, order_cli, default_cli, description_cli_en, description_cli_de, description_cli_fr, description_cli_it) VALUES
	(30000310, 30000310, 'mcla101', 'S-SC', 'slightly clayey sand', 'schwach toniger Sand', 'sable peu argileux', 'sabbia leggermente argillosa', 23, false, '', '', '', ''), 
	(30000311, 30000311, 'mcla101', 'S-SM', 'slightly silty sand', 'schwach siltiger Sand', 'sable peu limoneux', 'sabbia leggermente limosa', 24, false, '', '', '', ''), 
	(30000308, 30000308, 'mcla101', 'G-GC', 'slightly clayey gravel', 'schwach toniger Kies', 'gravier peu argileux', 'ghiaia leggermente argillosa', 6, false, '', '', '', ''), 
	(30000309, 30000309, 'mcla101', 'G-GM', 'slightly silty gravel', 'schwach siltiger Kies', 'gravier peu limoneux', 'ghiaia leggermente limosa', 7, false, '', '', '', '');

-- Reorder codes:
-- Move 'MH' to order 20
UPDATE bdms.codelist
SET order_cli = order_cli + 1
WHERE schema_cli = 'mcla101' AND order_cli > 19;

UPDATE bdms.codelist
SET order_cli = 20
WHERE schema_cli = 'mcla101' AND code_cli = 'MH';

-- Move 'SC' to order 25
UPDATE bdms.codelist
SET order_cli = order_cli - 1
WHERE schema_cli = 'mcla101' AND order_cli > 22;

UPDATE bdms.codelist
SET order_cli = order_cli + 1
WHERE schema_cli = 'mcla101' AND order_cli > 24;

UPDATE bdms.codelist
SET order_cli = 25
WHERE schema_cli = 'mcla101' AND code_cli = 'SC';
```

**Comment by gysimichael** [comment]
super, bitte einfach auch noch auf Test umsetzten

**Comment by danjov** [comment]
Die Bereinigung wurde mit #164 durchgeführt.

**Comment by gysimichael** [comment]
super, sieht gut aus.
