### ISSUE TITLE
technische Attribute Übersetzung ändern

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#18]
msgStartigraphyEmpty
Für die Erfassung eines Stratigraphieprofils bitte das Plus-Symbol oben rechts klicken
Pour l'enregistrement d'un profil stratigraphie veuillez cliquer sur le symbole dans le coin supérieur gauche
Per la registrazione di un profilo stratigrafia cliccare il pulsante con il simbolo in alto a sinistra
For the recording of a stratigraphic profile please click the plus symbol at the top left

msgCasingEmpty
Für die Erfassung eines Verrohrungsprofils bitte das Plus-Symbol oben rechts klicken
Pour l'enregistrement d'un profil tubage veuillez cliquer sur le symbole dans le coin supérieur gauche
Per la registrazione di un profilo tubatura cliccare il pulsante con il simbolo in alto a sinistra
For the recording of a casing profile please click the plus symbol at the top left

total_depth_tvd
Bohrendteufe TVD [m]
Profondeur totale TVD [m]
Profondità totale TVD [m]
Total depth TVD [m]

**Comment by RBordoni** [comment]
Auch hier gilt beim deutschen Text "... oben links ..." statt "... oben rechts ..."

**Comment by RBordoni** [comment]
Test RB: Lösung beisst sich mit Überlegungen zu #121. Text sollte nur in der gestarteten Editor-Session sichtbar sein, da erst dann etwas oben links sichtbar ist.

**Comment by gysimichael** [comment]
scheint alles bestens zu klappen, Danke!
