### ISSUE TITLE
Blank screen bei zurückkehren zur Filterung

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#185]
**Reprosteps:** 

Zu  https://dev.boreholes.swissgeol.ch/editor navigieren und einloggen.
Unter Suchfiltern  Location -> "Identifier" beliebige ID auswählen. Eine Bohrung aus der gefilterten Liste anklicken um zur Editiermaske zu gelangen.
Von der Editiermaske wieder zum Ausgangspunkt zurückkehren (Done).  Erneut Location Filter wählen und bei "Identifier" auf reset klicken.

**Erwartet:** Filterung wird zurückgesetzt.

**Beobachtet:** Blank screen. Neuladen und Einloggen ist notwendig.

**Comment by MiraGeowerkstatt** [comment]
Möglicherweise besteht eine Verbindung zu #169  da es sich ebenfalls um Einträge handelt die nicht als Geometrien auf der Karte dargestellt werden.

**Comment by MiraGeowerkstatt** [comment]
Ist mit #169 erledigt.

**Comment by gysimichael** [comment]
funktioniert! Danke!
