### ISSUE TITLE
Memory nach Return Button

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#188]
Wenn man eine Bohrung sucht und gefunden hat, dies Anschaut und dann auf zurück klickt, setzt es alles wieder in den Startmodus zurück und erinnert sich nicht, wo man war und wie man sortiert hat. Wäre toll wenn diese Einstellungen gespeichert und bei einem Retourn wieder sichtbar wären

**Comment by RBordoni** [comment]
@MiraGeowerkstatt Im vorherigen Release verschwand alles und es wurde sogar vom Editor- auf den Viewer-Modus zurückgeschaltet. Dies scheint durch die anderen Fixes behoben zu sein. Es verbleibt nur die Sortierung & Pagination der Tabelle. 
(Zudem ist der letzte Filter nicht mehr aufgeklappt. Falls dies schwierig zu beheben ist, schlage ich vor, es mal so zu belassen.)

**Comment by RBordoni** [comment]
Besprechung 21.12.2022: Umsetzen, so dass Sortierung & Pagination der Tabelle beibehalten wird.

**Comment by gysimichael** [comment]
@danjov hier wäre auch gut, wenn man das mit der Karte auch gleich einbauen könnte, das die nicht auf die ganze Schweiz zurückspringt, sondern im zoom Modus, wo man war, bleibt. Dies für den Viewer und Editor Modus.

**Comment by RBordoni** [comment]
@danjov Hier meine Testresultate. Du kannst es ergänzen, danach tragieren wir und machen bei Bedarf Einzelissues.

**Verhalten Bohrung aus Liste anklicken → Go back to List**
Viewer und Editor:
- [ ] Kartenausschnitt ist wieder auf Full Extent, resp. maximaler Extent der Filterresultate. 
- [ ] Filter wird zugeklappt

Nur Editor:
- [ ] Sortierung der Liste ist nicht mehr richtig. (Bei Sortierung nach Creation date schon!?)
- [ ] Pagination: In Liste wird wieder Seite 1 dargestellt

**Anderes**
Viewer und Editor
- [ ] Karte reagiert bei Serch Filters immer wie "center to selected", "center to selected" auch wenn ausgeschaltet. Oder was ist mit "selected" gemeint, Filter oder echte Selektion? 

Viewer: 
- [ ] Reset und Refresh Löscht Selektion nicht (im Editor schon). Es hat dafür oben die Funktion "reset selection". Wäre gut, wenn es überall gleich funktioniert

**Comment by RBordoni** [comment]
@danjov Ideal wäre, wenn der letzte Zustand beibehalten würde. Da dies aber bisher nicht implementiert war und dieser Punkt eher ein "minor Issue" ist, würde ich gar nichts machen. Es ist meiner Meinung nach halb so schlimm, wenn die Filter zuklappen.

**Comment by gysimichael** [comment]
Im Viewer Mode wenn man auf die Seitenauswahl unten klickt, Beispielsweise 3:

Erwartetes Verhalten:
Beim anschauen einer Bohrung und Done klicken komme ich wieder auf Seite 3

Verhalten:
Beim anschauen einer Bohrung und Done klicken komme ich auf Seite 1

**Comment by gysimichael** [comment]
Beim Editor: Die Seite bleiben, jedoch die Scrollposition wird nicht erhalten, wäre das möglich?

Desweitern, wieso rechnet er zuerst ein Refresh und kommt erst dann zum vorhergehenden Zustand zurück? Könnte man diesen Refresh Schritt nicht weglassen, um reaktiver zu sein?

Auch wenn man Reinzoomt, das es keine Culuster mehr gibt und dann zurück kommt, ist man immer im Cluster Modus. Lässt sich das beheben?

**Comment by danjov** [comment]
Bis auf das Thema mit dem Refresh wurden alle oben genannten Punkte erledigt. Der zusätzliche Refresh soll in separat behandelt werden.

**Comment by gysimichael** [comment]
Im Viewer Modus, wenn man in der Karte Reinzoomt, dann auf Seite 73 klickt, und anschliessend "Im Kartenausschnitt filtert", kommt eine leere Liste weil es weniger Seiten hat.

Erwartetes Verhalten:
Es springt auf Seite 1, da es die Seite 73 nicht mehr gibt

Verhalten:
Es bleibt bei Seite 73 und zeigt eine Leere Seite an.

Ps. Beim Editor Modus funktioniert es und ist somit richtig umgesetzt.

**Comment by gysimichael** [comment]
Im Editor Modus, wenn man in der Karte Reinzoomt, dann auf "Im Kartenausschnitt filtern" klickt, anschliessend Seite 3 auswählt, eine Bohrung auswählt, und "Done" klickt:

Erwartetes Verhalten:
Es kommt auf Seite 3 zurück

Verhalten:
Es springt auf Seite 1

**Comment by gysimichael** [comment]
sonst funktioniert es gut

**Comment by gysimichael** [comment]
@danjov: Editor ist nun super und funktioniert bestens. Beim Viewer gibt es noch issues:

- Wenn alle Bohrungen eingeblendet sind, ich auf Seite 73 gehe, auf eine Bohrung klicke und zurück, dann springt es auf Seite 1, sollte aber die Seite 73 beibehalten, weil diese ja exisitiert
- Wenn alle Bohrungen eingeblendet sind, ich auf Seite 73 gehe, dann auf "Filter by map" klicke, dann spring es auf Seite 1 -> somit ok. Wenn ich aber unter diesen Umständen dann auf Seite 3 klicke, eine Bohrung anschaue und zurück gehe spring er weiterhin auf Seite 1

Beim Editor funktioniert dies einwandfrei.

**Comment by RBordoni** [comment]
Die beiden Fehler treten nur bei diesen beiden Settings auf:
![Image](https://user-images.githubusercontent.com/31883445/230021446-0d5c2d2b-7a47-4c52-b143-181249eb7a59.png)

**Comment by gysimichael** [comment]
sehrgut, das scheint nun zu klappen
