### ISSUE TITLE
Heatmap Code prüfen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#189]
Den Code-Teil von assets.swissgeol.ch prüfen, wie einfach man diesen bei boreholes.swissgeol.ch einbinden kann jedoch noch nichts umsetzten. Je länger ich die Cluster nutze, des besser gefallen sie mir, daher gut möglich, das wir es vorerst bei den Clusters belassen.

**Comment by MiraGeowerkstatt** [comment]
Noch als Info zur Entscheidungsfindung: Beim Cluster haben wir grundsätzlich auch die Möglichkeit aber einer festzulegenden Zoomstufe alle Punkte darzustellen und ganz auf das Clustern zu verzichten (analog zur Lösung mit der Heatmap).

**Comment by RBordoni** [comment]
Entscheid 06.12.2022: Version mit Cluster umsetzen
