### ISSUE TITLE
Script zur Berrechnung von Gemeinde und Kanton

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#190]
Wenn Koordinaten importiert werden, werden die Einträge für Gemeinde und Kanton nicht automatisch aus dem Dienst gelesen. 
Es wäre gut, ein Skript zu schreiben, welches dies macht. Dieses Skript könnte man anschliessend auch für den Importer benützten, da hier die gleiche Problematik vorliegt

**Comment by RBordoni** [comment]
Hängt zusammen mit #217

**Comment by RBordoni** [comment]
Skript noch auf DEV, TEST und PROD ausführen.

**Comment by danjov** [comment]
Die Migration wurde am 13.02.2023 auf allen Umgebungen ausgeführt.
