### ISSUE TITLE
Bei Eingabe in LV 03 rechnet es den Kanton und die Gemeinde nicht

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#206]
**Repro Steps:**

1. Editor > beliebige Bohrung > Start editing
2. LV03 wählen und gültige Koordinaten eingeben

**Erwartet:**
Kanton und Gemeinde werden ausgefüllt

**Beobachtet:**
Kanton und Gemeinde werden nicht ausgefüllt

![Image](https://user-images.githubusercontent.com/31883445/206189710-f16b1aab-be4c-4fa4-a3de-ef405415ace6.png)

**Comment by gysimichael** [comment]
Funktioniert super, vielen herzlichen Dank!
