### ISSUE TITLE
Neu erstellte Bohrung mit LV03 erscheint nicht in Karte

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#213]
**Repro Steps:**

1. Editor > +New
2. Workgroup "swisstopo-Hiwi-Datman" oder beliebig
3. LV03 auswählen und Koordinaten ausfüllen
4. Punkt erscheint in der Dateilkarte
5. Stop editing
6. Zurück zur Liste

**Erwartet:**
In der Übersichtskarte wird der Punkt angezeigt

**Beobachtet:**
Der Punkt wird in der Übersichtskarte nicht angezeigt

Detailansicht mit angezeigtem Punkt:

![Image](https://user-images.githubusercontent.com/31883445/206466743-4f3f7318-89bb-4919-865c-d51973b24dea.png)

Übersichtskarte ohne Punkt:

![Image](https://user-images.githubusercontent.com/31883445/206467419-c2c9f7d1-37dc-4a54-9139-388f98c1320e.png)

Anmerkungen:
- Das gleiche mit LV95 führt nicht zum Fehler
- Die bestehenden mit LV03 werden angezeigt

**Comment by gysimichael** [comment]
Sieht gut aus!
