### ISSUE TITLE
Berechnung von Gemeinde und Kanton auf Service umstellen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#217]
Bisher sind die Gemeindepolygone in der DB gespeichert und für die Berechnung von Gemeinde und Kanton werden diese verwendet. Die Nachführung ist nicht kontinuierlich gewährleistet.

Die Berechnung von Gemeinde und Kanton soll neu einen Service verwenden, statt einer Auswertung von Gemeinde- und Kantonsgeometrien in der Applikation. Beispiel eine Services:
https://api3.geo.admin.ch/rest/services/api/MapServer/identify?geometryType=esriGeometryPoint&geometry=548945.5,147956&tolerance=0&layers=all:ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill&returnGeometry=false

Damit werden wir eine grosse Datenmenge und 2 db Tabellen los.

**Comment by Philippluca** [comment]
Zusammenfassung aus der Besprechung mir @RBordoni am 4.1.2023:
- Die Evaluierung von Gemeinde/Kanton/Land wird beim Bearbeiten/Setzten von den Koordinaten ausgeführt.
- Gemeinde/Kanton/Land werden gemäss Evaluation zu Erfassungszeit in die DB gespeichert und nicht automatisch nachgeführt.
- Die Routine zur Evaluierung von Gemeinde/Kanton/Land soll für den Import wiederverwendbar sein.
- Die Evaluierung passiert über Services von geo.admin.ch.

**Comment by Philippluca** [comment]
Nachtrag Wochensitzung 4.1.2022

- Es soll möglich sein automatisiert und regelmässig (z.B. monatlich) die Evaluierung von Gemeinde/Kanton/Land für alle Datensätzte zu wiederhohlen.
- Bei einem Export muss nicht erneut evaluiert werden.
- Bei einem Import werden Gemeinde/Kanton/Land immer evaluiert.

Note: 
Über https://api3.geo.admin.ch/rest/services/api/MapServer/identify?geometryType=esriGeometryPoint&geometry=548945.5,147956&tolerance=0&layers=all:ch.swisstopo.swissboundaries3d-land-flaeche.fill,ch.swisstopo.swissboundaries3d-kanton-flaeche.fill,ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill&returnGeometry=false können alle 3 Felder gelichzeitig evaluiert werden.

**Comment by gysimichael** [comment]
Viele GeODin Bohrungen haben immer noch keinen Eintrag bei Kanton und Gemeinde, müssten diese jetzt nicht ausgefüllt sein, weil es diese Routine gibt, welche diese im Hintergrund berechnet?

Den Rest ist für mich schwierig zu testen, da ich ins Backend sehen kann. Funktionieren tut es auf jeden fall, wenn ich eine neue Koordinate setzte.

**Comment by RBordoni** [comment]
Die Nachberechnung der bestehenden GeODin Daten ist noch nicht gemacht. Sie wird mit #190 erfolgen.
