### ISSUE TITLE
Bei Rückkehr zur Hauptkarte werden nicht alle Bohrungen angezeigt.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#218]
**Reprosteps**

- Im Editormodus auf der Hauptkarte ein beliebiges Cluster anwählen. Karte zoomt sodass statte des Clusters alle Einzelpunkte sichtbar werden. 
- Auf einen beliebigen Punkt klicken um zur Editiermaske zu gelangen.
- Ohne etwas zu editieren via "Done" zur Kartenansicht zurückkehren.
- Karte herauszoomen.

**Erwartet**

  Alle Bohrungen sind sichtbar sobald die Karte herausszoomt.

**Beobachtet**

 Nur die Punkte die in der hereingezoomten Ansicht sichtbar waren sind sichtbar. (Wird der "Filter by map" Button betätigt, aktualisiert zwar die Liste und zeigt alle Bohrungen, auf der Karte sind weiter nur die gefilterten Bohrungen sichtbar).

**Comment by gysimichael** [comment]
scheint zu funktionieren
