### ISSUE TITLE
Zahlen mit Tausender-Trennstrichen anzeigen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#223]
Betrifft nicht nur Koordinaten, sondern wenn möglich alle Zahlenfelder. Format 1'000'000.00.
Die Eingabe muss aber ohne das Tippen der Trennstriche erfolgen. Tippen = 1000000.00 → Anzeige = 1'000'000.00

**Comment by gysimichael** [comment]
Zurzeit ist es aber glaube ich nur auf die Koordinaten beschränkt (Beispielsweise Bohrung Bülach-1 ist die Teufe noch ohne Striche)

**Comment by MiraGeowerkstatt** [comment]
Zu Ergänzen: 

4 Teufenfelder
From-To Felder in Profilen (Stratigraphy, Casing ...)
Bohrloch Durchmesser

**Comment by gysimichael** [comment]
-Im Editormodus oben Links die Anzahl Bohrungen müsste man noch die Striche aktivieren (sind zurzeit noch ohne)

-Im Viermodus oben Links die Anzahl Bohrungen müsste man noch die Striche aktivieren (sind zurzeit noch ohne)

-Im Viewermodus, wenn man auf eine Bohrung Klickt, erscheint oben rechts noch Total Depth MD ohne Striche.

(siehe Bohrung Test Michael auf test.boreholes.swissgeol.ch)

Rest scheint in Ordnung.

**Comment by gysimichael** [comment]
ich glaube wir haben alle gefunden; Danke!
