### ISSUE TITLE
Nachberechnung LV95 der migrierten Daten

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#226]
Input Michael 14.12.2022:

> Wenn ich bestehende Bohrungen anschaue, dann sind bei LV03 und LV05 die gleichen Einträge, hat das damit zu tun, dass hier die ganze DB Einträge in LV03 noch migriert werden müssen?

Die Daten wurden per Shift von LV95 zu LV03 zurückgerechnet (#61). Hingegen wurde das sekundäre Referenzsystem (LV95) nicht neu mit Fineltra berechnet. Dies ist nachzuholen.

**Comment by MiraGeowerkstatt** [comment]
Wir haben die Daten mit dem Migrationsendpunkt '/api/v2/migrate/recalculatecoordinates' für DEV und TEST neu berechnet.
Die neu berechneten Koordinaten werden aktuelle mit der maximalen Anzahl Kommastellen gespeichert, so wie sie von dem Migrationsendpunkt zurück kommen. (Siehe Bild). 
 
Vielleicht müsste man noch entscheiden wie/ob wir das in Einklang bringen wollen mit dem Konzept, wenn neue Daten erfasst werden und die Kommastellen entsprechend der Eingabe gerundet werden.

![Image](https://user-images.githubusercontent.com/49144408/207825552-4907be0b-ac70-43f2-a4bf-69b8b99f5764.png)

**Comment by RBordoni** [comment]
@gysimichael  Fragen:

- Zu Kommentar oben: Meiner Meinung nach sollten die Koordinaten auf die gleiche Art gerundet werden, wie bei der Handeingabe. Die vielen Stellen vermitteln eine falsche Genauigkeit. Deine Meinung?
- Das Script läuft momentan nicht durch, wenn es Bohrungen ohne Koordinaten hat. Das es wiederverwendbar ist, stellt sich folgende Frage: Soll es abbrechen, wenn es Bohrungen ohne Koordinaten findet (→ dadurch werden solche Fälle erkannt, müssen dann aber manuell bereinigt werden) oder sollen dies Fälle einfach ignoriert und übersprungen werden?

**Comment by gysimichael** [comment]
> * Zu Kommentar oben: Meiner Meinung nach sollten die Koordinaten auf die gleiche Art gerundet werden, wie bei der Handeingabe. Die vielen Stellen vermitteln eine falsche Genauigkeit. Deine Meinung?

genau, unbedingt!

> * Das Script läuft momentan nicht durch, wenn es Bohrungen ohne Koordinaten hat. Das es wiederverwendbar ist, stellt sich folgende Frage: Soll es abbrechen, wenn es Bohrungen ohne Koordinaten findet (→ dadurch werden solche Fälle erkannt, müssen dann aber manuell bereinigt werden) oder sollen dies Fälle einfach ignoriert und übersprungen werden?

Meines erachtens sollte das kaum vorkommen, das es keine Koordinaten enthält, daher würde ich vorschlagen, es durchlaufen zu lassen

**Comment by danjov** [comment]
Sobald die Koordinaten bereinigt wurden, soll ein Excel-File der `borehole`-Tabelle an @gysimichael gesendet werden.

**Comment by flenny** [comment]
Aufgrund Abhängigkeiten zu #217 (Anpassung Testdaten) kurzzeitig zurückgestellt

**Comment by flenny** [comment]
Die Koordinaten wurden mit der Genauigkeit (Anzahl Nachkommastellen) des ursprünglichen Koordinatensystem auf _dev_ und _test_ neu gerechnet. [Bsp 1](https://test.boreholes.swissgeol.ch/editor/17084), [Bsp 2](https://test.boreholes.swissgeol.ch/editor/14442). Beim nächsten Release müssen die Änderungen (resp. die Migration) noch auf Prod ausgeführt werden.

**Comment by flenny** [comment]
Nach dem Release auf Prod und der Bereinigung der Koordinaten auf Prod, muss noch ein Excel-File der borehole-Tabelle (inkl. Layers) erstellt und an @gysimichael gesendet werden.

**Comment by gysimichael** [comment]
wäre es auch möglich mir ein aktuellen Export von Codeliste zu machen? Dann hätten wir alles zusammen. Vielen Dank im Voraus.

**Comment by flenny** [comment]
Die Koordinaten wurden soeben auch auf Prod neu berechnet. Bsp. https://boreholes.swissgeol.ch/editor/14442

**Comment by flenny** [comment]
Export der Tabellen _borehole_, _codelist_ und _layers_ wurde erstellt und in Teams an @gysimichael gesendet.
