### ISSUE TITLE
Zahleneingabe mit Nullen ( .00) soll gespeichert werden und Kommastellen bestimmen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#227]
Eine Eingabe von Koordinaten mit nur Nullen hinter dem Komma, wird heute nicht berücksichtigt Die Kommastellen werden weder gespeichert noch für die Berechnung des anderen Referenzsystems verwendet.

![Image](https://user-images.githubusercontent.com/31883445/207583235-02c04967-1244-4531-8251-87b43c835f0d.png)

Neu sollen sie mindestens für die Berechnung des anderen Referenzsystems als Angabe der Anzahl Kommastellen verwendet werden.

**Comment by MiraGeowerkstatt** [comment]
Die Kommastellen werden jetzt für die Berechnung des anderen Referenzsystems verwendet. Allerdings werden sie weiterhin nicht gespeichert, da es ein grösserer Umbau wäre und wir den Datentyp der Koordinaten in der DB ändern müssten.

**Comment by gysimichael** [comment]
ist das somit etwas, was wir für die Diskussion am Mittwoch auf die Pendenzenliste schreiben müssen?

**Comment by MiraGeowerkstatt** [comment]
Ja wir können es sicher anschauen.

**Comment by RBordoni** [comment]
Entscheid Besprechung 21.12.2022: Es ist für gewisse Stellen wichtig, die Zahlen mit den richtigen Kommastellen zu sehen, auch wenn es nur Nullen sind. → Umsetzen, technische Lösung überlegen.

**Comment by gysimichael** [comment]
Das haben wir vergessen zu besprechen heute, müsste man dann nochmals angehen...

**Comment by RBordoni** [comment]
Für die Umsetzung ist pro Zahlenfeld ein zusätzliches Precision-Attribut zu führen in dem die Anzahl der Kommastellen gespeichert wird.

**Comment by gysimichael** [comment]
sehr cool, danke!
