### ISSUE TITLE
Workflow Kommentare bereinigen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#232]
> Zum Löschen von "borehole_form" die Werte werden derzeit noch für die "Mention" Funktion in der Kommentarbox gebraucht.
> 
> Mittels @ kann man einen Wert auswählen und der Wert wird dann hervorgehoben dargestellt. Wir müssten abklären ob das noch gebraucht wird.
> 
> ![Image](https://user-images.githubusercontent.com/49144408/199747987-c6f88998-dcbe-42b1-8d31-a370dd84eedb.png)
> 
> ![Image](https://user-images.githubusercontent.com/49144408/199748689-80727dde-01fe-4cd8-92e8-d34b9d3bb1c8.png)

Ich denke, diese Funktion kann man löschen und somit auch in den Codeliste aufräumen. Ist aus meiner Sicht mässig gut umgesetzt und kann gut darauf verzichtet werden. Das Textfeld gibt ja genug freiheiten, das auch ohne Mentioning zu machen.

**Comment by RBordoni** [comment]
Entscheid Wochensitzung 21.12.2022: Funktion löschen

**Comment by gysimichael** [comment]
Irgendwie fehlen die Buttons beim Workflow, um weiter zu leiten... Da wurde glaube ich zu viel gelöscht.

**Comment by gysimichael** [comment]
ok, dann ist es somit in Ordnung!
