### ISSUE TITLE
layer_kind

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#233]
> "layer_kind" kann zum jetzigen Zeitpunkt auch noch nicht entfernt werden, da es im Hintergrund dazu verwendet wird. Den Layertyp ( z.B. Casing, Stratigraphy, Backfill , Instrumentation) festzulegen. Das könnte man allenfalls auch anders lösen aber ich würde vorschlagen das erst anzugehen, wenn allfällige Modellanpassungen durch sind.

Ich denke, mit der Datenmodel sollte dies anders gelöst werden und nicht mit den Geolcodes verlinkt sein.

**Comment by RBordoni** [comment]
Wird mit #254 und #253 umgesetzt. Dieses Issue wird daher geschlossen.
