### ISSUE TITLE
IDs Umstellen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#235]
Bei der Migration der IDs ist mir ein Fehler unterlaufen, der jetzt von meinem Mitarbeiter gespottet wurde.

Wäre es möglich, Alle IDs der Workgroup GeODin die Werte der ID Original in ID Bohrhole zu schreiben, und die Werte der ID Borehole in ID Original? Bei der Workgroup swisstopo_Hiwi ist alles richtig und muss nichts geändert werden.

Habe diese beiden ID für die Migration irrtümlicher Weise verwechselt.

**Comment by danjov** [comment]
@gysimichael Wie soll mit Bohrungen umgegangen werden, die kein `ID Borehole` definiert haben? Sollen wir diese ebenfalls migrieren und `ID Original` in diesem Fall leer lassen?

**Comment by gysimichael** [comment]
diese müssen nicht migriert werden, sprich die werden somit keine ID Original haben.

ID Original sollten Nummern sein die von Büros vergeben wurden, das ist aber nicht bei allen Bohrungen der Fall, daher nicht leerlassen sondern weglassen

ID Borehole sollte die Nummer enthalten, die in GeODin als Shortname gehalten wurde. Jede GeODin Bohrung enthält diese Nummer, daher gibt es hier keine Leeren Felder.

Hilft das so?

**Comment by danjov** [comment]
Nach Rücksprache mit @gysimichael soll wie folgt migriert werden:
* Überall, wo eine `ID Borehole` vorhanden ist: Diese IDs müssen nach `ID Original` migriert werden.
* Alle Werte von `ID Original` zu `ID Borehole` migrieren.

**Comment by gysimichael** [comment]
Danke!
