### ISSUE TITLE
Bulk Editing

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#24]
Alle Attribute, die Universal geändert werden sollen (bspw. ohne Koordianten, Bemerkungen, Beschreibungen) sollten hier aufgeführt sein und mit dem richtigen technischen Attribut verlinkt sein.

**Comment by RBordoni** [comment]
Test RB: Soweit erfüllt. Dropdown nicht hierarchisch, separater Bug → https://github.com/geoadmin/suite-bdms/issues/110

**Comment by gysimichael** [comment]
sieht gut aus, danke für die Umsetzung
