### ISSUE TITLE
Nach "Settings" wechselt es immer in den Viewer Mode

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#244]
**Repro Steps:**

1. BDMS > Editor Modus
2. Settings öffnen
3. Zurück mit "Done"

**Erwartet:**
Die Applikation befindet sich immer noch im Editor Mode

**Beobachtet:**
Die Applikation befindet sich im Viewer Mode

**Comment by gysimichael** [comment]
Cool, vielen Dank! Funktioniert bestens
