### ISSUE TITLE
Nicht benötigte Spalten löschen

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#245]
#138  **Datenschemaanpassungen** 

Nicht mehr benötigte Spalten löschen. 

| Tabelle   | Spalte | 
| ------------- | ------------- |  
| borehole| import_id| 
| stratigraphy| import_id| 
| layer| import_id| 
| layer| tectonic_unit_id_cli| 
| borehole| tecto_id_cli | 
| layer| symbol_id_cli | 
| layer| soil_state_id_cli | 
| layer| kirost_id_cli |

**Comment by gysimichael** [comment]
Kann ich leider nicht prüfen aber wird sicher in Ordnung sein.
