### ISSUE TITLE
Fehlende contraints hinzufügen.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#247]
**#138 Datenschemaanpassungen**

Fehlende Constraints ergänzen

| Tabelle   | Spalte | zu referenzierende Tabelle  |
| ------------- | ------------- |  ------------- |
| stratigraphy  | fill_casng_id_sty_fk | stratigraphy    |
| layer | gradation_id_cli  | codelist|

**Comment by gysimichael** [comment]
kann ich leider nicht prüfen, denke aber es ist in Ordnung :-)
