### ISSUE TITLE
Neues Feld für Kantonsspezifische legacy Daten.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#248]
#138 Datenschemaanpassungen

Auf der Tabelle "layer" soll ein neues  Character-Feld mit dem Namen "original_lithology" eingeführt werden.
Dorthin sollen die Inhalte der Spalten "unconrocks_id_cli" und "lithok_id_cli" als unstrukturierter Text übertragen werden.
Die Spalten sollen anschliessend gelöscht werden.

**Comment by MiraGeowerkstatt** [comment]
@RBordoni Bei dieser Schemaänderung kannst du beim Testen besoderen Wert auf den Layer legen.
Erstellen/Modifizieren von Layers.
Ausserdem Duplizieren von Stratigraphien, Duplizieren von Boreholes.

**Comment by MiraGeowerkstatt** [comment]
! Bitte erst nach dem nächsten Release Testen! Durch das zurücksetzen der DB auf DEV ist die Migration dort noch nicht drauf.

**Comment by MiraGeowerkstatt** [comment]
@RBordoni Kann jetzt getestet werden.

**Comment by RBordoni** [comment]
Testresultat: Ein Bug beim Kopieren einer Stratigraphie

**Repro Steps:**
1. Ausgangsdatensatz mit Stratigraphie-Layer, bei dem Felder mit Mehrfacheiträgen gefüllt sind (USCS 3, Kornform, Kornrundung, ...)
2. Stratigraphie Klonen/Kopieren

**Erwartet:**
Alles wird dupliziert

**Beobachtet:**
Die Felder mit Mehrfacheinträgen werden nicht kopiert und sind leer. Die anderen Felder weren kopiert.
