### ISSUE TITLE
Von Feedback auf User Object verweisen, statt den Usernamen als text zu speichern.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#249]
#138 Datenschemaanpassungen

In der Tabelle Feedback besteht die Spalte "user_feb" in der der username als text gespeichert wird. Analog zu anderen Tabellen soll hier  eine Id gespeichert werden die auf die User-Tabelle verweist.  Das Anzeigen des Usernamens im Client ist entsprechend anzupassen. 

Auf neues API umstellen

**Comment by danjov** [comment]
Dieses Issue hat sich erledigt, da mit #1024 die Feedback-Funktion zurückgebaut wird.
