### ISSUE TITLE
Kopie einer Bohrung

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#25]
Diese Funktion im Editor funktioniert nicht. Muss wohl neu aufgesetzt werden. Hier sehe ich den Vorteil wenn man Bohrungen in verschiedene Workgroups kopiert werden könnten oder eine sehr ähnliche Bohrung existiert und so eine Kopie angepasst werden kann

**Comment by patrickackermann** [comment]
Wie muss beim Kopieren mit den Feldern `CreatedBy`, `Created` (Datum), `UpdatedBy` und `Updated` (Datum) umgegangen werden?

**Comment by RBordoni** [comment]
@patrickackermann Es soll eine vollständige 1:1-Kopie sein. Selbst Created und CreatedBy soll beim alten belassen werden. Einzig die Titelerweiterung (copy) ist ok und weicht somit von der 1:1-Kopie ab.

**Comment by RBordoni** [comment]
Test Version: 2.0.57+782f061: 
→ Es wird keine Kopie erstellt. Dialog geht bis zur Bestätigung "Create a Copy", dann passiert einfach nichts.

**Comment by danjov** [comment]
Der Fehler tritt auf, da die Spalte `borehole.contact_id` manuell aus der Datenbank gelöscht wurde und nicht mit einem Skript. Wird mit #146 erledigt.

**Comment by gysimichael** [comment]
cool, danke für das fixen!
