### ISSUE TITLE
Datentyp vereinheitlichen.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#250]
**#138 Datenschemaanpassungen**

In der Datenbank kommt sowohl der Typ "Datetime" als auch"Dateonly" für Datumseinträge vor. 
Es ist zu prüfen ob sich die Datentypen ohne grossen Aufwand zu "Datetime" vereinheitlichen lassen.

**Comment by danjov** [comment]
@RBordoni Bitte kurz testen, ob vom Erstellen bis zum Löschen eines Boreholes alles noch so funktioniert, wie es sollte. Danke!

**Comment by gysimichael** [comment]
funktioniert, habe auch kurz vom Erstellen bis löschen alles getestet! Danke
