### ISSUE TITLE
1:n Korrekturen aus GeODin Migration

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#252]
auf der Prod DB können unter "layer_codelist" folgende Einträge gelöscht werden, diese sind falsch und bin mir nicht sicher, woher die kommen, daher weg damit wo code_cli:
-custom_lith_pet_top_bedrock
-mcla101
-mcla104
-mlpr117

Bei der Migration aus GeODin ist bei mlpr115 was schiefgegangen und müsste korrigiert werden (Alle anderen Einträge stimmen):
1. alle Einträge mit id_cli_fk:
        -21115006 (Anzahl: 8633) 
        -21115008 (Anzahl 67565)
    können in der DB gelöscht werden, die sind falsch, jedoch beachten das man hier auf die GeODin Einträge filtert. Die swisstopo-Hiwi Einträge zu diesen Codes sind richtig

2. GeODin Attribut "kornrundu" mit dem Eintrag (in allen Variationen zusammen mit anderen Abkürzungen):
        -ger
     können in layer_codeliste auf dem Attribut id_cli_fk mit dem Code 21115006 eingetragen werden (Anzahl: 4057)

3. GeODin Attribut "kornrundu" mit dem Eintrag:
        -ka
     können in layer_codeliste auf dem Attribut id_cli_fk mit dem Code 21115008 eingetragen werden (Anzahl: 64968)

GeODin Attribut "colour" mit den Einträgen (in allen Variationen zusammen mit anderen Abkürzungen):
         -wei (Anzahl 201)
         -grgr (Anzahl 360)
         -grbr (Anzahl 550)
    gingen bei der Migration vergessen. Bitte:
         -wei in die DB mit 21112012 schreiben
         -grgr in die DB mit 21112016 schreiben
         -grbr in die DB mit 21112014 schreiben

Alle anderen Farbwerte wurden richtig migriert.

Das wäre somit die letzten Bugs der Migration.

**Comment by danjov** [comment]
Aufgrund [fehlender Constraints](https://github.com/geoadmin/suite-bdms/issues/247) befinden sich in der `layer_codelist`-Tabelle etliche verwaiste Einträge, die bereinigt werden müssen.

@gysimichael Ich schlage vor, dass wir diese Bereinigungen kurz zusammen besprechen.

**Comment by gysimichael** [comment]
macht sicher sinn, bin Morgen ab 10 Uhr frei, ruf mich doch einfach kurz an.

**Comment by danjov** [comment]
Die GeODin-Migration der `mlpr115` Codes wurde am 19.01.2023 10:05 Uhr auf Prod korrigiert:
```sql
-- GeODin-Migration der mlpr115 Codes korrigieren
DELETE FROM bdms.layer_codelist
WHERE (id_lay_fk, id_cli_fk) IN (
	SELECT lc.id_lay_fk, lc.id_cli_fk
	FROM bdms.layer_codelist lc
	INNER JOIN bdms.layer l ON l.id_lay = lc.id_lay_fk
	INNER JOIN bdms.stratigraphy s ON s.id_sty = l.id_sty_fk
	INNER JOIN bdms.borehole b ON b.id_bho = s.id_bho_fk
	WHERE lc.id_cli_fk IN (21115006, 21115008) AND b.id_wgp_fk = 12
);	
	
INSERT INTO bdms.layer_codelist
	SELECT l.bdms_layer_id, c.id_cli, 'mlpr115'
	FROM geodin.geodin_loc_stlayer l
	INNER JOIN bdms.codelist c ON c.code_cli = 'ger' AND c.schema_cli = 'mlpr115'
	WHERE kornrundu LIKE 'ger%' OR kornrundu LIKE '%,ger' OR kornrundu LIKE '%, ger' OR kornrundu LIKE '%\,ger,%';
	
INSERT INTO bdms.layer_codelist
	SELECT l.bdms_layer_id, c.id_cli, 'mlpr115'
	FROM geodin.geodin_loc_stlayer l
	INNER JOIN bdms.codelist c ON c.code_cli = 'kA' AND c.schema_cli = 'mlpr115'
	WHERE kornrundu = 'ka';	
```

**Comment by danjov** [comment]
Die GeODin-Migration der mlpr112 Codes wurde am 19.01.2023 10:18 Uhr auf Prod nachgeholt:
```sql
-- GeODin-Migration der 'colour' Werte (mlpr112) nachholen
UPDATE bdms.codelist
SET code_cli = 'wei'
WHERE code_cli = 'wie';

INSERT INTO bdms.layer_codelist
	SELECT l.bdms_layer_id, c.id_cli, 'mlpr112'
	FROM geodin.geodin_loc_stlayer l
	INNER JOIN bdms.codelist c ON c.code_cli = 'wei' AND c.schema_cli = 'mlpr112'
	WHERE colour LIKE 'wei%' OR colour LIKE '%,wei' OR colour LIKE '%, wei' OR colour LIKE '%\,wei,%';

INSERT INTO bdms.layer_codelist
	SELECT l.bdms_layer_id, 21112016, 'mlpr112'
	FROM geodin.geodin_loc_stlayer l
	WHERE colour LIKE 'grgr%' OR colour LIKE '%,grgr' OR colour LIKE '%, grgr' OR colour LIKE '%\,grgr,%';

INSERT INTO bdms.layer_codelist
	SELECT l.bdms_layer_id, 21112014, 'mlpr112'
	FROM geodin.geodin_loc_stlayer l
	WHERE colour LIKE 'grbr%' OR colour LIKE '%,grbr' OR colour LIKE '%, grbr' OR colour LIKE '%\,grbr,%';
```

**Comment by danjov** [comment]
Alte Einträge aus der `contents`-Tabelle wurden am 19.01.2023 10:33 Uhr auf Prod gelöscht:
```sql
DELETE
FROM bdms.contents
WHERE id_cnt < 14;
```
