### ISSUE TITLE
Tabelle Layer_codelist  in 6 Tabellen aufteilen

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#256]
In der Tabelle "layer_codelist" werden 1:n Beziehugne für die folgenden Felder abgebildet: "grain_shape", "grain_angularity", "organic_component", "debris" "color". 

![Image](https://user-images.githubusercontent.com/49144408/208985818-4b4edef1-bece-48ff-857d-60b1a41b584a.png)

Goal: Aus Gründen der Übersichtlichkeit soll pro Attribut eine eigene 1:n Tabelle geführt werden. 
Mit der Umsetzung von #183 soll eine weitere Tabelle für die Neue 1:n Beziehung  für uscs_3 erstellt werden.

**Comment by RBordoni** [comment]
Test Version: 2.0.584:

Wird bei den Suchfiltern unter **Filter > Lithology > USC 3** (und alle anderen umgebauten) ein Wert ausgewählt, folgt ein Fehler.



![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/281881f6-a182-4a60-b166-f7eca947e1c8)

**Comment by gysimichael** [comment]
Bei allen 6 Einträgen funktioniert die Funktion "Zurücksetzten" nicht.

Aus meiner Sicht sollte diese Funktion alle Einträge löschen

**Comment by gysimichael** [comment]
funktionniert nun bestens, vielen Dank!
