### ISSUE TITLE
Bei gewissen Bohrungen fehlen die Workflow Buttons

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#265]
Bei den GeODin Bohrungen fehlen die Workflow Buttons. Auch in der produktiven Version. Eventuell wurde bei der Migration in den Daten etwas nicht richtig gesetzt?

**Repro Steps**

1. Filtern nach Original Name = "Ächerlitunnel - B81a"
2. öffnen und Start editing

**Beobachtet**:
siehe folgende Nummern in Printscreen
(1) Buttons fehlen
(2) Status ist auf Submitted **(ist das richtig?)**
(3) Das "Comments"-Feld zeigt ein komisches Verhalten. Tippt man ins Feld wird oben der Eintrag gleich wiederholt

![Image](https://user-images.githubusercontent.com/31883445/211282931-ab3421f8-3ca2-4c90-a62a-55a93e42c70b.png)

Bei den nicht GeODin Daten sind die Buttons vorhanden

**Comment by gysimichael** [comment]
In Absprache mit meinem Mitarbeiter können alle Einträge bei den Kommentaren gelöscht und alle Bohrungen im Workflow auf "change in Progress" gesetzt werden. Somit würden dann alle Bohrungen in diesem Status sein und man könnte dann auch sauber mit der Prüfung der Daten beginnen.

**Comment by danjov** [comment]
Die Workflows (inkl. Kommentare) wurden bei allen Bohrungen auf allen Umgebungen am 19.01.2023 17:10 Uhr zurückgesetzt:
```sql
-- Alle Workflow-Einträge mit einem anderen Status als 'Edit' (= Change in Progress) löschen
DELETE FROM bdms.workflow
WHERE id_rol_fk <> 1;

-- Alle Kommentare aus den Workflow-Einträgen löschen
UPDATE bdms.workflow
SET notes_wkf = NULL;
```

**Comment by gysimichael** [comment]
Das Problem mit dem Button zum Weiterleiten im workflow besteht immer noch

**Comment by danjov** [comment]
Die Workflows für die GeODin-Bohrungen waren nicht korrekt eingetragen und wurden mit folgendem Skript am 01.02.2023 16:55 Uhr auf allen Umgebungen korrigiert:
```sql
-- Remove finished date for all GeODin borehole workflows
UPDATE bdms.workflow w
SET finished_wkf = NULL
FROM bdms.borehole b
WHERE b.id_bho = w.id_bho_fk AND b.geodin_id IS NOT NULL AND w.id_rol_fk = 1 AND w.finished_wkf IS NOT NULL AND w.finished_wkf = w.started_wkf
```

**Comment by gysimichael** [comment]
Danke!
