### ISSUE TITLE
Einzelkarte wird beim Editieren langsam

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#266]
Repro Steps:

1. BDMS > Beliebige Bohrung öffnen > Start editing
2. In Karte Punkt mehrmals verschieben

Beobachtet:

Nach mehreren (bei mir ein bis zwei) Verschiebungen wird die Applikation langsam und zeitweise hängt der Browser

![Image](https://user-images.githubusercontent.com/31883445/211295693-9248b998-c2c7-4cda-970f-a1d29e7b99cf.png)

**Comment by MiraGeowerkstatt** [comment]
Wird erst nach Abschluss von #217 angegangen.

**Comment by gysimichael** [comment]
sieht gut aus, danke!
