### ISSUE TITLE
Neues Feld "original_lithology" in UI integrieren.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#277]
Kann nachdem #248 erfolgreich migriert ist angegangen werden.

**Comment by MiraGeowerkstatt** [comment]
@gysimichael  Wir haben mit #248 das neue Feld "original_lilthology" eingeführt das die Daten von "unconrocks_id_cli" und "lithok_id_cli" jetzt als kommagetrennten englischen Text enthält. Bisher wurden diese beiden Felder aber soweit ich sehe nirgends im UI angezeigt und konnten auch nicht editiert werden.

Daher die Frage, soll das neue Feld "original_lithology" im UI angezeigt werden? zb. im Viewer Modus? Ich nehme an, edieren soll man es jedenfalls nicht, oder?

**Comment by gysimichael** [comment]
Genau, dieses neue Attribut "original_lithology" sollte sowohl im Editor als auch im Viewer angezeigt werden unter dem Attribut "lithology" in Stratigraphy platziert werden. Es soll als Textfeld Editirbar sein und die Filter und Settings dementsprechend anpassen

**Comment by MiraGeowerkstatt** [comment]
@RBordoni Bitte beim Testen dieses Issues neben den Layerfunktionen (Editieren, Anzeigen, Kopieren, Klonen, Filtern) auch ein Augenmerk auf das Editieren der Codelists legen.

**Comment by RBordoni** [comment]
Testresultat RB: Zwei Bugs gefunden. @MiraGeowerkstatt in separaten Issues beschrieben.

→ #306 
→ #307

**Comment by gysimichael** [comment]
sieht gut aus, danke!
