### ISSUE TITLE
Daten unter Intstrumente werden nicht gespeichert

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#279]
Wenn man Einträge unter Instrumente macht:

Erwartetes Verhalten:
Einträge werden gespeichert

Jetziges Verhalten:
Einträge werden, nach Wechsel des Reiters gelöscht und bleiben als leere Felder bestehen

**Comment by patrickackermann** [comment]
Ich konnte es nicht reproduzieren und es funktioniert auch gemäss @gysimichael  wieder.
