### ISSUE TITLE
Initialisierungs schliesst nicht ab

### ISSUE THREAD

**Issue by Philippluca** [geoadmin/suite-bdms#280]
Unter gewissen Umständen laden Teile der Viewer Seite nicht. Die Umstände gilt es zu klären.
Nach wenigen Sekunden meldet der Browser eine nicht reagierende Seite.

Browser: Edge.

![image](https://user-images.githubusercontent.com/2191817/212114854-c92c7c5b-4492-4a0e-9fe7-c819fbc30af9.png)

**Comment by danjov** [comment]
Wird mit #308 adressiert.
