### ISSUE TITLE
 Object Storage File Path/Name JSON in Spalte 'conf_fil' vereinfachen

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#289]

**Comment by gysimichael** [comment]
@RBordoni wurde hier etwas gemacht?

**Comment by danjov** [comment]
> @RBordoni wurde hier etwas gemacht?

@gysimichael Dieses Issue hat sich in der Zwischenzeit erledigt, da es die Spalte nach dem Change in https://github.com/geoadmin/suite-bdms/pull/343 nicht mehr gibt.
