### ISSUE TITLE
Daten von API auf CI anders als lokal

### ISSUE THREAD

**Issue by Philippluca** [geoadmin/suite-bdms#293]
Die Cypress Tests auf dem CI laufen im Vergleich zu lokal nicht durch. Ein Grund dafür könnten abweichende Zeitzonen auf dem CI sein. Der Grund für die Vermutung kann bei https://github.com/geoadmin/suite-bdms/actions/runs/3957922518/jobs/6778864806 beobachtet werden. Hier hat das Datum auf der zweiten Zeile der Tabelle eine Abweichung von nur einem Tag. Lokal läuft der gleiche Test durch.

**Comment by danjov** [comment]
Wird mit https://github.com/geoadmin/suite-bdms/pull/288 behoben: Die Timezone-Information in der Cypress CI Action war nicht korrekt.
