### ISSUE TITLE
3rd Party Software Credits übernehmen bzw. neu generieren

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#3]
Siehe `code_provenance.txt`.

**Comment by flenny** [comment]
Gibts hier bereits Ideen wie/wo die Lizenzinformationen/Credits im Web-Client eingebunden werden sollen? Oder ist die Idee dass bspw. eine _license.json_ automatisiert im Source-Repo erstellt wird?

**Comment by flenny** [comment]
Allenfalls macht es Sinn. Den 'Tab' Dokumentation in _About_ resp. _Über_ umzubenennen und Dinge wie Versionsinformationen, Entwicklung, Bugtracking und Lizenzinformationen dort unterzubringen. Was meinst du @danjov ?



![Image](https://user-images.githubusercontent.com/1365121/195367226-7d1b2fcb-1042-4373-8ab6-108c3bbee806.png)

**Comment by danjov** [comment]
> Gibts hier bereits Ideen wie/wo die Lizenzinformationen/Credits im Web-Client eingebunden werden sollen? Oder ist die Idee dass bspw. eine license.json automatisiert im Source-Repo erstellt wird?

Vorerst reicht es, wenn die Credits in einem File im Repo stehen und nicht in den Web-Client eingebunden werden.

> Allenfalls macht es Sinn. Den 'Tab' Dokumentation in _About_ resp. _Über_ umzubenennen und Dinge wie Versionsinformationen, Entwicklung, Bugtracking und Lizenzinformationen dort unterzubringen. Was meinst du @danjov ?
> 
> ![Image](https://user-images.githubusercontent.com/1365121/195367226-7d1b2fcb-1042-4373-8ab6-108c3bbee806.png)

Das macht auf jeden Fall Sinn 👍🏻.

**Comment by gysimichael** [comment]
wow, endlos lange liste, müsst ihr mir dann heute kurz erklären
