### ISSUE TITLE
Separate Darstellung von Lithological Description im Editor Modus.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#301]
Muss nach #300 bearbeitet werden.

Darstellung gemäss Skizze (...BDMS\Konzeption\Stratigraphie\Lösungsdesign_Stratigraphie_vEntwurf.docx)

a)  Bei Überlappung mit der vorhandenen Stratigraphy. Werden die Felder zunächste halbiert => keine massstäbliche Darstellung der Höhen.
b) Lithological Description soll im UI bearbeitet werden können. (Add, Edit, Delete).
c) Changetracker Information (Created Date, Creator, Updated Date...) sollen erfasst werden.

**Comment by RBordoni** [comment]
Erste Tests durch Michael sind schon erfolgt und die Resultate in den Issues #383 bis #392 erfasst.

**Comment by gysimichael** [comment]
Danke!
