### ISSUE TITLE
Separate Darstellung von Facies Description im Editor Modus.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#302]
Muss nach https://github.com/geoadmin/suite-bdms/issues/303 bearbeitet werden.

Darstellung gemäss Skizze (...BDMS\Konzeption\Stratigraphie\Lösungsdesign_Stratigraphie_vEntwurf.docx)

Analog Lithological Description

**Comment by gysimichael** [comment]
@MiraGeowerkstatt: es gibt noch diverse Sachen bei der Lithologie Beschreibung im Ready (heute neu erfasst); Eventuell lohnt es sich, diese zuerst zu beheben bevor dies kopiert wird für die Fazies?

**Comment by MiraGeowerkstatt** [comment]
Danke für die Info! Da wir für die beiden "Description" Spalten ohnehin die gleiche Code-Komponente verwenden, ist es nicht so relevant was zuerst geschieht. Da ich jetzt schon dabei bin, werde ich erst die Facies-Description hinzufügen. Alle weiteren Anpassungen werden dann gleich auf beide Description Spalten angewendet, ohne dass es mehr Aufwand gibt.

**Comment by gysimichael** [comment]
Sieht sehr schön aus! Bin begeistert!!!
