### ISSUE TITLE
Anzeige Feld "original_lilthology" wenn leer nicht immer gleich

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#306]
Wenn bei migrierten Daten das Feld "original_lilthology" leer ist, wird es als Viewer ohne Strich "-" angezeigt. 
Wenn der Datensatz editiert wird, ein Buchstabe eingegeben und gleich wieder gelöscht wird, ist danach ein "-" sichtbar.

vor Editing:
![Image](https://user-images.githubusercontent.com/31883445/214259269-daa32acf-2c3f-48ff-bf10-70c0d52ca9f7.png)

nach Editing:

![Image](https://user-images.githubusercontent.com/31883445/214259417-1545d530-480f-4da6-b85d-f3f669d34efa.png)

Hat das mit der Datenmigration zu tun?

**Comment by RBordoni** [comment]
Was das ursprüngliche Verhalten war, ist nicht ganz klar. Es scheint, dass Textfelder ohne Strich dargestellt wurden und Dropdown-Felder mit.

Jetzt verhalten sich die beiden Textfelder "Original Lithology" und "Lithological description" unterschiedlich. Nach dem Editieren und löschen ist beim ersteren ein Strich sichtbar, beim zweiten nicht.

**Comment by danjov** [comment]
Das hat nichts mit der Datenmigration zu tun und war schon immer so. Deine Annahme, dass Textfelder ohne Strich dargestellt werden und Dropdown-Felder mit, ist so im Code verankert.
Sollen wir das vereinheitlichen und z.B. alle nicht vorhandenen Werte mit Strich anzeigen?

**Comment by gysimichael** [comment]
Danke für die Vereinheitlichung! Sieht gut aus und macht absolut so Sinn!
