### ISSUE TITLE
Reihenfolge "Original Lithology" in "Settings - Stratigraphy fields" nicht richtig

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#307]
BDMS > Settings > Stratigraphy fields

Das Feld "Original Lithology" ist am Schluss der Liste. Alle anderen Felder entsprechen in der Reihenfolge dem Darstellungs-UI.
Richtige Position nach "Lithology"

**Comment by gysimichael** [comment]
Sieht gut aus, Danke!
