### ISSUE TITLE
Mehrfacheinträge werden beim Kopieren einer Stratigraphie ignoriert

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#331]
**Repro Steps:**
1. Ausgangsdatensatz mit Stratigraphie-Layer, bei dem Felder mit Mehrfacheiträgen gefüllt sind (USCS 3, Kornform, Kornrundung, ...)
2. Stratigraphie Klonen/Kopieren

**Erwartet:**
Alles wird dupliziert

**Beobachtet:**
Die Felder mit Mehrfacheinträgen werden nicht kopiert und sind leer. Die anderen Felder werden kopiert.

_Originally posted by @RBordoni in https://github.com/geoadmin/suite-bdms/issues/248#issuecomment-1384211161_

**Comment by RBordoni** [comment]
Testresultat Version 2.0.166:
Der Fehler ist für das Kopieren einer Stratigraphie behoben.

@danjov Hingegen tritt der gleiche Fehler auf beim Kopieren einer ganzen Bohrung.
Repro Step:
1. Ausgangsdatensatz mit Stratigraphie-Layer, bei dem Felder mit Mehrfacheiträgen gefüllt sind (USCS 3, Kornform, Kornrundung, ...)
2. Bohrung in Liste Selektieren
3. "Create a copy" anwenden

Beobachtet:
Die Stratigraphie wird kopiert, die Felder mit Mehrfacheinträgen sind aber leer.

**Comment by gysimichael** [comment]
funktioniert nun einwandfrei, danke!
