### ISSUE TITLE
White out bei Filterabfrage Location

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#345]
wenn man als nicht Admin einloggt, und eine Filter Abfrage bezüglich Standort tätigt:

erwartetes Verhalten:
Bohrungen werden Gefiltert

Beobachtetes Verhalten sowohl bei Viewer als auch Editor Modus:
white out

Bei Admin scheint diese Problem nicht vorzuliegen

**Comment by RBordoni** [comment]
@danjov Test Version Version: 2.0.172:
Beim Filtern erfolgt kein White Out mehr, hingegen beim anklicken einer Bohrung in der Liste. Auch wenn nicht gefiltert wurde.

Repro Steps:
1. Login mit Viewer Rechten
2. Eine beliebige Bohrung aus der Liste anklicken

**Comment by gysimichael** [comment]
sieht gut aus und funktioniert! Danke!
