### ISSUE TITLE
Selektions-Icon bei Viewer analog Editor anpassen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#348]
Das unschöne _Plus/Mnus_ soll zu einer Checkbox umgeändert werde, analog Editor-Liste.

![Image](https://user-images.githubusercontent.com/31883445/217532578-ba1502d5-fea2-494f-a025-0d15b6b528e3.png)

**Comment by MiraGeowerkstatt** [comment]
Wir mit der Umsetzung von #1154 obsolet.
