### ISSUE TITLE
Datei hochladen funktioniert auf Prod nicht

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#355]
Wenn ein pdf auf Prod hochgeladen werden soll:

Erwartetes Verhalten:
Datei kann ausgewählt werden, und nachdem man auf upload klickt, wird es hochgeladen

Verhalten:
Nachdem man die Datei ausgewählt hat, zeigt es an, das es lädt, jedoch stoppet diese Prozess ohne das Dokument als hochgeladen anzuzeigen

Ps. auf dev. funktioniert es

**Comment by danjov** [comment]
@gysimichael Ist das noch aktuell?

**Comment by gysimichael** [comment]
funktioniert nun bei mir, hat sich wohl mit einem andern bugfix behoben.
