### ISSUE TITLE
fehlende Fehlermeldung, wenn Profil schon im S3 Bucket vorhanden

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#360]
Wenn ein pdf schon einmal in den S3 Bucket geladen wurde, kann es nicht nochmals geladen werden

Erwartetes Verhalten:
Fehlermeldung beim Laden, das diese Datei schon existiert und nicht nochmals geladen werden kann

Verhalten:
Es gibt einem Vor, dass die Datei geladen wird, jedoch passiert nichts

**Comment by Lehats** [comment]
@gysimichael Es geht um die Fehlermeldung welche angezeigt werden soll.
Im screen shot findest du ein Beispiel von mir auf Deutsch. Ich wäre froh, wenn du mir passende Fehlermeldungen in den vier Sprachen zukommen lassen könntest.

![err_msg_file_uplaod](https://user-images.githubusercontent.com/37898460/223091512-8d931805-a8eb-4636-9141-42558d42ceb7.png)

**Comment by gysimichael** [comment]
Diese Datei wurde bereits für diese, oder eine andere Bohrung hochgeladen und kann nicht ein zweites Mal hochgeladen werden.

This file has already been uploaded for this or another borehole and cannot be uploaded a second time.

Ce fichier a déjà été téléchargé pour ce forage ou un autre forage et ne peut pas être téléchargé une deuxième fois.

Questo file è già stato caricato, per questa o una altra perforazione, e quindi non può essere caricato una seconda volta

**Comment by gysimichael** [comment]
das wären meine Vorschläge

**Comment by gysimichael** [comment]
Wäre richtig so, wie du sagst, jedoch ist das Zurzeit nicht so. Wenn das Dokument im S3 liegt, kannst du es nicht nochmals hochladen, noch erstellt es dir eine Verknüpfung, es macht einfach nichts

**Comment by gysimichael** [comment]
Wenn das gehen würde, wären die Meldungen folgendermassen:

Diese Datei wurde bereits für diese Bohrung hochgeladen und kann nicht ein zweites Mal hochgeladen werden.

This file has already been uploaded for this borehole and cannot be uploaded a second time.

Ce fichier a déjà été téléchargé pour ce forage et ne peut pas être téléchargé une deuxième fois.

Questo file è già stato caricato, per questa perforazione, e quindi non può essere caricato una seconda volta.

**Comment by gysimichael** [comment]
sehr gut gemacht, danke!
