### ISSUE TITLE
bei Leereinträgen im Viewer Modus fehlen die "-"

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#361]
Wenn mein Feldern, die kein Dropdown enthalten, keine Einträge enthalten sind, fehlen die "-", dies betrifft sowohl Zahlen wie auch Textfelder

**Comment by RBordoni** [comment]
Betrifft Formular für Borehole.

**Comment by gysimichael** [comment]
Für den unwahrscheinlichen Fall, dass man keine Koordinaten Setzt, fehlen noch die Striche.

![Image](https://user-images.githubusercontent.com/108096632/222788364-e5aa918b-3d9a-4f95-9b88-95ab2dfd92ec.png)

**Comment by gysimichael** [comment]
danke!
