### ISSUE TITLE
Error Message bei Location, Borehole und Settings (Manage ID types)

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#363]
Wenn man ohne Start Editing auf ein Feld click bei Borehole und Location, oder unter Settings Mange ID types:

Erwartetes Verhalten:

Fehlermeldung: You should press the 'start editing' button, auf die jeweilige gewählte Sprache

Verhalten:

Fehlermeldung: Borehole not locked, immer auf Englisch

**Comment by gysimichael** [comment]
Unter Settings -> Manage ID, wenn man einen Eintrag löschen will, kommt der Fehler: identifierDeletionAlreadyUsed, sieht aus als fehlen zu diesem Attribut die Übersetzungen. Könnte man die noch hinzufügen?

DE: Dieser ID Typ wird verwendet und kann daher nicht gelöscht werden
FR: Ce type d'ID est utilisé et ne peut donc pas être supprimé
IT: Questo tipo di ID è utilizzato e quindi non può essere cancellato
EN: This ID type is used and therefore cannot be deleted

**Comment by RBordoni** [comment]
Test Version 208: Settings -> Manage ID noch nicht gefixt.
