### ISSUE TITLE
DB Bereinigung GeODin

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#375]
Wurden folgende Attribute bewusst nicht gelöscht?

Layer:
- geodin_layer_id
- geodin_intv
- geodin_id

borehole:
-geodin_id

stratigraphie:
-geodin_id
-geodin_intv

Aus meiner Sicht können wir diese löschen, da wir mit GeODin durch sind

**Comment by Lehats** [comment]
@gysimichael Kannst du mir bitte etwas genauer beschreiben wo du diese Attribute gefunden hast? Oder vielleicht ein screen shot schicken? In der prod db?

**Comment by gysimichael** [comment]
ja in der Prod DB sehe Attachment

![bdms-schema-20230303](https://user-images.githubusercontent.com/108096632/228774980-dac387ba-b0ce-4c96-8b8b-f294534c315e.png)

**Comment by gysimichael** [comment]
@Lehats ruf mich doch kurz via Teams an, ist wohl einfacher

**Comment by Lehats** [comment]
Die Bereinigungen wurde am 03.04.2023 um ca 14 Uhr auf allen Umgebungen mit dem folgenden SQL script durchgeführt:

```sql
ALTER TABLE bdms.layer 
DROP COLUMN IF EXISTS geodin_layer_id;

ALTER TABLE bdms.layer 
DROP COLUMN IF EXISTS geodin_intv;

ALTER TABLE bdms.layer 
DROP COLUMN IF EXISTS geodin_id;

ALTER TABLE bdms.borehole 
DROP COLUMN IF EXISTS geodin_id;

ALTER TABLE bdms.stratigraphy 
DROP COLUMN IF EXISTS geodin_id;

ALTER TABLE bdms.stratigraphy 
DROP COLUMN IF EXISTS geodin_intv;
```
