### ISSUE TITLE
Instrumente Einträge nicht gespeicher

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#376]
Als normaler User Instrumente erfassen:

Erwartetes Verhalten:
Erfasste Einträge werden gespeichert

Verhalten:
Zellen für die Einträge werden generiert, jedoch beim wechseln eines Reiters sind alle Einträge leer (nicht sichtbar oder nicht gespeichert)

Ps. Als Admin funktioniert es einwandfrei

**Comment by gysimichael** [comment]
@danjov: Die Informationsabfrage ist relativ langsam hier, woher kommt das?

**Comment by danjov** [comment]
@gysimichael Vermutlich ist die Datenabfrage nicht optimal und müsste verbessert werden. Ich nehme an, dass hier viel zu viele Daten geladen werden, die es in diesem UI nicht braucht. Machst du ein Issue dazu auf oder soll ich?

**Comment by gysimichael** [comment]
Ist erfasst.
