### ISSUE TITLE
Workflow Message ein Sprachdurcheinander

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#378]
Wenn man im Workflow eine Weiterleitung macht:

Erwartetes Verhalten:
Das Popup ist in der Sprache, die man ausgewählt hat

Verhalten:
Das Popup enthält unterschiedliche Sprachen:
- Header ist generisch (weiss nicht, ob es vorgesehen oder hinterlegt war, dies in den verschiedenen Sprachen darzustellen)
- Nachfrage ist in der Richtigen Sprache
- Button ist in der richtigen Sprache
- Bei Veröffentlichung bei öffentlich kommt noch eine Zwischenziele auf Italienisch 
 

![Image](https://user-images.githubusercontent.com/108096632/218399056-4dc355f9-cfdf-478a-a1bc-559303eb37f1.png)

**Comment by Lehats** [comment]
@gysimichael 

Abhängig vom Status des Borehole werden folgende Werte im Header angezeigt:

"Change in Progress" => "Edit"
"Scientific check" => "Control"
"Validated" => "VALID"
"Publish" => "PUBLIC"

Es existiert keine Übersetzung für diese Begriffe, daher sind sie immer English.
Nun möchte ich dich fragen, ob das so okay ist oder ob wir andere Werte anzeigen sollen? Und ob man sie auch noch übersetzen sollte?

Die erwähnte Zeile auf Italienisch beim "Veröffentlichen" habe ich entfernt.

**Comment by gysimichael** [comment]
Die Bearbeitung ist abgeschlossen.
Die wissenschaftliche Prüfung ist abgeschlossen.
Die Validierung ist abgeschlossen.
Die Bohrung wird publiziert.

La modification est terminée.
Le contrôle scientifique est terminé.
La validation est terminée.
Le forage va être publier.

La redazione è stata completata.
Il controllo scientifico è completato.
La validazione è completata.
La perforazione sarà pubblicata.

The processing is completed.
Scientific check is completed.
The validation is completed.
The borehole will be published.

**Comment by gysimichael** [comment]
Ich würde Vorschlagen, das es wohl sinnvoller ist, hier diese Texte anzuzeigen

**Comment by gysimichael** [comment]
also die englischen Begriffe mit diesen Sätzen ersetzten

**Comment by gysimichael** [comment]
Top Umsetzung! Vielen Dank!
