### ISSUE TITLE
Profilgenerator funktioniert nicht

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#380]
Im Viewer Modus, entweder auf plus klicken und dann Profildownload, oder im Header über dem Profil auf Produktdownload klicken:

Erwartetes Verhalten:
PDF vom generischen Profil wird erstellt und heruntergeladen

Verhalten:
abgesehen dass das Download Icon erscheint, passiert nichts
siehe Bohrung XXX

**Comment by gysimichael** [comment]
Ist immer noch was nicht richtig. Gewisse Bohrungen gehen nun, andre generieren ein PDF, dass sich aber nicht öffnen lässt, bspw. Bohrung Bülach

**Comment by danjov** [comment]
@gysimichael Das ist ein Folgefehler von #454 und hat nichts (mehr) mit dem Profilgenerator zu tun. Sobald der Fix für #454 da ist, sollte der Profilgenerator wie erwartet für alle Bohrungen funktionieren.

**Comment by gysimichael** [comment]
@danjov : da ist irgendwie der Wurm drin, Bohrung Trüllikon-1-1 und Bülach-1-1 geht weiterhin nicht, das Files ist 1KB gross

**Comment by gysimichael** [comment]
bei anderen Bohrungen hingegen geht es... Komme nicht nach

**Comment by danjov** [comment]
@gysimichael Bei den Bohrungen Trüllikon-1-1 und Bülach-1-1 sind Fehler in den Stratigraphien drin und deshalb funktioniert der PDF-Export nicht. Das betrifft nur die Dev-Umgebung, da wir dort mit den Daten getestet haben. Beispiel Bülach:
![buelach-strati-fehler](https://user-images.githubusercontent.com/8969524/221542835-acec9768-d3e1-41e6-a7b5-45d4b6f1086d.png)

Ich habe den Fehler auf Dev bereinigt und nun funktioniert der Export bei Bülach.

**Comment by gysimichael** [comment]
ok! na dann :-). Danke fürs Detektiv spielen
