### ISSUE TITLE
Lithology Description kann als Editor nicht gespeichert werden

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#383]
Aus Mail Michael Gysi 13.02.2023

User mit Editor Rechten aber nicht als Admin definiert

Beobachtet:
- Lithological Desription kann mit dem Stift bearbeitet werden. Beim erneuten Klick auf den Stift wird aber nichts gespeichert.
- Ebenso können keine neuen Schichten eingefügt oder bestehende gelöscht werden

**Comment by gysimichael** [comment]
als admin geht es

**Comment by gysimichael** [comment]
funktioniert bei mir nicht.

**Comment by gysimichael** [comment]
Ich kann hier als Normaluser  nichts ändern

**Comment by gysimichael** [comment]
Der Add Button geht nicht

**Comment by RBordoni** [comment]
Stimmt. Eine bestehende kann ich editieren aber eine neue nicht anlegen. Add-Button geht nicht.

**Comment by gysimichael** [comment]
Funktioniert! Danke!
