### ISSUE TITLE
Editierstart durch Klick auf Feld, nicht nur auf Bleistift

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#385]
Aus Mail Michael Gysi 13.02.2023

Wenn man auf das Feld klickt, sollte diese sich editieren lassen, nicht nur wenn man auf das Bleistift klickt

**Comment by RBordoni** [comment]
Test Version 2.0.199: Funktionalität viel besser!

Eine  Fehler bleibt. Beim Wegklicken von einer Lithological description zur anderen werden die Eingaben richtigerweise gespeichert. Beim Wegklicken von einer Lithological description zu einer Lithology fälschlicherweise nicht.

**Comment by gysimichael** [comment]
Top, vielen Dank, funktioniert super.
