### ISSUE TITLE
Stapel der Lithology Description rutscht hoch wenn oberste Teufe nicht passt

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#387]
Aus Mail Michael Gysi 13.02.2023
- Wenn man bei der Lithology Description als erster Eintrag 20-40 macht und 0-20 keinen Eintrag hat, wird er von 0 bis 20 angezeigt
- Wenn die oberste Schicht der Lithology Description gelöscht wird, rückt alles nach oben, scheint nicht an die Teufen gebunden zu sein, respektive nicht mit der Lithologieteufen gelinkt

**Comment by gysimichael** [comment]
perfekt, vielen Dank!
