### ISSUE TITLE
Falsche Rückmeldung bei Überlappungen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#389]
Aus Mail Michael Gysi 13.02.2023

Bei Überlappung kommt die falsche Rückmeldung und nicht an der richtigen Position. Solle wie bei Lithologie heissen, das eine Überlappung vorliegt und an spezifischen Ort angezeigt werden

**Comment by gysimichael** [comment]
Lösung suboptimal, denn wenn man zwei Einträge hat, und die Teufe falsch, muss man den einen Eintrag löschen, um die Teufe beim andern zu ändern...

Aus meiner Sicht besser wäre, eine Überlappung zuzulassen, und dann wie bei der Lithologie, auf den Überlappung hinzuweisen

![image](https://user-images.githubusercontent.com/108096632/218979275-6d60da67-3a45-4703-b53f-34f8a3c03681.png)

**Comment by gysimichael** [comment]
Zusätzlich lässt ich immer noch ein Schichtlücke erstellen, mit falscher Fehlermeldung:


![Image](https://user-images.githubusercontent.com/108096632/218980339-5d255e47-cba2-4082-8539-5b9db39baa5b.png)

Erstellte 4 Einträge, lösche die zwei mittleren, und generiere mit den Verbleibenden eine Überlappung

**Comment by gysimichael** [comment]
DANKE!
