### ISSUE TITLE
Scrollen bei Neueinträgen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#392]
Aus Mail Michael Gysi 13.02.2023

Wenn man neue Lithologiebeschreibung erstellt, sollte es gleich zum Eintrag scrollen, oder als pop up erscheinen. Bei vielen Einträgen ist das verwirrend, respektive man merkt nicht, ob ein neuer Eintrag erstellt wurde oder nicht.

**Comment by RBordoni** [comment]
Test Version 2.0.199: Funktioniert. Eine Unschönheit besteht → separates Issue #419

**Comment by gysimichael** [comment]
cool vielen Dank!

@MiraGeowerkstatt:
Wäre es möglich das auch bei Stratigraphie Lithologie und bei Completion bei Casing und Backfill auch zu inkludieren?

**Comment by gysimichael** [comment]
funktioniert, danke!
