### ISSUE TITLE
UI Stratigraphie, optische Verbindung nicht mehr klar

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#397]
Die Lithologie war früher mit einem grauen Band mit dem Detailformular verbunden. Das war besser, jetzt fehlt der optische Zusammenhang.
Gilt für beide Zustände: Editing started und Editing stopped.

![Image](https://user-images.githubusercontent.com/31883445/218488202-ff037ee1-8941-4e6f-b788-3e460940c78a.png)

**Comment by MiraGeowerkstatt** [comment]
Tritt mit Änderungen in #384 nicht mehr auf.

**Comment by gysimichael** [comment]
cool, danke!
