### ISSUE TITLE
SMTP-Konfiguration für Feedbacks überprüfen/integrieren

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#4]
| Environment| Domain | State
| :--- | :--- | ---: |
| dev | [dev.swissforages.ch](https://dev.swissforages.ch/) | boreholes.swissgeol@swisstopo.ch ✅ |
| prod| [swissforages.ch](https://swissforages.ch/) | swissforages@swisstopo.ch ✅ |
| dev | [dev.boreholes.swissgeol.ch](http://dev.boreholes.swissgeol.ch/) | not yet available |
| test | [test.boreholes.swissgeol.ch](http://test.boreholes.swissgeol.ch/) |boreholes.swissgeol@swisstopo.ch ✅ |
| prod| [boreholes.swissgeol.ch](http://boreholes.swissgeol.ch/) | not yet available |

**Comment by flenny** [comment]
Umgebungs-Identifier (DEV/TEST/PROD) im Betreff der E-Mail ergänzen.

**Comment by danjov** [comment]
Feedbacks sollen nicht mehr in der DB abgelegt werden.

**Comment by danjov** [comment]
Neue E-Mail Adresse für Feedbacks verwenden: boreholes.swissgeol@swisstopo.ch

**Comment by flenny** [comment]
> Feedbacks sollen nicht mehr in der DB abgelegt werden.
Da der Versand der E-Mails aktuell über "DB-Hooks" umgesetzt ist, wird vorerst darauf verzichtet die entsprechende Tabelle `feedbacks` zu bereinigen. Sinnvollerweise würde der E-Mail Versand dann direkt auf der neuen API (v2) umgesetzt.

**Comment by flenny** [comment]
Kann erst dann sinnvoll umgesetzt werden, wenn alle Umgebungen neu installiert wurden. DEV und Prod sind aktuell noch ausstehend.
