### ISSUE TITLE
Lithology Description im Normal Modus funktioniert nicht

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#402]
Editieren der Lithological description im als Normaluser:

Erwartetes Verhalten:
Die Kacheln können bearbeitet werden

Verhalten:
Die Kacheln können nicht bearbeitet werden

**Comment by RBordoni** [comment]
Dies scheint sich gelöst zu haben. Ansonsten bitte angeben, welche Roles und Workgroups beim "Normaluser" eingestellt sind.

**Comment by gysimichael** [comment]
geht auch bei mir!
