### ISSUE TITLE
Lithologie Feld im Editor Anpassen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#406]
Mit den Änderungen unter Stratigraphie müsste man im Lithologie Feld folgende Anpassungen machen:

Ist Zustand:

![Image](https://user-images.githubusercontent.com/108096632/218981796-684789eb-f545-4739-acad-870dd1840c1a.png)

In der Lithologie werden folgende Infos Angezeigt, ohne das Popup zu öffnen:

- Tiefe Oberkante
- Lithostratigraphie
- Chronostratigraphie
- Lithologie
- Tiefe Unterkante

Zukünftig werden ja in dem Popup folgende Felder gelöscht:

- Lithologische Beschreibung
- Fazielle Beschreibung
- Lithostratigraphie
- Chronostratigraphie

**Comment by gysimichael** [comment]
Mit der  Neuentwicklung sollten folgende Infos Angezeigt werden:

- Tiefe Oberkante
- Lithologie, USCS1, Konrgrösse 1, USCS2, Konrgrösse 2, USCS3, Kornform, Kornrundung, Organische Komponenten, Grobbestandteile, Striemung (wenn ja Striemung schreiben, sonst weglassen), Farbe, Konsistenz, Plastizität, Lagerungsdichte, Kohäsion, Abstufung, Feuchtigkeit, Alteration, Anmerkungen
- Tiefe Unterkante

Somit sollten alle Attribute vom Pupup, ausser:
- Bohrlochende
- Qualität der Beschreibung
- Ursprüngliche Lithologie
- USCS Originalklassifikation
- USCS Bestimmungsmethode

Aufgelistet werden.

Ich habe mir das so vorgestellt:
- Liste alle Einträge, durch ein "Koma" getrennt, nacheinander auf (wie eine Aufzählung). Falls der Wert "NULL" oder "Keine Angaben" enthalten ist, wird der Wert inkluisve "Koma" weggelassen.
- Bei Striemung würde man falls Eintrag "Ja" wäre, "Striemung" schreiben, bei "Nein" oder "Keine Angabe" den Eintrag, inklusive "Koma" weglassen

**Comment by RBordoni** [comment]
Anmerkung aus Sitzung 15.02.2023: Es ist immer der ganze String anzuzeigen. Unabhängig welche Felder in Settings ausgeblendet sind.

**Comment by RBordoni** [comment]
Anmerkung aus Sitzung 22.02.2023: 

- Feld "Anmerkungen" auch weglassen und nicht anzeigen
- Keine Label anzeigen, nur Feldinhalte (Kommagetrennt)

**Comment by MiraGeowerkstatt** [comment]
Hier wäre mein Vorschlag.

Ich habe die Liste in zwei Teile geteilt, damit es etwas Struktur gibt und optisch zu den anderen Spalten (die auch Titel (fett) und Untertitel haben) passt.



![Image](https://user-images.githubusercontent.com/49144408/220924388-ac03d285-2ce7-4c9d-97c8-95ee6f0ac592.png)

**Comment by gysimichael** [comment]
Sieht gut aus, denke Lithologie, USCS1, Körngrösse 1 und Farbe sollte Fett sein, alles andere dann darunter.

Das mit den Punkten finde ich eine sehr gute Lösung.

**Comment by gysimichael** [comment]
@MiraGeowerkstatt: Sieht seht gut aus! Könnte man noch alle "Keine Angaben" ausblenden? Das anzuzeigen generiert keinen Mehrwert. Sonst super umgesetzt

**Comment by gysimichael** [comment]
Echt toll, danke für die Umsetzung. Jetzt sieht es super aus; Danke!
