### ISSUE TITLE
Stratigraphie und Ausbau zeigt 0

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#410]
![Image](https://user-images.githubusercontent.com/108096632/219062410-9dcd0b3d-ae85-4f23-b0c8-c378fd686e38.png)

Unter dem + Button und der Linie wird eine "0" angezeigt, braucht es diese oder wäre es nicht besser, diese gleich weg zu lassen?
Wenn man den + Button klickt, erscheint ja sowieso das erste Feld mit 0

**Comment by RBordoni** [comment]
Hat sich im Rahmen andere Anpassungen erledigt.
