### ISSUE TITLE
Stratigraphie und Ausbau + Button Balken überlagert Kalender Popup

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#411]
![Image](https://user-images.githubusercontent.com/108096632/219063532-88e1f2b0-7c24-4601-80d0-09e8e910a184.png)

Kalender Pupup verschwindet hinter dem + Button

**Comment by RBordoni** [comment]
Test RB Version: 2.0.214: Das ist immer noch so

**Comment by gysimichael** [comment]
jetzt ist's gut! Danke!
