### ISSUE TITLE
Änderungen an geolcodes oder Übersetzungen direkt in GitHub oder in der Applikation

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#42]
Änderungen an den geolcodes oder an Übersetzungen sollen weiterhin direkt in GitHub oder in der Webapplikation vorgenommen werden können.

Siehe https://github.com/geoadmin/doc-bdms/tree/master/i18n

**Comment by danjov** [comment]
Die Übersetzungen des UIs können weiterhin direkt in GitHub editiert werden. Unter https://github.com/geoadmin/suite-bdms/tree/main/src/client/public/locale kann pro Sprache die Übersetzung im jeweiligen Ordner und `common.json`-File angepasst werden. Der Umweg über das [web-bdms-translations.csv](https://github.com/geoadmin/doc-bdms/blob/master/i18n/web-bdms-translations.csv)-File entfällt.

**Comment by danjov** [comment]
Idee: Die geolcodes, sprich die Einträge aus der Tabelle `codelist`, sollen mittels einem UI, welches nur für Admins zur Verfügung steht, editiert werden können.

**Comment by RBordoni** [comment]
Anforderungen Geolcodes aus Besprechung 04.10.2022:
- Der jetzige Bereich "Manage identifiers" kann in den Bereich "Codelist translation" verschoben werden (wie jetzt bereits sichtbar aber noch ohne ADD und DELETE). Als einzelständiger Bereich fällt er weg.
- Der jetzige Bereich "Manage identifiers" ist der einzige, mit ADD und DELETE
- Die Bezeichnungen der Gruppen sind anzupassen. Michael sendet uns diese Woche eine Liste für die Beschriftung. Die Begriffe werden im BDMS fix gespeichert.
- Die Nummern der Geolcodes sind einzublenden, ohne Editiermöglichkeit.
- Für das bessere handling soll eine innere Scrollbar erstellt werden, so dass die Eingabezeile immer sichtbar bleibt. Alternative: In Line Editing in der Zeile mit Fokus.

**Comment by RBordoni** [comment]
Planänderung zu den IDs: 
Im Rahmen der Vereinfachung des Datenmodells ist es sinnvoller die IDs nicht in der Tabelle _Codelist_ zu führen. Die IDs sind im Verhalten anders als reine Codes. 
Konsequenzen:
- Das führen der Verbindungstabelle borhaole_codelist entfällt.
- Das UI für die Editierung der ID bleibt separat. Der jetzige Bereich "Manage identifiers" wird _nicht_ in den Bereich "Codelist translation" verschoben.

**Comment by RBordoni** [comment]
Besprechung 25.10.2022:
- Die überflüssigen können gelöscht werden
- Wie die neuen Begriffe in der Applikation/DB verankert werden, dazu überlegt sich die GeoWerkstatt die passendste Lösung. Kann auch später umgesetzt werden
- Die IDs sollen wie oben beschrieben nicht mehr in den Geolcodes geführt werden.

**Comment by MiraGeowerkstatt** [comment]
Zum Löschen von "borehole_form" die Werte werden derzeit noch für die "Mention" Funktion in der Kommentarbox gebraucht.

Mittels @ kann man einen Wert auswählen und der Wert wird dann hervorgehoben dargestellt. 
Wir müssten abklären ob man das noch gebraucht wird.

![Image](https://user-images.githubusercontent.com/49144408/199747987-c6f88998-dcbe-42b1-8d31-a370dd84eedb.png)

![Image](https://user-images.githubusercontent.com/49144408/199748689-80727dde-01fe-4cd8-92e8-d34b9d3bb1c8.png)

**Comment by gysimichael** [comment]
Funktioniert sehr gut, habe auch schon ein paar Sachen nun geändert und hat bestens funktioniert, einzig die Reihenfolge der Geolcodes scheint nicht immer mit der Reihenfolge der DropDowns übereinzustimmen

**Comment by RBordoni** [comment]
@gysimichael Wir finden den Input gut. Ich habe dazu zwei Issues erfasst, damit sie mal parkiert sind:
→ #201 Sortierfeld für GeolCodes editierbar machen
→ #202 GeolCodes im Admin Bereich sortiert anzeigen
