### ISSUE TITLE
Lithological und Facies Desription aus Lithology entfernen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#430]
To Do:

- Lithological und Facies Desription aus dem UI der Lithology entfernen.  (Temporär in DB noch beibehalten)
- Im Viewer ebenfalls. Die Descriptions sind dort nicht mehr sichtbar.
- In den Settings sind die Filteroptionen und Einblendoptionen anzupassen

**Comment by gysimichael** [comment]
Sieht gut aus, danke!

**Comment by RBordoni** [comment]
Quality of the description ist meiner Meinung nach auch zu entfernen.


![Image](https://user-images.githubusercontent.com/31883445/221497794-1c435785-7632-48ad-91df-b0ac9a0f3161.png)

**Comment by gysimichael** [comment]
@RBordoni : soll bleiben, gibt die Qualität der Beschreibung anhand der Attribute wieder.
