### ISSUE TITLE
GeolCodes Übersetzung Korrigieren

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#44]
Bei:

23101032	mcla101	kunst	künstlich Auffüllung

sollte es "künstliche Auffüllung" heissen.

**Comment by RBordoni** [comment]
Codeanpassungen erst nach Import GeODin

**Comment by gysimichael** [comment]
da es hier nur um die Übersetzung geht, kann dies angepasst werden, auch wenn GeODin noch nicht bereit ist

**Comment by gysimichael** [comment]
sieht gut aus
