### ISSUE TITLE
Schichtlücken Check -> whiteout

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#440]
Wenn eine Lithologie gelöscht wird und man eine Funktion ausser "Bestehende Schicht löschen" wählt:

Erwartetes Verhalten:
Die Funktion wird fehlerfrei ausgeführt

Verhalten:
whiteout, jedoch nach restart wurde die Funktion richtig ausgeführt

PS. Bei Überlappung scheint es zu funktionieren

**Comment by RBordoni** [comment]
Ergänzung RB: Ist etwas schwierig zu reproduzieren. Bei mir erfolgt der Whiteout nicht sofort, erst beim mehrmaligen an- und wegklicken des geänderten Lithologie-Layers

**Comment by gysimichael** [comment]
Funktioniert, Danke!
