### ISSUE TITLE
DB Korrektion Koordinaten

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#448]
Gestern haben meine Leute festgestellt, das von Projekt GeoQuat die Mehrheit der Bohrungen doch in LV95 waren....

Könnte man die Excelliste auf Teams (Coordinates to change.xlsx) für diese Bohrungen die LV03 Koordinaten und LV95 Koordinaten löschen und die Koordinaten im Excel als LV95 einfügen?

Vielen Dank

**Comment by danjov** [comment]
Die Koordinaten wurden am 28.02.2023 08:10 Uhr auf allen Umgebungen anhand der Excel-Liste ersetzt. Die automatische Berechnung der LV03-Koordinaten anhand der Ausgangskoordinaten in LV95 wurde ebenfalls ausgeführt. Das verwendete SQL-Skript wurde in Teams abgelegt.

**Comment by gysimichael** [comment]
Danke
