### ISSUE TITLE
User löschen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#45]
Diese User lassen sich nicht löschen, könnte man dies im Backend vornehmen?

![Image](https://user-images.githubusercontent.com/108096632/189601999-762d0168-3d91-462b-96c7-b3955f624ce8.png)

**Comment by danjov** [comment]
Diese User lassen sich nicht löschen, da sie noch Referenzen zu Files/Attachements, Workflows und Feldern zur Rückverfolgbarkeit haben. Unser Vorschlag wäre ein _Soft-Delete_ für die User-Tabelle einzuführen, so dass ein Eintrag als gelöscht in der DB markiert anstatt komplett gelöscht wird. So entsteht kein Datenverlust und als gelöscht markierte User könnten wir im obigen UI ausblenden.

**Comment by gysimichael** [comment]
finde ich einen guten Ansatz

**Comment by RBordoni** [comment]
Besprechung 25.10.2022:
- Funktionalität so belassen, kein weiterer Soft-Delete
- Meldung ausbauen:
   - Wenn keine Bohrung vorhanden ist, aber andere Verbindungen (Attachments, ...) schon, dann erscheint heute keine Meldung → Meldung einbauen
   - In Meldung, dass nicht gelöscht werden kann auch Attachments, etc, aufführen
- Die 4 User St.Gallen, test, testVD, ZH_AWEL-Toth löschen

**Comment by danjov** [comment]
Die vier User _St. Gallen_, _test_, _test_VD_ und _ZH_AWEL-Toth_ wurden am 26.10.2022 08:15 Uhr aus der produktiven Datenbank gelöscht.
