### ISSUE TITLE
Cluster in Kartendarstellung beim Rauszoomen nicht vollständig

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#465]
Repro Steps:

1. Ausgangslage: Editor, Karte ganze Schweiz
2. mehrmals einen Cluster anklicken bis Darstellung von Cluster zu Bohrungen wechselt (filter by map wird dabei eingeschaltet)
3. eine Bohrung anklicken
4. Zurück zur Liste mit "Done"
5. Mit Mausrad rauszoomen

Beobachtet: Es wird nur ein Cluster angezeigt, obwohl kein anderer Filter gesetzt ist.

![Image](https://user-images.githubusercontent.com/31883445/220939008-840c6ea7-0b53-4d34-a99a-0aecd72f7e55.png)

Hat evtl. mit #188 zu tun

**Comment by RBordoni** [comment]
Momentan wird bei einem Klick auf einen Cluster im Editor-Modus automatisch "Filter by Map" eingeschaltet, im Viewer-Modus nicht. Das Verhalten soll bei beiden gleich sein, so wie im Editor. → Anpassen

**Comment by gysimichael** [comment]
Wenn ich ein Filter einstelle werden die Punkte auf der Karte reduziert, jedoch, wenn ich auf zurücksetzten klicke, bleibt die Auswahl auf der Karte erhalten, obwohl die Totalbohrung viel höher ist.

**Comment by gysimichael** [comment]
jetzt kann ich es nicht mehr reproduzieren, also gehen wir mal davon aus, es funktioniert :-)
