### ISSUE TITLE
Mehrfachbearbeitung Workgroup Einbauen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#469]
Um die Möglichkeit zu haben, Bohrungen zuwischen Workgroups zu verschieben, wäre es gut, wenn man bei der Mehrfachbearbeitung eine Option einfügen könnte, welche erlaubt, die Workgroup zu ändern

**Comment by RBordoni** [comment]
Anmerkung RB: Ist als zusätzliches Feld im Bulk editing drin.

**Comment by gysimichael** [comment]
Vielen Dank, funktioniert bestens!
