### ISSUE TITLE
Cookie “i18next”

### ISSUE THREAD

**Issue by mantonovic** [geoadmin/suite-bdms#47]
Investigate further this message from dev console:

Cookie “i18next” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite.

**Comment by danjov** [comment]
Abklären, ob das noch aktuell ist.

**Comment by danjov** [comment]
Die Meldung erscheint nicht mehr in der Konsole.
