### ISSUE TITLE
Separate Darstellung von Chronostratigraphy im Editor Modus.

### ISSUE THREAD

**Issue by patrickackermann** [geoadmin/suite-bdms#471]

**Comment by gysimichael** [comment]
Sieht aus meiner Sicht super aus, danke für die Umsetzung.
Es gibt noch diverse Sachen, die man als Konsequenz anpassen muss, habe diese mal Separat erfasst.
Denke ist sinnvoller, als alles hierher zu packen.

**Comment by RBordoni** [comment]
@gysimichael Bitte noch nicht testen, siehe Anmerkung im Chat. Es wird in Kürze anders aussehen, wenn die anderen Issues fertig sind, die in Progress sind.
