### ISSUE TITLE
Label "Transparenz" in Karten Settings immer auf italienisch

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#483]
Sowohl in der Viewer-, als auch in der Editor-Karte sind die Slider immer auf italienisch angeschrieben.

![Image](https://user-images.githubusercontent.com/31883445/222120385-f2986679-8127-4639-83a1-ec5050d46d7c.png)

**Comment by gysimichael** [comment]
bis jetzt nie gespotted; nice catch. 

Vielen Dank für die Umsetzung
