### ISSUE TITLE
Chronostratigraphie Tabelle importieren

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#484]
Neuste Chronostratigraphie Daten einlesen.
Neuste Tabelle mit Farbcodes:
\\KD755036\Projekte\swisstopo\BDMS\Konzeption\Stratigraphie\C3_Chronostratigraphie_2023.xlsx

**Comment by gysimichael** [comment]
das macht es bedeutend besser, und vereinfacht die Lesbarkeit! Danke

**Comment by gysimichael** [comment]
habe noch einen Fehler gefunden, könnte man diesen Eintrag noch anpassen (also Farbcode ändert):
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/U80864~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/U80864~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



115 | 5_Epoche | 15001124 | Mississippien | Mississippien | Mississippiano | Mississippian | 15001119 | 103,143,102
-- | -- | -- | -- | -- | -- | -- | -- | --




</body>

</html>

**Comment by gysimichael** [comment]
Weiter wäre noch eine Erweiterung Sinnvoll, wenn ich es im Gesamten anschaue:

Bei diesen zwei müsste man nur die Hirarchie anpassen:

15001015 | Plaisancien | Plaisancien | Piacenziano | Piacenzian | 255,255,191 | 15001001.15001002.15001013.15001014.30000312.15001015
15001016 | Zancléen | Zancléen | Zancleano | Zanclean | 255,255,179 | 15001001.15001002.15001013.15001014.30000313.15001016

Diese zwei müsste man neu erfassen:

30000312 | Spätes Pliozän | Pliocène tardif | Tardo Pliocene | Late Pliocene | 255,255,153 | 15001001.15001002.15001013.15001014.30000312
30000313 | Frühes Pliozän | Pliocène précoce | Primo Pliocene | Early Pliocene | 255,255,153 | 15001001.15001002.15001013.15001014.30000313

**Comment by gysimichael** [comment]
Vielen Dank, das ist gut so!
