### ISSUE TITLE
Stratigraphy Edit Menu anpassen

### ISSUE THREAD

**Issue by patrickackermann** [geoadmin/suite-bdms#486]
_Lithology_ und _Chronostratigrapyh_ sollen als Untermenu von _Stratigraphy_ dargestellt werden ähnlich wie es beim Casing ist.

**Comment by RBordoni** [comment]
Testresultat Version: 2.0.246:

Repro Steps:
1. Editor Modus
2. Menupunkt Stratigraphy anklicken und Aufklappen
3. Direkt Chronstratigraphy anklicken (bevor man auf Lithology klickt)

Beobachtet:
Die Chronostratigraphy wird nicht vollständig angezeigt 

![Image](https://user-images.githubusercontent.com/31883445/223131829-aae0f776-ada5-414a-8ef5-6f716c19e314.png)

wenn man danach  Lithology anklickt und wieder zurück zur Chrono klickt, ist es richtig angezeigt 


![Image](https://user-images.githubusercontent.com/31883445/223132009-49ab4fdf-8e41-4b56-aa24-275a10dde4ae.png)

**Comment by gysimichael** [comment]
siehe Kommentar bei #694, somit hiermit abgeschlossen.
