### ISSUE TITLE
Technische ID jeder Bohrung Anzeigen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#497]
Technische ID unter Standort ID Anzeigen, sowohl im Viewer als auch im Editor

ID Typ: ID boreholes.swissgeol.ch
ID Code: id_bho

Vorschlag: 
Variante 1: Diese ID unter 100'000'001 zu hinterlegen, sprich kleines Skript schreiben, welches die id_bho in die borehole_codelist mit Code 100'000'001 schreibt
Variante 2:  Da dieser Wert ja eh in der borehole_codeliste abgespeichert wird, diesen immer als Default bei ID Code anzeigen, und bei ID Type "ID boreholes.swissgeol.ch" anzeigen

100'000'001 und 100'000'002 gibt es nicht, dies nicht aus technischen Gründen, sondern da ich am Anfang hier rumgespielt hatte (und nicht wusste, was ich tat :-)), daher kann man dies gut so machen, ohne Probleme zu verursachen. Ich bin mir bewusst, dass man die eigentlich nicht tut, aber hier stellt es kein Problem dar :-)

unter 100'000'002 könnte man noch einen neuen Code einführen für das Kernlager:

ID Kernlager, ID Core storage, ID Dépôt de carottes, ID Magazzino di carote

**Comment by danjov** [comment]
Die technische ID (`id_bho`) soll zusammen mit den anderen IDs mit dem Typ `ID boreholes.swissgeol.ch` angezeigt werden. Für die technische ID wird kein separater Eintrag in der Codeliste erstellt.

**Comment by gysimichael** [comment]
@danjov  Habe den Eintrag bezüglich Kernlager gemacht, hier der Aktuelle Stand (muss wohl auch noch beim Import angepasst werden):



![Image](https://user-images.githubusercontent.com/108096632/226954245-8c044166-3c3f-4fc8-b003-703dfce4ca37.png)

**Comment by RBordoni** [comment]
Test Version 2.0.360: So weit so gut, aber die Darstellung im Viewer ist nicht optimal. Wenn viele ID vorhanden sind stossen wir so oder so auf Platzmangel. Daher lieber wie vorher untereinander.

Jetzt:


![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/a072bffb-4b7a-4c8c-b09b-e5c343330cff)

Vorher:


![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/759b04f3-65de-4c59-a209-e08b2794ca61)

**Comment by Philippluca** [comment]
Notiz für den fix:  Ist: `flex-direction: row`  Soll: `flex-direction: column`

**Comment by gysimichael** [comment]
@Philippluca Auf Englisch sollte ID am Schluss stehen, um konsistent mit den anderen IDs zu sein, könnte man das noch ändern? Sonst sieht es gut aus.

**Comment by danjov** [comment]
@MiraGeowerkstatt Kannst du das übernehmen? Danke

**Comment by gysimichael** [comment]
Ist nun in Ordnung, danke!
