### ISSUE TITLE
Completness in DB

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#498]
Die Tabelle "completness" braucht es glaube ich nicht, respektive sehe ich nicht eine Umsetzung, welche diese Tabelle braucht. Sollte man diese, falls nicht gebraucht, nicht besser abräumen?

**Comment by Lehats** [comment]
@gysimichael Ich habe nachgeschaut. Es handelt sich bei _completness_ um eine sql view, welche in diversen sql commands im alten API gebraucht wird. Daher können wir diese view nicht in absehbarer Zeit entfernen. Was sollen wir nun mir diesem Issue machen?

**Comment by gysimichael** [comment]
@Lehats einfach lassen und ins backlog verschieben

**Comment by gysimichael** [comment]
Ja, respektive hat es bis jetzt nicht gefehlt, somit ist es wohl sinnvoll, hier aufzuräumen

**Comment by gysimichael** [comment]
Ihr könnt das wohl am besten entscheiden, was hier sinnvoll ist.

**Comment by danjov** [comment]
Wir werden die View und den dazugehörigen Code abräumen, da er nicht verwendet wird.

**Comment by gysimichael** [comment]
das kann ich wohl kaum selber prüfen, somit vertraue ich auf Eure Arbeit im Backend :-)
