### ISSUE TITLE
Settings Einstellung nur als Viewer

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#502]
Wenn man nur die Viewer Berechtigungen hat, kann man in den Settings die Einstellungen nur als Viewer machen. Da man aber trotzdem in den Editor Bereich kommt, ohne was zu ändern zu können, wäre es gut, wenn man unter Settings die gleichen Einstellungsmöglichkeiten hätte, wie der Editor und so seine Filter und Stratigraphie-Felder anpassen kann.

Somit sollten dies für alle Profile so eingestellt werden, sprich View, Controller, Validator und Publisher

**Comment by gysimichael** [comment]
@danjov : habe es nochmals geprüft, wir haben hier 3 Modi:
Admin: kann alles ändern, somit Vierer, Editor, Admin, Terms of service und Login screen
Editor: Kann in Viewer alles einstellen, im Editor, ausser "Manage ID types" und "Codelist translation" auch alles Anpassen
Viewer, Controller, Validator und Publisher: können nur im Viewer Einstellungen machen

Aus meiner Sicht sollte man die Option Viewer gar nicht anbieten und für alle, ausser Admin, die Editor Einstellungen bei Settings machen können. 

Wäre gut, wenn man dies noch vor dem Deploy umsetzten könnte, weil bei der swisstopo die Mehrheit als Viewer agieren werden.

Oder übersehe ich das was?

**Comment by danjov** [comment]
@gysimichael Nein, ich denke du hast alle Punkte korrekt erfasst und nichts übersehen. Wir werden diesen Punkt entsprechend priorisieren.

**Comment by gysimichael** [comment]
@danjov : Dein Vorschlag mach so sin und kann ausgeführt werden.

**Comment by gysimichael** [comment]
funktioniert, danke!
