### ISSUE TITLE
Chronostratigraphie Ersteintrag

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#503]
Wenn noch keine Lithologie respektive Chronostratigraphie Erfasst wurde, sollte die Chronostratigraphie leer sein mit der Message:

Wenn man nicht Editiert:

Kein Chronostratigraphieprofil verfügbar
Aucune profil chronostratigraphie disponible
Nessuno profilo cronostratigrafia disponibile
No chronostratigraphic profile available

Wenn man Editiert:

Für die Erfassung eines Chronostratigraphieprofils bitte das Plus-Symbol oben links klicken
Pour l'enregistrement d'un profil chronostratigraphie veuillez cliquer sur le symbole dans le coin supérieur gauche
Per la registrazione di un profilo cronostratigrafia cliccare il pulsante con il simbolo in alto a sinistra
For the recording of a chronostratigraphic profile please click the plus symbol at the top left

Der Knopf oben Rechts sollte mit:

Chronostratigraphieprofil
Profil chronostratigraphie
Profilo cronostratigrafia
Chronostratigraphy profile

beschriftet sein.

Falls man eine Stratigraphie erstellen will, bevor eine Lithologieprofil erstellt hat, sollte eine Fehler Meldung kommen:

Sie sollten zuerst ein Lithologieprofil erstellen, bevor Sie ein Chronostratigraphieprofil erstellen können
Vous devez d'abord créer un profil lithologique avant de pouvoir créer un profil chronostratigraphique
Prima di creare un profilo cronostratigrafico è necessario creare un profilo litologico
You should first create a lithology profile before you can create a chronostratigraphy profile

Der Slider sollte mit:

Dies ist das Hauptchronostratigraphieprofil
Ceci est le profil chronostratigraphie principale
Questo è il profilo cronostratigrafia principale
This is the main chronostratigraphy profile

beschriftet sein

**Comment by MiraGeowerkstatt** [comment]
Chronostratigraphieprofile können nicht unabhängig von Lithologieprofilen erstellt werden. 
Es braucht hier noch eine Anpassung im UI-Header ( gleiches Problem wie #506). Im Chronostratigraphie-Tab sollten keine "unabhängigen" Chronostratigraphieprofile erstellt werden können, sondern nur mit vorhandenen Lithologyprofilen verknüpft werden,  damit erübrigt sich ein Teil der Übersetzungen.
Dieses Issue sollte nach dem UI-Change erneut bearbeitet werden.
