### ISSUE TITLE
Lithologie Tab anpassen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#504]
Wenn noch keine Lithologie erfasst wurde, sollte der Text in der Lithologie angepasst werden:

Wenn man nicht Editiert:

Kein Lithologieprofil verfügbar
Aucune profil lithologie disponible
Nessuno profilo litologia disponibile
No profilo litologia available

Wenn man Editiert:

Für die Erfassung eines Lithologieprofils bitte das Plus-Symbol oben links klicken
Pour l'enregistrement d'un profil lithologie veuillez cliquer sur le symbole dans le coin supérieur gauche
Per la registrazione di un profilo litologia cliccare il pulsante con il simbolo in alto a sinistra
For the recording of a lithology profile please click the plus symbol at the top left

Der Knopf oben Rechts sollte mit:

Lithologieprofil
Profil lithologie
Profilio litologia
Lithology profile

beschriftet sein.

Der Slider sollte mit:

Dies ist das Hauptlithologieprofil
Ceci est le profil lithologie principale
Questo è il profilo litologia principale
This is the main lithology profile

beschriftet sein

**Comment by MiraGeowerkstatt** [comment]
Solle mit #503 und nach dem dort beschriebenen, notwendigen UI-Change angegangen werden.
