### ISSUE TITLE
Hochladen der selben Datei für ein anderes Bohrloch nicht möglich

### ISSUE THREAD

**Issue by Lehats** [geoadmin/suite-bdms#509]
Wenn ein pdf bei einen Bohrloch hochgeladen wurde, kann es bei keinem weiteren Bohrloch hochgeladen werden.

Erwartetes Verhalten:
Datei sollte bei einem anderen Bohrloch hochgeladen werden können.

Verhalten:
Es gibt einem Vor, dass die Datei geladen wird, jedoch passiert nichts.

**Comment by gysimichael** [comment]
funktioniert! Danke
