### ISSUE TITLE
Chronostratigraphy Middle Jurassic migrieren

### ISSUE THREAD

**Issue by patrickackermann** [geoadmin/suite-bdms#511]
alte Chronostratigraphy `Middle Jurassic undifferenciated` (geolcode 15001168) nach `Middle Jurassic` (geolcode 15001070) migrieren

Betroffen sind Tabellen `layer` und `chronostratigraphy`

**Comment by gysimichael** [comment]
Funktioniert jetzt, danke fürs Troubleshooting!
