### ISSUE TITLE
Teufenangaben Visualisierung bei Chronostratigraphie

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#515]
Ab einer gewissen Zoomstufe verfliessen die Teufenangaben mit den Wert des Eons, was optisch unschön ist. Wäre es nicht sinnvoller, wenn man nicht am Editieren der Felder ist, die Zahlen neben der Spalte links visualisert, und nur bei der Editierung sie in die Felder in der Spalte platziert:

![Image](https://user-images.githubusercontent.com/108096632/223746538-2b611a4e-dd64-4383-806d-4e20e621e413.png)

**Comment by RBordoni** [comment]
Wir haben es so gelöst, dass die Zahlen ab einer gewissen Zoomstufe verschwinden. Links neben der Spalte ist unpassend, da dort andere Elemente liegen.

**Comment by gysimichael** [comment]
top, gefällt mir sehr gut!
