### ISSUE TITLE
Überlappungen Chronostratigraphie und Lithologie

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#516]
Wenn man unter Lithologie eine Änderung vornimmt und das PopupFenster nicht schliesst, anschliessend auf Chronostratigraphie geht, bleibt das Fenster offen:

![Image](https://user-images.githubusercontent.com/108096632/223941930-36f4ea40-c2c0-4ab8-bd79-f6085872d712.png)

**Comment by patrickackermann** [comment]
Mit neuem Header zur Auswahl der Lithologie zu der die Chronostratigraphie erfasst wird würde dieser bug auch behoben.

**Comment by gysimichael** [comment]
das geht nun, danke!
