### ISSUE TITLE
CSV Vorlage enthält Zeilenschaltungen und Leerschläge

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#520]
Die CSV-Vorlage (String) enthält Zeilenschaltungen, Leerschläge und an einer Stelle ein doppeltes Anführungszeichen.

Da der Sinn dieses Strings ist, ihn mit Copy/Paste in ein Textfile zu kopieren und dieses dann im Excel aufzumachen, dürfen diese Dinge nicht vorkommen.

![Image](https://user-images.githubusercontent.com/31883445/224743791-4d945913-ffc0-4d7f-8b51-0a686cba2293.png)

**Comment by gysimichael** [comment]
Danke
