### ISSUE TITLE
Nicht verwendetes Datums-Feld im Import CSV

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#522]
Das Feld "date" ist in der CSV-Vorlage enthalten, wird aber nach dem Import nicht sichtbar.
In der DB vermutlich ein Überbleibsel von früher.

To do:
- [ ] Aus CSV Import Vorlage-String entfernen
- [ ] Abklären, ob in DB obsolet und falls ja, aus DB löschen.

![Image](https://user-images.githubusercontent.com/31883445/224938524-f098d7ce-3569-40c3-a779-89d617f1fccf.png)

**Comment by RBordoni** [comment]
Vermutlich ein Zusammenhang mit Meldung von Michael vom 14.03.2023: 

> unter borehole in der DB gibt es ein Eintrag date_bho, der aber in der DB nur NULL Einträge hat. Ist es möglich zu schauen, wo der verhängt ist? ich glaube im UI nicht, zumindst ist mir das noch nie aufgefallen

**Comment by gysimichael** [comment]
danke
