### ISSUE TITLE
Import der Bohrungen funktioniert nicht

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#530]
Wenn man eine Bohrung importiert, gemäss vorgaben der Attribute, welche beim Importer Hinterlegt sind:

Erwartetes Verhalten:
Bohrung wird importiert und alle Attribute, die im .csv enthalten sind, wurden in die DB geschrieben

Verhalten:
Import-Prozess läuft durch, die Anzahl zu importierenden Bohrungen werden kreiert, jedoch werden nur Teile der IDs geladen, sonst sind alle Felder leer

Dies sowohl mit meinem Import file: import.csv, aber auch mit dem modifizierten Testfile von Mira (einfach zusätzlich Kanton, Land und Stadt eingefügt, damit der Importer es liest)

Noch offene Punkte:
- [x] Alle Leerzeichen aus dem Header im UI entfernen
- [x] Sonderzeichen wie ä,ö,ü oder é,è,à,ç werden nicht korrekt geladen
- [x] #541
- [ ] Kantons- und Gemeinde-Spalte entfernen, da diese automatisch berechnet werden

**Comment by gysimichael** [comment]
[testdata.csv](https://github.com/geoadmin/suite-bdms/files/10987236/testdata.csv)



[data_Converter-Import.xlsx](https://github.com/geoadmin/suite-bdms/files/10987241/data_Converter-Import.xlsx)
[import.csv](https://github.com/geoadmin/suite-bdms/files/10987242/import.csv)

**Comment by gysimichael** [comment]
Habe noch ein bisschen rumgespielt und folgendes erreicht:

Konnte nun mit dem Excel generierte Bohrungsliste vollständig laden:
- alle Leerzeichen aus dem Header entfernt
- sichergestellt, das Daten nicht als Zahl dargestellt wird, was in Excel leider Standard ist
- Alle geolcodes geprüft, ob diese von boreholes.swissgeol.ch erkannt werden, und festgestellt, dass ich bei der Chronostrati schon zwei Codes drin habe, die es eingentlich gar nicht gibt.

Somit habe ich 1510 Bohrungen in die Workgroup Neu importiert und sieht gut aus.



[Import.csv](https://github.com/geoadmin/suite-bdms/files/10997990/Import.csv)



[data_Converter-Import.xlsx](https://github.com/geoadmin/suite-bdms/files/10997991/data_Converter-Import.xlsx)

**Comment by gysimichael** [comment]
folgendes habe ich festgestellt:

-Sonderzeichen wie ä,ö,ü oder é,è,à,ç werden nicht korrekt geladen
- LV03 Einträge werden nicht in die DB geschrieben
- boreholes braucht die id_cli und nicht die geolcode. Ich frage mich, wieso man überhaupt diese Duplikation hat. Die Mehrheit der Einträge sind identisch, mit Ausnahme von:

id_cli		geolcode
20101001	30000101
20101002	30000102
20101003	30000103
20101004	30000104
9100		30000301
9101		30000302
9102		30000303
9103		30000304
9104		30000305
9105		30000306
9000		30000201
9001		30000202
9002		30000203
9003		30000204
9004		30000205
2211601		22116001
2211602		22116002
2211603		22116003

Könnte man die geolcode löschen, vorher aber noch die geolcode nummern wie oben aufgelistet auf id_cli übertragen, das wir konsistent mit unserer geolcode Inventur sind?

**Comment by danjov** [comment]
Zusammenfassung nach Rücksprache mit Michael:

- Sonderzeichen unterstützen
- LV03-Einträge
- Kantons- und Gemeinde-Spalte entfernen, da diese automatisch berechnet werden
- Geolcodes können laut Michael vermutlich abgeräumt werden und die technischen IDs verwendet werden. Die Geolcodes werden ausserhalb der swisstopo nicht verwendet.

**Comment by Lehats** [comment]
@gysimichael Bei welchen Spalten hast du Probleme mit den Sonderzeichen? Kannst du mir evt. ein csv file senden, welches das Fehlverhalten auslöst?

**Comment by gysimichael** [comment]
https://dev.boreholes.swissgeol.ch/editor/37804

[Mappe1.csv](https://github.com/geoadmin/suite-bdms/files/11074941/Mappe1.csv)

Text | Text | Text | Text | Text | Text | Text | Text | Text | Text | Text | Text | Text
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | Text
id_geodin_shortname | id_info_geol | id_original | id_canton | id_geo_quat | id_geo_mol | id_geo_therm | id_top_fels | id_geodin | original_name | project_name | alternate_name | remarks

**Comment by Lehats** [comment]
@gysimichael Wir haben das File _Mappe1.csv_ angeschaut und können einige Zeichen nicht erkennen. Kannst du uns evt. einen screen shot schicken bei dem du das csv im excel offen hast? Wie du in meinem screen shot siehst, sind die Zeichen für mich nicht sichtbar.

![Image](https://user-images.githubusercontent.com/37898460/228194459-7af75167-fa59-4897-a1a0-71143ff408cf.png)

**Comment by gysimichael** [comment]
[test.xlsx](https://github.com/geoadmin/suite-bdms/files/11093975/test.xlsx)

**Comment by gysimichael** [comment]
Sorry, da ist irgendwie der Wurm drinn, wenn ich das excel in CSV abspeichere, oder .TXT, generiert es die komischen Zeichen. Im .XLSX ist alles ok

**Comment by gysimichael** [comment]
Ahhhh....
Problem liegt beim User!!!

Wenn ich das excel als CSV-UTF8 speichere, geht alles korrekt. Sorry, mein Fehler!

**Comment by gysimichael** [comment]
https://dev.boreholes.swissgeol.ch/editor/37813

**Comment by gysimichael** [comment]
[ich.csv](https://github.com/geoadmin/suite-bdms/files/11094044/ich.csv)

**Comment by Lehats** [comment]
@gysimichael Genau, du hast das richtig erkannt. Um einen korrekten Import zu garantieren, muss das CSV in UTF-8 gespeichert sein.

**Comment by gysimichael** [comment]
cool, geht, danke
