### ISSUE TITLE
Intervallbezeichung Chronostratigraphie

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#537]
Um Konsistent mit den bereits bestehenden Feldern zu sein, müssen "von Tiefe" auf "Top [m MD]" und "bis Tiefe" auf "Basis [m MD)" gewechselt werden. Damit könnte man auch das "m" in dieser Zelle weglassen, das es ja schon im Header enthalten ist.
Auch müsste man die Fehlermeldung, wenn die Basis kleiner ist als der Top, anpassen.

**Comment by patrickackermann** [comment]
Siehe auch: https://github.com/geoadmin/suite-bdms/issues/627

**Comment by MiraGeowerkstatt** [comment]
Es ist jetzt "Von Tiefe [m MD]" ... analog zu den angepassten Tiefen Labels


![Image](https://github.com/geoadmin/suite-bdms/assets/49144408/831aed60-536f-4a47-8a1c-fdaf5d6bc57d)
