### ISSUE TITLE
Import der Koordinaten auf zwei Felder reduzieren

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#542]
Status Quo: Im Import CSV sind 5 Felder für den Import der Koordinaten vorhanden.
original_reference_system, location_x_lv_95, location_y_lv_95, location_x_lv_03, location_x_lv_03

Dies führt zu vielen Tests, die nötig sind (Was wenn kein original_reference_system angegeben ist? Was wenn beide Koordinaten ausgefüllt sind? ... ) und für die Befüllung des CSV sind viele Überlegungen nötig.

Eigentlich ist and den Koordinaten anzusehen, was sie sind. 

**Neuer Umsetzungsvorschlag:**

- Wir führen im CSV nur zwei Felder X_Koordinate, Y_Koordinate.
- Am Zahlenformat wird erkannt welches Referenzsystem als Original angegeben werden muss
- Das jeweils andere wird berechnet

**Comment by RBordoni** [comment]
@gysimichael Bist du mit dieser Umsetzung einverstanden? Wir sind bei den Überlegungen zu der Weiterentwicklung des Imports darauf gestossen. Wir würden diesen Punkt, falls ok, jetzt schon so bauen, damit sich die User nicht an etwas anderes gewöhnen.

**Comment by gysimichael** [comment]
tönt vernünftig, somit kann so umgesetzt werden

**Comment by gysimichael** [comment]
funktioniert bestens! Danke!
