### ISSUE TITLE
ID-Liste mit Prod abgleichen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#543]
Die Liste der IDs sind im DEV sowohl in den Daten, wie auch im Import-CSV anzupassen.  Sie sollen dem jetzigen PROD entsprechen. Neu ist beispielsweise _ID Kernlager_. _ID Borhole_ wurde zu _ID GeODin-Shortname_ umbenannt.

Der Abgleich der DBs bzw. der Codelisten erfolgte am 04.04.2023, der CSV-Import muss noch angepasst werden.

**Comment by gysimichael** [comment]
klappt super, danke!
