### ISSUE TITLE
Online-Hilfe

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#549]
Es soll eine Online-Hilfe bzw. Dokumentation der Webapplikation mit [DocFX](https://dotnet.github.io/docfx/) oder [MkDocs](https://www.mkdocs.org/) generiert und mit der Applikation ausgeliefert werden.

**Comment by RBordoni** [comment]
Test Version: 2.0.284: Online Hilfe lässt sich nicht öffnen. Beim Klick auf Help wird man zu Login-Screen weitergeleitet.
