### ISSUE TITLE
Pflichtfelder für CSV-Import

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#550]
In der Import-CSV-Datei für die Boreholes sind die drei Felder für Original Name, X und Y neu Pflichtfelder.

- [x] Validierung erstellen
- [x] Im UI ein Feld für die Validierungs-Rückmeldungen erstellen (grosses Textfeld mit Scrollbar)

Bei einem Fehler wird in Phase 1 der ganze Import abgebrochen (Prinzip "Alles oder nichts")

**Comment by gysimichael** [comment]
finde ich auch, danke für die Umsetzung!
