### ISSUE TITLE
Duplikate validieren

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#551]
Duplikate sollen erkannt werden (innerhalb einer Import Datei und über mehrere Importereignisse hinweg). Kriterien:

- Kombination X (Radius 2m), Y (Radius 2m), Bohrlänge
- Name nicht berücksichtigen

To Do:
- [x]  Validierung erstellen
- [x]  Validierungs-Rückmeldung anzeigen

Bei einem Fehler wird in Phase 1 der ganze Import abgebrochen (Prinzip "Alles oder nichts")

**Comment by Lehats** [comment]
@RBordoni Mit "und über mehrere Importereignisse hinweg" ist gemeint, dass kein Borehole in der Db bereits existieren darf mit den beschriebenen Kombination. Stimmt das?

**Comment by RBordoni** [comment]
Ja, das stimmt so. Vielleicht wird dies später nur in einem Warning enden, die Validierung wollen wir aber. Jetzt wird wie gesagt abgebrochen.

**Comment by RBordoni** [comment]
Test RB Version: 2.0.293:
Die Angabe der Row-Nummer ist falsch. Es wird einfach hochgezählt. Das Ziel ist aber die Row-Nummer im CSV zu haben (abzüglich Header), damit man dem Fehler nachgehen kann.


![Image](https://user-images.githubusercontent.com/31883445/232399771-994bb0c4-b599-466e-b9dc-5c0493e78b0d.png)

In diesem Beispiel eigentlich Row 7:


![Image](https://user-images.githubusercontent.com/31883445/232400003-ad522602-0f27-4b5e-ad82-09e83e836dec.png)

**Comment by gysimichael** [comment]
klappt einwandfrei! Danke!
