### ISSUE TITLE
Import Lithologie ermöglichen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#553]
To Do:

- [x] Import von minimaler Lithologie via API ermöglichen
- [ ] Lithologie import mit allen Attributen inkl. Mehrfachauswahl
- [ ] Upload Funktionalität für Lithologie CSV gemäss Lösungsdesign (Word)
- [x] Bohrhole CSV um Import-ID erweitern
- [ ] UI erweitern mit zusätzlichem Upload Bereich für Lithologie CSV
- [ ] Validierung: Alle sich in mehreren Zeilen wiederholende Felder einer Stratigraphie müssen identisch sein
- [x] Validierung: Pflichtfelder: Import-ID, Strati-ID, Top, Base

Bei einem Fehler wird in Phase 1 der ganze Import abgebrochen (Prinzip "Alles oder nichts")

**Comment by RBordoni** [comment]
Test RB. Import funktioniert grundsätzlich. 
Mit #756 werden noch folgende Schwachstellen korrigiert: Es können momentan nur 10 Files gedroppt werden und UI wird noch optimiert.

**Comment by gysimichael** [comment]
Es fehlen zwei Attribute für den Import:
-gradation
-Coarse component lithology

Diese müssten noch ergänzt werden.

Desweitern müsste man:
-lithostratigraphie
-Chronostratigraphie
im Importer löschen, da diese ja nun im neuen Modul abgehandelt werden. Sobald diese neuen Moduls fertig sind, müsste man diese Einträge generell aus dem UI und der DB in unter layer entfernen

Rest funktioniert Einwandfrei, bis auf den Issue bezüglich "Performance" wie mit Frederic besprochen. Ist beim testen mehrmals aufgetreten.

Was mir noch aufgefallen ist bezüglich Filter aber auch in Viewer und Editor:

Es gibt ein Durcheinander mit "Coarse component Lithology" und "Lithology top bedrock"

Settings Viewer Stratigraphie Filter: Lithology top bedrock
Settings Viewer Stratigraphie fields: Lithology top bedrock
Settings Editor Stratigraphie Filter: Lithology top bedrock
Settings Editor Stratigraphie fields: Lithology top bedrock

Editor Stratigraphie Filter: Coarse component lithology
Viewer Stratigraphie Filter: Coarse component lithology

Editor Lithology: Coarse component lithology -> Settings werden aber nicht berücksichtig, ist immer ausgeblendet
Viewer Profil: Lithologie to bedrock -> Settings werden berücksichtigt

Es sollte überall "Lithology top bedrock" sein

Gut sieht man dies bei der Bohrung https://dev.boreholes.swissgeol.ch/48161 beobachten

**Comment by RBordoni** [comment]
Ich schliesse dieses Issue. Das folgende Testfeedback ist umgesetzt, alle anderen Punkte sind in Einzelissues verteilt.
Done:
> Es fehlen zwei Attribute für den Import:
> -gradation
> -Coarse component lithology
> Diese müssten noch ergänzt werden.
