### ISSUE TITLE
Help für Import erstellen mit Link auf UI

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#558]
Bisher bekannter Inhalt:

- Struktur und Beziehungen der CSV-Dateien
- UTF8
- erwähnen, dass Row x die Datenzeile ist. Row 1 ist erste Datenzeile und entspricht im Excel Zeile 2
- erwähnen, das Duplikate Validierung pro Workgroup
- evtl. Converter Excel von Michael beschreiben
- ...

Hängt zusammen mit #557 und CSV-Vorlagen

**Comment by danjov** [comment]
@RBordoni @gysimichael Wie bereits angesprochen ist die Online-Hilfe im [Markdown-Syntax](https://www.markdownguide.org/basic-syntax/) geschrieben und kann direkt, wie die Übersetzungen, in GitHub editiert werden. Die Online-Hilfe bietet dazu auf jeder Seite einen direkten Link ("_Edit on GitHub_") zum entsprechenden Artikel an, welcher dann direkt in GitHub bearbeitet werden kann.

Beispiel:
![image](https://user-images.githubusercontent.com/8969524/236172845-2f98e928-e14d-49bc-a25d-24348a2eb98b.png)

**Comment by gysimichael** [comment]
@danjov : könnte man den Title oben links auf boreholes.swissgeol.ch wechseln?

Der Starteintrag konnte ich auf Github.com ändern, der Titel aber nicht.

Danke!

**Comment by gysimichael** [comment]
coole Sache! Habe kleine Änderungen auf Github.com vorgenommen, sonst Top! Danke

**Comment by danjov** [comment]
@gysimichael Danke für das Feedback. Der Seitentitel wurde angepasst (siehe #637).

**Comment by gysimichael** [comment]
Vielen Dank, ist nun gut so!
