### ISSUE TITLE
Bei Chronostratigraphie kann die ganze Lithologie gelöscht werden

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#573]
Die Lösch- Und Klon-Funktion ist bei der Chronostratigraphie zu entfernen. Sie löscht und klont nicht die Chronostratigraphie, sondern die ganze Strati inkl. Lithologie. Das ist verwirrend und führt zu fehlern.

![Image](https://user-images.githubusercontent.com/31883445/230413901-741b3e71-f35f-45ec-a8ff-e77bd0e2ed0f.png)

**Comment by gysimichael** [comment]
Danke!
