### ISSUE TITLE
Erfassung eines Wasserzutritts (Observation - WaterIngress) ermöglichen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#575]
Erfassung eines Wasserzutritts (Observation - WaterIngress) ermöglichen. 

Grundlage:
- Besprechung vom 05.04.2023 mit Stefan Volken, Michael Gysi, Mira Bleuler, Daniel Jovanovic, Frederic Stahel, Renato Bordoni
- Excel Datenmodell _5064.002_miniDM_Observations_V2_for GeoWerkstatt.xlsx_

**Comment by gysimichael** [comment]
@MiraGeowerkstatt ich kann die Dropdowns nicht sehen, respekektive sind sie eventuell in weisser Schrift

**Comment by danjov** [comment]
@gysimichael Sprache auf Deutsch umstellen, da wir die anderen Übersetzungen noch nicht drin haben.

**Comment by gysimichael** [comment]
:-), ok, das erklärt es auch :-)

**Comment by gysimichael** [comment]
@MiraGeowerkstatt Sieht gut aus, von der Beschriftung wäre es noch Sinnvoll  bei von Tiefe und bis Tiefe in der Klammer "m MD" zu Schreiben und Eckige Klammern zu benutzten. Auch bei "m ü.M." sollten eckige klammern benützt werden, um konsistent mit den Anderen Einträgen zu sein.

Generell fällt mir auf:
Lithologie: Top [m MD], Basis [m MD]
Lithologische Beschreibung: Top [m MD], Top [m MD] -> kann es sein das der zweite Header ein Fehler ist
Fazielle Beschreibung: Top [m MD], Top [m MD] -> kann es sein das der zweite Header ein Fehler ist
Chronostratigraphie: von Tiefe, bis Tiefe und Einheit in der Zelle, wenn der Eintrag gemacht wurde, steht die Zahl und dann "m" und nicht "m MD"
Wasserzutritt: von Tiefe (m), bis Tiefe (m)
Verrohrung: Top [m MD], Basis [m MD]
Instrumentierung: Von [m MD], Bis [m MD]
Hinterfüllung: Top [m MD], Basis [m MD]

Da ist ein bisschen Wild West, obwohl immer das selbe gemeint ist. Aus meiner Sicht kann gut "von Tiefe [m MD] und "bis Tiefe [m MD]" benützt werden, müsste es aber einfach konsequent bei allen Modulen umsetzten.

**Comment by MiraGeowerkstatt** [comment]
Ich werde das als separates Issue erfassen, dann vereinheitlichen wir das gleich über die ganze Applikation.
