### ISSUE TITLE
Erfassung einer Grundwassermessung (Observation - GroundwaterLevelMeasurement) ermöglichen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#576]
Erfassung einer Grundwassermessung (Observation - GroundwaterLevelMeasurement) ermöglichen. 

Grundlage:
- Besprechung vom 05.04.2023 mit Stefan Volken, Michael Gysi, Mira Bleuler, Daniel Jovanovic, Frederic Stahel, Renato Bordoni
- Excel Datenmodell _5064.002_miniDM_Observations_V2_for GeoWerkstatt.xlsx_

**Comment by gysimichael** [comment]
@MiraGeowerkstatt : wieso wird bei der Teufe der Wert 0 als - angezeigt?

**Comment by gysimichael** [comment]
Sonst funktioniert es einwandfrei

**Comment by gysimichael** [comment]
danke für die gute Umsetzung

**Comment by gysimichael** [comment]
Jetzt ist alles in Ordnung, danke!
