### ISSUE TITLE
Erfassung von Hydro-Tests (Observation - Hydro-Test) ermöglichen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#577]
Erfassung von Hydro-Tests (Observation - Hydro-Test) ermöglichen

Grundlage:
- Besprechung vom 05.04.2023 mit Stefan Volken, Michael Gysi, Mira Bleuler, Daniel Jovanovic, Frederic Stahel, Renato Bordoni
- Excel Datenmodell 5064.002_miniDM_Observations_V2_for GeoWerkstatt.xlsx

**Comment by gysimichael** [comment]
@MiraGeowerkstatt : Sieht gut aus, ausser bei Art des Hydrotests bei "keine Angabe" müsste man etwas bei den Resultaten etwas auswählen unter Parameter (Pflichtfeld) kann aber nicht. Wird sich wohl erübrigen mit den neuen Wertelisten, aber müsste nochmals kurz getestet werden

**Comment by gysimichael** [comment]
sieht nun gut aus, danke!
