### ISSUE TITLE
Räumliches Bezugssystem - Eingabe LV03 ermöglichen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#59]
**Lösungsdesign**	

- Die Eingabe der Koordinaten soll in den Bezugsrahmen LV03 und LV95 möglich sein. 
  - Es gibt zwei neue Felder für LV03 (East und North)
  - Die Beschriftungen werden entsprechend angepasst (Entweder "Coordinate East LV95" (und entsprechend LV03) etc. oder als ganzer Block/Zeile gekennzeichnet)
- Die Eingabe erfolgt entweder im einen oder im anderen Bezugsrahmen. Es können nicht beide manuell eingegeben werden.
- Der Original(Ausgangs)-Bezugsrahmen soll markiert werden können
  - Pro Bezugsrahmen wird eine Tickbox oder Combobox erstellt (Details bei Realisierung zu definieren)
  - Es kann immer nur ein Bezugsrahmen als Original gekennzeichnet werden. Nach Wahl des Originals sind die Felder des anderen Bezugsrahmens ausgegraut (2 Koordinatenfelder und Tickbox).
  - Im Workflow zur Bestimmung des Originals gibt es zwei Use Cases. 
  - Voraussetzung: Alle Felder sind noch leer.
    - Es wird eine der beiden Tickboxes angeklickt
    - Im ersten der leeren Koordinatenfelder wir eine Eingabe gemacht → die Tickbox wird automatisch gesetzt.
  - Wechsel des Original-Bezugsrahmens. 
    - Um bei einer Fehleingabe den anderen Bezugsrahmen als Original zu kennzeichnen, muss die gesetzte Tickbox abgewählt werden.
    - Beim Abwählen einer gesetzten Tickbox werden alle Koordinatenfelder geleert (!) und die Eingabe beginnt von vorne. (Dies ist unseres Erachtens die beste Lösung, die nicht zu einem verwirrenden Workflow führt.)
- Nach der Eingabe der Koordinaten im Original-Bezugsrahmen werden die Koordinaten des andern Bezugsrahmens automatisch berechnet. Dazu wird eine echte Koordinatentrans-formation angewendet (REFRAME-Service von swisstopo  https://www.swisstopo.admin.ch/de/karten-daten-online/calculation-services/m2m.html)
- Die Umrechnung erfolgt mit maximaler Genauigkeit, gespeichert wird in der gleichen Genauigkeit (Kommastellen), wie die Ausgangsdaten vorliegen. Das Feld "+/- Coordinates [m]" wird nicht berücksichtigt.
- Die Z-Koordinate ist nicht Bestandteil der Berechnungen und wird nicht angefasst.
- In View- und Editor-Mode sollen immer beide Koordinaten angezeigt werden. 
- Die Anzeige im Kartenfenster erfolgt immer in LV95, ob Originalkoordinate oder berechnete. So bleibt die Anzeige konsistent und es entstehen keine Missverständnisse.

**Comment by gysimichael** [comment]
Frage: Wenn ich die Daten neu Eingebe, scheint alles gut zu funktionieren.
Wenn ich bestehende Bohrungen anschaue, dann sind bei LV03 und LV05 die gleichen Einträge, hat das damit zu tun, dass hier die ganze DB Einträge in LV03 noch migriert werden müssen?

**Comment by gysimichael** [comment]
Wäre es möglich, dass im Viewer und im Editor Modus, die Zahlen automatisch mit den Tausender-Strichen angezeigt werden? Also die Eingabe normal, jedoch wenn die Zahl steht, die Milion und Tausend mit einem Apostroph gekennzeichnet werden?

**Comment by MiraGeowerkstatt** [comment]
> Frage: Wenn ich die Daten neu Eingebe, scheint alles gut zu funktionieren. Wenn ich bestehende Bohrungen anschaue, dann sind bei LV03 und LV05 die gleichen Einträge, hat das damit zu tun, dass hier die ganze DB Einträge in LV03 noch migriert werden müssen?

Kannst du dazu ein Beispiel angeben, damit ich richtig verstehe was du meinst?

**Comment by MiraGeowerkstatt** [comment]
> Wäre es möglich, dass im Viewer und im Editor Modus, die Zahlen automatisch mit den Tausender-Strichen angezeigt werden? Also die Eingabe normal, jedoch wenn die Zahl steht, die Milion und Tausend mit einem Apostroph gekennzeichnet werden?

@RBordoni  Kannst du dazu ein Issue erfassen?

**Comment by gysimichael** [comment]
![image](https://user-images.githubusercontent.com/108096632/207539391-26fd80a8-e8ac-4b7e-b284-d06891b17bea.png)
![image](https://user-images.githubusercontent.com/108096632/207539434-415a9f94-0bc9-4fb6-a13a-a911e14f1e2f.png)

**Comment by gysimichael** [comment]
![image](https://user-images.githubusercontent.com/108096632/207539607-7beac3d4-fb52-44d0-a792-b0c8275f1497.png)
![image](https://user-images.githubusercontent.com/108096632/207539638-2edde9a3-f6aa-43dd-b94a-db68b37bf291.png)

**Comment by MiraGeowerkstatt** [comment]
Die bestehenden Koordinaten wurden wie in #61 beschrieben mit "Shift" migriert. Es besteht aber ein Migrationsendpunkt der auf der FINELTRA Transformation basiert. Den müssten wir dann nochmal laufen lassen.

**Comment by RBordoni** [comment]
Wir schliessen das Issue. Die obigen offenen Fragen wurden in eigene Issues erfasst.
→ #223 
→ #226
