### ISSUE TITLE
Tiefendurcheinander im Viewer Modus

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#590]
Bohrung Thun_1 im Viewer Modus öffnen:

Erwartetes Verhalten:

Profil wird der Tiefe geordnet angezeigt

Verhalten:

Tiefen im Profil sind durcheinander

![Image](https://user-images.githubusercontent.com/108096632/232384751-018b8cb0-e4bc-4504-ab9a-bd1560260f81.png)

Im Editor Modus scheinen die Teufen korrekt dargestellt zu sein

**Comment by patrickackermann** [comment]
Im Editor Modus werden die Layer im Front-End sortiert.
Die aus meiner Sicht beste Lösung wäre alle Layer immer im Back-End zu sortieren. Die Chronostratigraphy-Layer werden schon im Back-End sortiert.
