### ISSUE TITLE
Internal Error auf Testsystem

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#591]
Michael Gysi per Teams 17.04.2023:

Internal Error bei Tests durch Geotest, vermutlich ohne eine Bohrung zu laden, könnt ihr das mal anschauen.

User und Passwort siehe Teams

**Comment by RBordoni** [comment]
Test RB: Es liegt am Passwort. Ein User mit gleichem PW auf Dev bringt den Error.

**Comment by RBordoni** [comment]
Lösung: Wir haben die temporären Einstellungen dieses Users aus der DB gelöscht (Settings, Sortierung, etc.), das hat geholfen.

Wie das genau zustande kam, wäre interessant zu wissen. Es ist schwierig das zu reproduzieren.

**Comment by gysimichael** [comment]
Danke!

**Comment by gysimichael** [comment]
Habe den Fehler reproduzieren können, indem ich beim Viewer Modus bei "Original Name" auf Sortieren geklickt habe. Offensichtlich ein Problem, wenn keine Bohrungen enthalten sind.

**Comment by gysimichael** [comment]
Wenn ich es bei einem anderen Account mache, funktioniert es aber, komisch. Scheint was mit dem Speichern der Account Settings zu tun zu haben, weiss aber nicht, wieso beim Account Geotest

**Comment by RBordoni** [comment]
@gysimichael Vielen Dank für die Info. Wir haben es nochmals zurückgesetzt. Fixing schauen wir noch.

**Comment by RBordoni** [comment]
Reproduzierbar wie folgt:
- Account XY erstellen
- Bohrungen per Import laden
- zwei drei mal Original Name klicken, dann kommt der interne Error

**Comment by RBordoni** [comment]
Es scheint, dass der Fehler auftritt, wenn im Account (oder Workgroup?) Bohrungen mit gleichem Original Name vorhanden sind. Wenn nicht, scheint der Fehler nicht aufzutreten.

**Comment by gysimichael** [comment]
@RBordoni [Mappe2.csv](https://github.com/geoadmin/suite-bdms/files/11258706/Mappe2.csv)

bin mir nicht sicher, denn mit dem laden von diesen Bohrungen auf Test, hatte ich den gleichen Effekt, trotz anderen original namen

**Comment by RBordoni** [comment]
Test Version: 2.0.298: Der Fehler beim Klicken auf den Original Name tritt nicht mehr auf. Aus meiner Sicht ist der Bug gefixt.

Es Tritt noch ein anderer Internal Error auf, wenn man sich als Admin in den Settings>Admin befindet und ausloggt und dann als anderer Viewer-User einloggt. Nach dem Einloggen versucht die Applikation auf Settings>Admin zu gehen, der Viewer hat aber kein Recht dazu. Use Case tritt eher nur beim Testen auf.
→ #602
