### ISSUE TITLE
Validierung Duplikate soll pro Workgroup erfolgen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#605]
Duplikatvalidierung soll pro Workgroup erfolgen, nicht über ganze DB.

**Comment by gysimichael** [comment]
kann 3 mal die gleich Bohrung laden, ohne das ich eine Fehlermeldung kriege, respektive der Workflow abgebrochen wird

**Comment by Lehats** [comment]
@gysimichael Kannst du diese Validierung nochmals testen? Bei mir funktioniert es. Ansonsten wäre ich froh um ein csv welches bei dir mehrmals geht. Und die workgroup in der du es versuchts. Danke

**Comment by gysimichael** [comment]
geht nicht, habe bei dev im Workgroup Test zwei mal die gleiche Bohrung geladen. Hier noch die Bohrung:


[Test-Bohrung.csv](https://github.com/geoadmin/suite-bdms/files/11558034/Test-Bohrung.csv)



[GeolBimFinalReport.pdf](https://github.com/geoadmin/suite-bdms/files/11558036/GeolBimFinalReport.pdf)
[GrundlagenBimMethode.pdf](https://github.com/geoadmin/suite-bdms/files/11558037/GrundlagenBimMethode.pdf)

**Comment by gysimichael** [comment]
geht nun einwandfrei! Danke!
