### ISSUE TITLE
Migration bestehender Koordinateneingaben

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#61]
Nah der Ermöglichung der Eingabe von LV03 #59, sind die bisherigen Daten zu bereinigen. 
Für die Migration bestehender Daten werden per SQL-Skript alle Daten des Bundes auf LV03 gesetzt. Die Koordinaten werden mit „Shift“ zurückgesetzt, d.h. es werden die 1 bzw. 2 am Anfang gestrichen.

**Comment by gysimichael** [comment]
Bitte beachten, das Bohrungen Bülach-1-1, Trüllikon-1-1, Marthalen-1-1, Bözberg-1-1, Bözberg-2-1, Stadel-2-1, Stadel-3-1, Rheinau-1-1 schon in LV95 sind, alle anderen Bohrungen sind LV03 und können somit konvertiert werden

**Comment by flenny** [comment]
Folgende Bohrungen verbleiben auf LV95:
_'Bülach-1-1','Trüllikon-1-1','Marthalen-1','Boezberg-1','Boezberg-2','Stadel-2','Stadel-3','Rheinau-1'_
