### ISSUE TITLE
Ausbau Id zur Erfassungsmaske für Wateringress hinzufügen.

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#611]

**Comment by RBordoni** [comment]
Die Verbindung erfolgt zum "Ausbau". Dann müsste das Label des Feldes eigentlich "Ausbau" heissen, nicht "Verrohrung".


![Image](https://user-images.githubusercontent.com/31883445/234851291-aaf6c752-3ee5-4254-8fab-5d3db003c894.png)

**Comment by gysimichael** [comment]
@RBordoni Nein, ist denke ich gut so. Ausbau bezeichnet das ganze drum herum, daher ist es bei Bolean gut so, ihr wird aber aktiv auf ein Verrohrungschema verwiesen. Ich würde es somit so lassen.
