### ISSUE TITLE
Menu Hydrogeologie nicht auf Deutsch

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#617]
To Do:

- [x] Im Sprachmodus Deutsch  erscheint im Manu "Hydrogeology" und "Wateringress" anstelle von "Hydrogeologie" und "Wasserzutritt".
- [ ] Achtung: Es heisst "Wasserzutritt" nicht "Wassereintritt". Überall anpassen.

![Image](https://user-images.githubusercontent.com/31883445/234791383-e68e4f9b-87b5-483a-929c-b48cea666aa3.png)

**Comment by danjov** [comment]
Die Anpassung ist noch nicht überall erfolgt:
![image](https://user-images.githubusercontent.com/8969524/235105033-fb5ae34a-7a66-4dc8-a2b6-f5424f23640c.png)

Der Infotext sowie der Button für die Erstellung eines ersten Wasserzutritts enthalten die Begriffe _Wassereintritt_.
