### ISSUE TITLE
Vereinheitlichen von Tiefenlables

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#627]
Infos von Michael : 
Bei von Tiefe und bis Tiefe in der Klammer "m MD" schreiben und Eckige Klammern zu benutzten. Auch bei "m ü.M." sollten eckige klammern benützt werden, um konsistent mit den Anderen Einträgen zu sein.

Generell fällt mir auf:
Lithologie: Top [m MD], Basis [m MD]
Lithologische Beschreibung: Top [m MD], Top [m MD] -> kann es sein das der zweite Header ein Fehler ist
Fazielle Beschreibung: Top [m MD], Top [m MD] -> kann es sein das der zweite Header ein Fehler ist
Chronostratigraphie: von Tiefe, bis Tiefe und Einheit in der Zelle, wenn der Eintrag gemacht wurde, steht die Zahl und dann "m" und nicht "m MD"
Wasserzutritt: von Tiefe (m), bis Tiefe (m)
Verrohrung: Top [m MD], Basis [m MD]
Instrumentierung: Von [m MD], Bis [m MD]
Hinterfüllung: Top [m MD], Basis [m MD]

Da ist ein bisschen Wild West, obwohl immer das selbe gemeint ist. Aus meiner Sicht kann gut "von Tiefe [m MD] und "bis Tiefe [m MD]" benützt werden, müsste es aber einfach konsequent bei allen Modulen umsetzten.

**Comment by gysimichael** [comment]
@MiraGeowerkstatt bei Hinterfüllung haben wir zwei mal von Tiefe, da müsste der zweiter Eintrag bis Tiefe heissen

**Comment by gysimichael** [comment]
danke
