### ISSUE TITLE
Feedback-Funktion: Angabe zur Umgebung (Prod, Test, Dev) im Mail ergänzen

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#63]

**Comment by danjov** [comment]
Siehe auch #4

**Comment by danjov** [comment]
Angabe zur Applikationsversion wäre auch hilfreich.

**Comment by flenny** [comment]
Wurde mit #4 umgesetzt.


![Image](https://user-images.githubusercontent.com/1365121/195032578-bc45f714-103e-4388-9426-7667f678162f.png)

**Comment by flenny** [comment]
Warten mit Testen bis sämtliche Umgebungen neu installiert wurden. DEV und Prod sind aktuell noch ausstehend.
