### ISSUE TITLE
Erfassung einer Feldmessung (Observation - FieldMeasurement) ermöglichen

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [geoadmin/suite-bdms#648]
Erfassung einer Feldmessung (Observation - FieldMeasurement) ermöglichen.

Grundlage:

Besprechung vom 05.04.2023 mit Stefan Volken, Michael Gysi, Mira Bleuler, Daniel Jovanovic, Frederic Stahel, Renato Bordoni
Excel Datenmodell 5064.002_miniDM_Observations_V2_for GeoWerkstatt.xlsx

**Comment by gysimichael** [comment]
@MiraGeowerkstatt Bei den Werten bräuchte es noch ein Feld mit den Einheiten, sonst alles gut

**Comment by MiraGeowerkstatt** [comment]
@gysimichael Da ein Feld mit den Einheiten im Datenmodell nicht vorgesehen ist würde ich es wie beim Hydrotest-Resultat lösen, dass wir die Einheiten je nach Parameter Auswahl jeweils in das "Wert" Feld als Suffix anhängen.

Hier das Beispiel.  Passt das so für dich?


![Image](https://github.com/geoadmin/suite-bdms/assets/49144408/26c134cf-80aa-474a-bc3e-8f706e5a3e22)

**Comment by gysimichael** [comment]
genau! Passt!

**Comment by gysimichael** [comment]
@MiraGeowerkstatt : bei pH-Wert bei der Einheit den "-" bitte weglassen, der sieht seltsam aus:



![Image](https://github.com/geoadmin/suite-bdms/assets/108096632/0565eff3-909a-43ae-9cbb-66674bfb6b4e)

**Comment by gysimichael** [comment]
sonst sehr gut, danke!
