### ISSUE TITLE
Hydrotest Parameterwerte je nach Kachelgrösse nicht sichtbar

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#654]
**Repro Steps:**

1. Editor
2. Eine Bohrung > Hydrogeologie > Hydrotest > Bearbeitung beginnen
3. Neuer Hydrotest erfassen
4. Neues Resultat Erfassen

**Erwartet:**
Ich sehe neu eingetragene Parameterwerte. Die Parameterfelder dürfen nur soweit verkleinert werden, dass mindestens etwas sichtbar bleibt.

**Beobachtet:**
Je nachdem wie gross das Fenster ist und demzufolge je nachdem wie gross die Kachel ist, sind die Einträge nicht sichtbar.
Bei allen bisherigen Felder war immer noch ein kleiner Rest sichtbar.

![Image](https://user-images.githubusercontent.com/31883445/238365523-e6076aa5-522e-479c-91c0-3bb598dc7e94.png)

**Comment by gysimichael** [comment]
sieht nun gut aus, danke!
