### ISSUE TITLE
Hydrotest "Neues Resultat" nicht ausgegraut wenn wieder bearbeitet

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#655]
**Repro Steps:**

1. Editor
2. Eine Bohrung mit Hydrotest > Hydrogeologie > Hydrotest > Bearbeitung beginnen
3. Ein Resultat erfassen
4. Resultat speichern
5. Resultat wieder bearbeiten durch Klick auf Bleistift

**Erwartet**: "+" ist ausgegraut

**Beobachtet**:
1. "+" ist nicht ausgegraut

![Image](https://user-images.githubusercontent.com/31883445/238376464-baaabcfb-9f4c-4980-9577-1ba71a6581a8.png)

2. Nach Klick auf "+" sind zwei identische Einträge vorhanden in nicht gespeichertem Zustand

![Image](https://user-images.githubusercontent.com/31883445/238376817-21e71631-43bd-4328-8ac7-360791979256.png)

**Comment by gysimichael** [comment]
Danke, funktioniert jetzt!
