### ISSUE TITLE
Hydrotest zuletzt bearbeitete Kachel springt an den Schluss

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#656]
**Repro Steps:**
1. Editor
2. Eine Bohrung mit zwei Hydrotests
3. Hydrogeologie > Hydrotest > Bearbeitung beginnen
4. Erste Kachel Kommentar bearbeiten und dann speichern

**Erwartet:**
Kachel bleibt an Ort

**Beobachtet:** 
Kachel springt ans Ende

![Image](https://user-images.githubusercontent.com/31883445/238378814-2f880e0c-685c-40e7-bcbe-c76f32e8c369.png)

**Comment by gysimichael** [comment]
sehr gut, danke!
