### ISSUE TITLE
Italiensiche Übersetzungen werde nicht mehr angezeigt

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#657]
Habe gerade gemerkt, dass die italienischen Übersetzungen nicht angezeigt werden

![Image](https://user-images.githubusercontent.com/108096632/238538331-75c46f89-3c33-44e5-80ad-d087589e3700.png)

**Comment by RBordoni** [comment]
@gysimichael sollte jetzt wieder richtig sein
