### ISSUE TITLE
Beschriftung neben dem Logo

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#66]
Beschriftung neben Logo oben Links von swissforages.ch auf dev.boreholes.swissgeol.ch wechseln, bei den anderen Instanzen auf test.boreholes.swissgeol.ch und boreholes.swissgeol.ch

**Comment by RBordoni** [comment]
Es wird jeweils die URL als Basis genommen. Erst wenn die URL _dev.boreholes.swissgeol.ch_ heissen wird, wird die Beschriftung gemäss oben formulierter Anforderung erscheinen.


![Image](https://user-images.githubusercontent.com/31883445/199447532-0deb6dc4-3d0e-4336-9360-d06c72ebd6c2.png)
