### ISSUE TITLE
Stratigraphie Name schwierig einzugeben

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#676]
Wenn man in Reiter Stratigraphie den Namen der Stratigraphie Eintragen will, oder ändern will

Erwartetes Verhalten:
Der Name lässt sich einfach und ohne Probleme ändern

Aktuelles Verhalten:
Wenn man nicht kontinuierlich tippt, aktualisiert die App den Namen und kann somit nicht weiterschreiben

**Comment by MiraGeowerkstatt** [comment]
Es hat sich leider herausgestellt, dass es kein triviales Issue zum Fixen ist. Die betroffene Komponente ist an einer Stelle der Applikation, die noch komplett auf dem alten Api basiert und dort war das Konzept bislang so, 
dass das UI sich erst aktualisiert nachdem eine Änderung an den Server geschickt wurde und dann die einzelnen Komponenten alle wieder neu geladen werden. 
Das führt zu dem beobachteten Verhalten: Immer wenn es eine Änderung im Input Feld gibt, wird die unmittelbar an den Server weitergeleitet und das triggert wiederum ein Rerender des UI, damit es aktualisiert wird. Zudem werden an mehreren Stellen "manuell" Reloads aus dem Code getriggert. 
Da es keine "quick-and-dirty" Lösung dafür zu geben scheint, denke ich das sauberste wäre das Holen/Editieren der Stratigraphien auf das neue Api umzustellen. Spätestens wenn der "Completion" Bereich verbessert werden soll, ist das ohnehin unumgänglich.
Zum jetzigen Zeitpunkt hat das leider keinen Platz mehr.

**Comment by gysimichael** [comment]
ok, versteht und macht Sinn

**Comment by RBordoni** [comment]
Durch die Umstellungen bei #151 tritt das Verhalten auch bei alle Textfeldern innerhalb der Lithologie, Casing und Backfill auf. Die Eingabe wird fast unzumutbar. Es ist daher Zeit dieses Issue prioritär umzusetzen.

**Comment by danjov** [comment]
> Durch die Umstellungen bei #151 tritt das Verhalten auch bei alle Textfeldern innerhalb der Lithologie, Casing und Backfill auf. Die Eingabe wird fast unzumutbar. Es ist daher Zeit dieses Issue prioritär umzusetzen.

@Lehats @tschumpr Kann sich das jemand von euch anschauen? Vermutlich liegt es am Caching mit Redux und/oder React.Query. Meiner Meinung nach können wir an diesen Stellen auf das Caching verzichten.

**Comment by RBordoni** [comment]
Das Verhalten wurde pragmatisch so angepasst, dass die Eingabe flüssig erfolgt, die Speicherung erfolgt nach einer kurzen Verzögerung nach der letzten Tippen. Diese Lösung ist nicht bei allen Eingabesituationen optimal, das Ganze wird sich aber ändern nach der Überarbeitung des Gesamt-UIs.

**Comment by gysimichael** [comment]
sieh für den Moment als eine gute Lösung aus. Danke für die pragmatische Umsetzung!
