### ISSUE TITLE
Bei Einheit m2 ist die Zwei nicht hochgestellt

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#685]
Michael per Teams: "ist es möglich, bei den Units m2 das 2 hochzustellen, oder ist das aufwendig (beispielsweise bei Transmissivität)?"

Ort: Hydrotest > Resultate

![Image](https://user-images.githubusercontent.com/31883445/238913592-135bda4b-40b1-43cd-8052-7ee4789d3bc2.png)

**Comment by gysimichael** [comment]
super, das klappt, danke!
