### ISSUE TITLE
Beschränkung auf PDF bei den Attachment aufheben

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#687]
Neu sollen generell Files als Anhänge hochgeladen werden können. Alle Fileformate erlauben.

**Comment by RBordoni** [comment]
Jetziger Text im UI "Wählen Sie eine oder mehrere PDF Datei(en) aus:"
Das stimmt nicht ganz, da auch keine eingegeben werden können. Es ist auch nicht klar, dass es hier um die Attachments geht.

Wenn wir es umbauen für alle Dateiformate, würde ich es wie folgt nennen:
"Wählen Sie die hochzuladenden Anhänge aus:"

**Comment by gysimichael** [comment]
@Lehats csv konnte ich hochladen, zip auch, jedoch das zip wird nicht angezeigt:

https://dev.boreholes.swissgeol.ch/editor/14174/attachments

Wenn ich es nochmals hochlade, kommt aber die Meldung, das es das File in der Bohrung schon gibt. Könntest du das nochmals prüfen?

**Comment by Lehats** [comment]
@gysimichael Kannst du mir bitte das zip schicken?

**Comment by gysimichael** [comment]
lade es gerade auf Teams Download.zip

**Comment by Lehats** [comment]
@gysimichael Das Problem scheint die Grösse der Datei zu sein. Das zip von dir hat 36Mb. Ich konnte bis 25 Mb ohne Probleme hochladen. Die 200Mb aus der Doku habe ich so von der verwendeten Komponente des Drag&Drop Feld übernommen. Nun ist der Flaschenhals aber an einer anderen Stelle. Deshalb zwei Fragen.
1. Bist du sicher, dass der Upload von Files mit Grössen (25Mb +) vor dem Umbau auf das neue API möglich war?
2. Können wir die Doku auf 20Mb anpassen und die Files dementsprechend validieren?

Ich hänge das Zip an, welches erfolgreich auf Dev hochgeladen wurde. Kannst du das evt. noch bestätigen? Danke

[mb25.zip](https://github.com/geoadmin/suite-bdms/files/11573869/mb25.zip)

**Comment by gysimichael** [comment]
mit den 25 MB geht es.

Habe keine Ahnung, was vorher möglich war, aber 25 MB ist doch sehr am untern limit, gerade bei logs. 200 MB wäre da schn wünschenswert

**Comment by Lehats** [comment]
Gut wir schauen das an. Danke

**Comment by Lehats** [comment]
@gysimichael Ich denke es macht Sinn dieses Issue als erledigt zu betrachten und das Problem mit der Dateigrösse hier zu verfolgen.

**Comment by gysimichael** [comment]
upload von verschiedenen Files läuft einwandfrei, danke!
