### ISSUE TITLE
Ein Speichern-Häkchen für alles bei Resultaten Hydrotest

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#689]
Momentan muss jedes Hydrotest-Resultat einzeln gespeichert werden. Besser wäre es, wenn mit dem Häkchen oben rechts alles gespeichert wird.

![Image](https://user-images.githubusercontent.com/31883445/238931211-11ae8f4a-24a6-4a44-bfa1-c54722578eb3.png)

**Comment by gysimichael** [comment]
sehr gut, funktionniert
