### ISSUE TITLE
Chronostratigraphie architektur anpassen

### ISSUE THREAD

**Issue by patrickackermann** [geoadmin/suite-bdms#694]
- Im Header nur noch eine Auswahl für die Stratigraphy
- Anzeige von Stratigraphie Säulen verbessern, damit wenn chronostratigraphie Säule Tiefer geht als Lithologie diese trotzdem ganz angezeigt wird.

**Comment by gysimichael** [comment]
@patrickackermann  wenn man dem Stratigraphie Profil keinen Namen gibt, sieht man auch keinen Eintrag im Dropdown unter Chronostratigraphie, könnte man in diesem Fall "Keine Angabe" anziegen? So wäre ersichtlich, das man dieses Profil wählen kann und muss nicht auf einen Leereintrag klicken

**Comment by gysimichael** [comment]
@patrickackermann : Wenn keine Lithologie vorhanden ist, und man auf Chronostratigraphie klickt, kommt ein Ladezeichen, aber es passiert nicht, wäre es möglich, hier auch die Meldung "Keine Stratigraphie verfügbar" einzublenden?

**Comment by patrickackermann** [comment]
> @patrickackermann : Wenn keine Lithologie vorhanden ist, und man auf Chronostratigraphie klickt, kommt ein Ladezeichen, aber es passiert nicht, wäre es möglich, hier auch die Meldung "Keine Stratigraphie verfügbar" einzublenden?

Siehe auch: https://github.com/geoadmin/suite-bdms/issues/722

**Comment by gysimichael** [comment]
>@patrickackermann wenn man dem Stratigraphie Profil keinen Namen gibt, sieht man auch keinen Eintrag im Dropdown unter Chronostratigraphie, könnte man in diesem Fall "Keine Angabe" anziegen? So wäre ersichtlich, das man dieses Profil wählen kann und muss nicht auf einen Leereintrag klicken

Die gilt auch für Hydro Submodule, wenn man bei der Verrohrung "Keine Angabe" Einträge hat

**Comment by patrickackermann** [comment]
>Die gilt auch für Hydro Submodule, wenn man bei der Verrohrung "Keine Angabe" Einträge hat

Ich habe dazu ein neues Issue erstellt (https://github.com/geoadmin/suite-bdms/issues/750)
