### ISSUE TITLE
Drehendes Rad beim Öffnen einer Chronostratigraphie ohne Inhalt

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#722]
Beim Öffnen einer Chronostratigraphie ohne Inhalt, respektive wenn keine Stratigraphie vorhanden ist, sieht man ein Rädli das endlos dreht.

![Image](https://user-images.githubusercontent.com/31883445/240496070-03766025-8b90-4bb8-91a2-5a1cda0c13e1.png)

Wenn man dann eine Stratigraphie macht, aber noch ohne Lithologieeintrag, dann "rädelt" es hier:

![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/08b34bb7-2e70-4f48-add9-fb683f06b880)

**Comment by patrickackermann** [comment]
Hängt auch mit https://github.com/geoadmin/suite-bdms/issues/503 zusammen.

**Comment by gysimichael** [comment]
Sehr gut gelöst, danke!
