### ISSUE TITLE
Ausbau fertiggestellt immer auf DE

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#724]
Bei allen Hydromodulen im Observation Teil ist "Ausbau fertiggestellt" immer auf Deutch und müsste man wohl noch mit einem technischen Attribut versehen:

![Image](https://user-images.githubusercontent.com/108096632/240534725-c75b590e-4ae6-4eda-a871-4096f5a9ccde.png)

**Comment by RBordoni** [comment]
Test Version 2.0.396:

@MiraGeowerkstatt Weiblich "Installazione terminata"

**Comment by gysimichael** [comment]
@MiraGeowerkstatt Ist der nicht schon auf dev sichtbar?
