### ISSUE TITLE
alle m zu m MD

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#736]
Bei Lithologie, Chronstratigraphie, Verrohrung und Hinterfüllung bitte alle "m" Beschriftungen in "m MD" umwandeln. Dies primär bei der Visualisierung, bei der Bearbeitung sieht man das ganze technische Attribut, somit ist es dann ok

**Comment by RBordoni** [comment]
Test Version: 2.0.552:
Ohne eckige Klammer sieht die Einheit unschön aus. So umsetze wie bei Chronostratigraphie:


![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/b71dfc8c-94df-47b7-b035-a455e83721a5)

**Comment by RBordoni** [comment]
Entscheid Weekly 13.02.2024: Wo die Einheit hinter einem Wert angezeigt wird, immer ohne Eckige Klammern.

→ https://github.com/orgs/geoadmin/projects/10/views/2?pane=issue&itemId=53128405
