### ISSUE TITLE
Workgroup Dropdown bei Import nicht scrollbar

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#740]
Auf TEST sind wesentlich mehr Workgroups definiert als auf DEV. Hier wird sichtbar, dass der Dropdown nicht scrollbar ist. Die unteren Einträge kann ich nicht auswählen.

![Image](https://user-images.githubusercontent.com/31883445/240641260-481bb253-d03e-411a-a0b3-e03318ba940a.png)

**Comment by RBordoni** [comment]
Umgehungsmöglichkeit: mit der Pfeil nach unten Taste erreiche ich die unteren Einträge zumindest.

**Comment by gysimichael** [comment]
geht, danke!
