### ISSUE TITLE
Keine Angaben bei Lithologie wieder aus der Anzeige entfernen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#741]
Irgendwie werden wieder die "keine Angabe" Anzeigen bei der Lithologie angezeigt. Diese bitte wieder ausblenden:

![Image](https://user-images.githubusercontent.com/108096632/240718903-00781948-0d04-4f19-8798-e5b1714a2442.png)

**Comment by MiraGeowerkstatt** [comment]
Ich glaube wir haben explizit "keine Angaben" rausgefiltert und jetzt heisst es neu "keine Angabe"

**Comment by gysimichael** [comment]
ah, ok, dann müsste man das ändern... sorry, war mit nicht auf dem Radar

**Comment by MiraGeowerkstatt** [comment]
Ja bei mir auch nicht :D

**Comment by gysimichael** [comment]
supi, funktioniert! Danke!
