### ISSUE TITLE
Slider anbringen

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#75]
im Editor Mode fehlt sowohl bei der Verrohrung wie auch bei der Hinterfüllung der Slieder, um Parameter im Layer ein oder auszublenden, we das beispielsweise bei Stratigraphie der Fall ist. Unter Settings aber hat man die Möglichkeit, die Parameter ein oder auszublenden mit der Tickbox, hat aber ohne den Slider kein Einfluss auf Verrohrung oder Hinterfüllung

**Comment by RBordoni** [comment]
Korrektur an der Beschreibung: "Im _Viewer_ Mode fehlt sowohl bei der Verrohrung wie auch bei der Hinterfüllung der Slieder, um Parameter _bei der Filterung_ ein oder auszublenden.

**Comment by gysimichael** [comment]
ok, da habe ich was durcheinander gebracht zwischen Filter settings und Eingabesettings. Eure Erklärung ist somit korrekt und alles gut so wie es ist. Danke
