### ISSUE TITLE
Leerer Eintrag in Auswahl in Hydro wenn Verrohrung keinen Namen 

### ISSUE THREAD

**Issue by patrickackermann** [geoadmin/suite-bdms#750]
>@patrickackermann wenn man dem Stratigraphie Profil keinen Namen gibt, sieht man auch keinen Eintrag im Dropdown unter Chronostratigraphie, könnte man in diesem Fall "Keine Angabe" anziegen? So wäre ersichtlich, das man dieses Profil wählen kann und muss nicht auf einen Leereintrag klicken

Die gilt auch für Hydro Submodule, wenn man bei der Verrohrung "Keine Angabe" Einträge hat

_Originally posted by @gysimichael in https://github.com/geoadmin/suite-bdms/issues/694#issuecomment-1560971999_

**Comment by gysimichael** [comment]
Super, funktioniert einwandfrei! Danke!
