### ISSUE TITLE
Import UI optimieren

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#756]
- [ ] Drag and drop zeigt momentan auf der ganzen UI-Fläche "+Kopieren" an. Es sollte nur in den Drop-Bereichen so reagieren
- [ ] Auch beim ersten CSV-Upload für die Boreholes soll das gleiche Drop-Feld eingesetzt werden, wie bei den andern beiden
- [ ] Es können momentan max 10 Files bei den Attachments gedroppt oder via Explorer ausgewählt werden. Eigentlich darf es hier keine Limite geben. Was wenn jemand 100 oder 1000 Bohrungen mit Anhängen importieren will.
- [ ] UI Anpassungen. Mindestens gemäss folgendem Printscreen:

![Image](https://user-images.githubusercontent.com/31883445/240953991-a588f203-534b-47ed-bf73-46ac34a5745b.png)

**Comment by gysimichael** [comment]
Bei den Texten:

- Das CSV-UTF8 File sollte die folgenden Spaltenüberschriften enthalten.
- Wählen Sie eine oder mehrere Datei(en) aus:
- Das CSV-UTF8 File sollte die folgenden Spaltenüberschriften enthalten.

Sind glaube ich "." und ":" hard gecodet (siehe Abbildung unten). Könnte man das ändern? Und bei den ersten und letzten den "." weglassen?

![Image](https://github.com/geoadmin/suite-bdms/assets/108096632/ee7b0fe5-8515-4e6c-8fd0-83c6cf96ecac)

Wäre es zusätzlich möglich, nach:

- Das CSV-UTF8 File sollte die folgenden Spaltenüberschriften enthalten.
- Das CSV-UTF8 File sollte die folgenden Spaltenüberschriften enthalten.

noch ein Abstand zu dem Fenstern mit den Spaltenüberschriften einzufügen, wäre optisch ruhiger.

**Comment by gysimichael** [comment]
Danke für die Korrekturen
