### ISSUE TITLE
Anhänge bis 200Mb ermöglichen

### ISSUE THREAD

**Issue by Lehats** [geoadmin/suite-bdms#762]
Erstellt als Folgetask zu diesem Issue #687.

**Comment by gysimichael** [comment]
Wenn ich 199 MB hochladen will, mit einem File, kommt dieser Error:



![Image](https://github.com/geoadmin/suite-bdms/assets/108096632/82307dee-fa05-4690-be2e-dcbb2000ace1)

![Image](https://github.com/geoadmin/suite-bdms/assets/108096632/935baabc-e02b-4c65-b1f5-f4d6de416810)

**Comment by gysimichael** [comment]
Wenn ein File über 200 MB ist, dann kommt eine Fehler Meldung gleich im Feld, was ich gut finde

**Comment by gysimichael** [comment]
Wenn die 200 MB über alle Dokumente das Limit wären, wäre es gut, wenn man das im Feld gleich sieht. Zurzeit gibt es ja nur an, wenn ein File grösser 200 MB ist

**Comment by gysimichael** [comment]
ist jetzt in Ordnung! Danke
