### ISSUE TITLE
Lithostratigraphie aktuelle Codeliste migrieren

### ISSUE THREAD

**Issue by patrickackermann** [geoadmin/suite-bdms#765]

**Comment by gysimichael** [comment]
@patrickackermann: Haben es angeschaut. Das was nötig war zu migrieren, habe ich auf PROD schon gemacht, somit sollte das in Ordnung sein. Die 71 fehlenden Begriffe einfach ignorieren.

**Comment by gysimichael** [comment]
Ich werde im Verlauf der nächsten Woche noch zusätzliche Code liefern, die nötig wären, um die Nagra Bohrungen richtig abzubilden. Da dies nur 2 Bohrungen betrifft, die eh neu bearbeitet werden müssen, ist auch hier keine Migration nötig. Nur wäre gut, wenn die im Verlauf der nächsten Woche noch die Codeliste updaten könnten mit diesen zusätzlichen werten.

**Comment by gysimichael** [comment]
so, jetzt sollte alles zusammen sein

**Comment by gysimichael** [comment]
Vielen Dank für die Umsetzung!
