### ISSUE TITLE
Chronostratigraphie bei bestehenden Bohrungen funktioniert nicht richtig

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#768]
Wenn man bei einer Bohrung (bspw Trüllikon) bei einer bestehtenden Chronostratigraphie eine Schicht dazu fügt:

Erwartetes verhalten:
Schicht wird am Ende angehängt

Aktuelles Verhalten:
Schicht wird irgendwo im Profil eingehängt mit Intervall 0 bis 10

![Image](https://user-images.githubusercontent.com/108096632/242004940-c57a028d-f43a-471e-8c28-77e68723d464.png)

**Comment by patrickackermann** [comment]
Das Problem bei dieser Bohrung ist, dass die _toDepth_ des letzten Chronostratigraphie Layers `null` ist.

**Comment by gysimichael** [comment]
@patrickackermann ok, lohnt sich da was zu ändern (bspw Fehlermeldung, oder einfach so lassen?
