### ISSUE TITLE
Durcheinander bei Filter "Lithology top bedrock"

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#774]
Gemeldet durch Michael in #533:

> Was mir noch aufgefallen ist bezüglich Filter aber auch in Viewer und Editor:
> 
> Es gibt ein Durcheinander mit "Coarse component Lithology" und "Lithology top bedrock"
> 
> Settings Viewer Stratigraphie Filter: Lithology top bedrock
> Settings Viewer Stratigraphie fields: Lithology top bedrock
> Settings Editor Stratigraphie Filter: Lithology top bedrock
> Settings Editor Stratigraphie fields: Lithology top bedrock
> 
> Editor Stratigraphie Filter: Coarse component lithology
> Viewer Stratigraphie Filter: Coarse component lithology
> 
> Editor Lithology: Coarse component lithology -> Settings werden aber nicht berücksichtig, ist immer ausgeblendet
> Viewer Profil: Lithologie to bedrock -> Settings werden berücksichtigt
> 
> Es sollte überall "Lithology top bedrock" sein
> 
> Gut sieht man dies bei der Bohrung https://dev.boreholes.swissgeol.ch/48161 beobachten

**Comment by tschumpr** [comment]
@gysimichael So wie du in #501 beschrieben hast, haben wir das Gefühl, dass für Layer _Coarse component lithology_ für die Layer korrekt sein müsste. Stimmt das? Die Übersetzungen müssen auf jeden Fall im Settingsbereich bereinigt werden.

**Comment by gysimichael** [comment]
genau, das geht um da gleiche.

Vermutlich am besten wäre, wie bei #501, alles als "Debris lithology" und in der DB als "debris_lithology_id_cli zu benennen. bin mir aber nicht sicher ob die DB Änderung einfach durchführbar ist, da es wohl tief in den code greifft

**Comment by tschumpr** [comment]
@gysimichael 
Mit dem PR #790 wird nur das Fehlverhalten beim Filtern sowie die fehlerhafte Anzeige der Labels korrigiert. Die Übersetzungen kannst du selbst anpassen, so dass es stimmt. In der DB passen wir vorläufig auch nichts an, weil es zu viel Anpassungen im Legacy-API brauchen würde (#501).

**Comment by gysimichael** [comment]
@tschumpr : Übersetzung korrigiert und Pull Request gestartet

**Comment by gysimichael** [comment]
Danke für die Umsetzung!

**Comment by gysimichael** [comment]
bezüglich Technisches Attribut ist es im #501 erfasst und auf dem Radar
