### ISSUE TITLE
Anhang upload funktioniert nicht

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#79]
Nach erstellen einer neuen Bohrung geht der upload von Anhangen nicht. Ich kann zwar das Dokument auswählen, doch anschliessend lädt es nicht hoch

**Comment by patrickackermann** [comment]
Nach dem Auswählen des Files muss noch der _Hochladen_-Button betätigt werden.

**Comment by gysimichael** [comment]
habe ich gemacht, aber bei der Bohrung "Heute ist ein guter Tag" passiert auch nach drücken des upload Buttons nichts

**Comment by gysimichael** [comment]
seltsam, nach mehreren Anläufen geht es dann plötzlich, vorher 3 mal ohne Erfolg

**Comment by gysimichael** [comment]
Ah, es liegt am File, lade das mal auf Teams für ein Test

**Comment by gysimichael** [comment]
bewegungsempfehlungen_kraeftigung_dehnen.pdf

**Comment by patrickackermann** [comment]
Ich glaube den Fehler gefunden zu haben. Wenn ein File bereits Hochgeladen wurde, wird es ignoriert um Duplikate zu verhindern. 
Dabei wird im Moment nicht darauf geachtet bei welcher Bohrung das File bereits existiert. Das heisst im Moment kann ein File nicht bei mehreren Bohrungen angehängt werden.

**Comment by gysimichael** [comment]
ok, das ist glaube ich gut so für den Moment, müssen wir uns einfach im Hinterkopf behalten, wenn es wieder zu einem Problem wird
