### ISSUE TITLE
Editieren im Status «In Überprüfung»

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#825]
Folgender Fehler:
Im Überprüfungsstatus kann z.T. editiert werden (was nicht sein sollte). 
Zum Beispiel folgende Attribute können angepasst werden: 
-	Terrainhöhe [m ü.M.]
-	Top Fels [m TVD]
Zum Beispiel kann bei «Top Fels [m TVD]» sogar editiert werden, ohne in den Bearbeitungsmodus zu stellen.

**Comment by RBordoni** [comment]
Reproduktionsversuch: Eingaben in den genannten Feldern werden im Status "In Überprüfung" nicht gespeichert, sie können in dem Sinn nicht editiert werden. Es erscheint oben zudem eine Meldung "Bohrung mit dem Status CONTROL kann nicht editiert werden."

Hingegen bleiben Eingaben im UI sichtbar, auch wenn man vom Feld wegnavigiert. Erst beim Neuaufbau der Seite (beispielsweise durch Wechseln des Menus von Location zu Borehole und zurück) verschwinden die eingetippten Werte. 

Erwartet: Eingetippte Werte erscheinen erst gar nicht in den Feldern. Bei Auswahl-Feldern ist das Verhalten schon so.

**Comment by RBordoni** [comment]
Testresultat RB Version: 2.0.486: Das Verhalten ist viel besser so. Alles was nicht editierbar ist, bewegt sich nicht. Man fragt sich, wieso war das nicht schon immer so war. Einzig die Schatten um die Radio-Buttons sehen nicht gut aus.

@Lehats - Bitte Zu Testzwecken für die swisstopo das ganze Formular Location (Standort) mal so umbauen. Dann sehen wir auch wie es sich auf Datumsfelder und Karte auswirkt.

**Comment by RBordoni** [comment]
@gysimichael Wir haben das Formular "Location" so umgebaut, dass die Felder auf "read only" gestellt werden, wenn "in Überprüfung". Auf diese Art kann gar nicht erst etwas eingegeben werden und die Meldung "Borehole with status xy not editable" erscheint erst gar nicht.
Einzig die Schatten um die Radio-Buttons sehen leider überall nicht mehr gut aus. Was meinst du zu dieser Lösung?

**Comment by gysimichael** [comment]
Die Radio-Buttons sind wirklich unschön, gibt es da keine andere Lösung?

**Comment by gysimichael** [comment]
was ich auch noch verwirrend finde, das ich start editing drücken muss, um im Publikationsworkflow etwas zu machen. Wäre es nicht sinnvoller, diesen Button auszugrauen, wenn man im Review, In validation und Publication Modus bin, und die Buttons im Workflow gleich aktivieren, nicht erst über Start Editing?

**Comment by gysimichael** [comment]
Sonst vom Vorgehen her sicher gut so, und sinnvoll

**Comment by gysimichael** [comment]
anstelle von Radio Buttons, gibt es da eventuell etwas anderes, dass man nützen könnte, wich tickbox oder so, das weniger unschön aussieht?

**Comment by RBordoni** [comment]
Entscheid Weekly 14.01.2024, @Lehats
Verbleibendes To Do:
- Seite "Boreholes" ebenfalls umbauen analog "Location"

Alle anderen Seiten NICHT anpassen. Diese werden später bei der UI-Überarbeitung sowieso ändern.
Die obige Anmerkung (ausgegraute Workflow Buttons) nicht angehen

**Comment by gysimichael** [comment]
Sehr gut, vielen Dank!
