### ISSUE TITLE
Login-Komponente (inkl. Vorschau im Admin-Bereich) löschen

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#832]
Nach der Anbindung ans eIAM werden diese Komponenten nicht mehr benötigt.

**Comment by Philippluca** [comment]
Login-Komponente & Vorschau werden auch mit OpenID Connect noch benötigt, damit eine eine Landingpage beim Öffenen der Applikation, Rücknavigieren nach Login & Daten laden sowie für nicht autorisierte/disabled Benutzer etwas angezeigt werden kann.
