### ISSUE TITLE
Unterstützung von OAuth2 über OIDC

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#833]
Die Applikation soll über OIDC (basierend auf OAuth2) mit dem _Auth-Code-Flow und PKCE_ abgesichert werden. Somit entfällt das User- und Passwort-Handling in der DB.  
  
Ein paar Bemerkungen dazu:

- [x] Die Anbindung soll vorläufig mit [Amazon Cognito](https://aws.amazon.com/de/cognito/) getestet werden.
- [x] #872
- [x] #888
- [x] #904
- [x] Die Rollenverwaltung bleibt vorläufig in der DB, bis wir entschieden haben, wie damit weitergefahren wird.
- [x] #911
- [x] #912
- [x] #938
- [x] Funktion _neue Benutzer erstellen_ aus Client entfernen (mit https://github.com/geoadmin/suite-bdms/pull/947 behoben)
- [x] middle_name aus DB entfernen  (mit https://github.com/geoadmin/suite-bdms/pull/947 behoben)
- [x] #955 (Issue erstellt)
- [x] Abklärungen, ob clientseitig (BDMS) nach dem Login überprüft werden muss, ob der entsprechende Benutzer für BDMS berechtigt ist (via API beim Abfragen der Userinformation)
- [x] Erstbenutzer werden ohne Workgroup/Rolle erstellt.
- [x] Handling neuer User ohne Workgroups/Berechtigungen
- [x] Handling disabled User mit erfolgreichem login
- [x] Disable(d) Funktionalität aus Client entfernen (wird neu via IAM geregelt)(Disable bleibt vorerst bestehen. User wird über fehlende Berechtigung informiert.)
- [x] Invalidieren/Löschen von abgelaufenen Tokens im Browser (Gelöst durch Verwendung eines Frameworks mit Login, Refresh, Logout support)
- [x] (username zu Shortname umbenennen)?

**Comment by Philippluca** [comment]
Alle Tasks sind abgeschlossen oder als einzelnes Issue im Milestone [Integration eIAM](https://github.com/geoadmin/suite-bdms/milestone/10) erfasst.
