### ISSUE TITLE
Container Image als non-root User `app` laufen lassen

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#858]
Seit .NET 8 haben alle .NET Docker Images einen non-root User mit dem Namen `app` konfiguriert, mit dem man das Image laufen lassen sollte - standardmässig wird das Image immer noch mit dem `root`-User ausgeführt.  
Siehe auch: https://andrewlock.net/exploring-the-dotnet-8-preview-updates-to-docker-images-in-dotnet-8/

**Comment by flenny** [comment]
@danjov Möchte man den [Client Node Container](https://github.com/geoadmin/suite-bdms/blob/main/src/client/Dockerfile) diesbezüglich auch gleich anpassen? Neues separates Issue?

**Comment by danjov** [comment]
> @danjov Möchte man den [Client Node Container](https://github.com/geoadmin/suite-bdms/blob/main/src/client/Dockerfile) diesbezüglich auch gleich anpassen? Neues separates Issue?

@flenny Gerne, ja - und in einem separaten Issue.
