### ISSUE TITLE
Umbau des Bereichs „Instrumentation“

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#869]
Der Bereich „Instrumentation“ soll, vor allem im Backend, umgebaut werden. Davon betroffen sind das Datenbankschema, das API und das Frontend. Durch den Umbau soll das Datenbank-Schema vereinfacht und verständlicher werden. Durch den Umbau im DB-Schema soll auch gleich das API auf .NET migriert und das Frontend umgebaut werden, das löst vermutlich einige offene Bugs (z.B. #251 und #426).

Die Anpassungen am DB-Schema sind ebenfalls beschrieben in #253.

Testing:
das UI ist unter der URL /editor/{_boreholeId_}/completion/v2
erreichbar.

**Comment by Lehats** [comment]
@gysimichael Wir sind gerade daran die Instrumentations anzupassen. Nun stellen wir uns die Frage ob das Attribut _Instrument ID_ noch notwendig ist?

Falls ja, haben wir etwas Bedenken zur Aussagekraft des Attributnamens _Instrument ID_. Wir denken, dass es sch dabei nicht wirklich um eine Id handelt. Wenn es aber aus dem Jargon des Bohrens kommt, ist es natürlich legitim.

Die selbe Frage stellen wir uns auch für das Attribut _Casing ID_. Auch da sollten wir, sofern es sich mit den Fachbegriffen der Bohrerei vereinbaren lässt, ein treffender Begriff finden.

**Comment by gysimichael** [comment]
Casing Name
Instrument Name 
etc.

ist glaube ich sinnvoller, oder was meint ihr?
Ich würde dieses Feld aber schon lassen, kann ja sein, das man bspw 3 gleiche Intrumente im Loch hat, und diese Unterscheiden will, und nicht nur über die Teufe

**Comment by Lehats** [comment]
@gysimichael Wir denken auch, dass _Name_ klarer ist. Und das es eine Berechtigung hat sehen wir auch. Danke für die schnelle Antwort!

**Comment by RBordoni** [comment]
Die obige Namensdiskussion soll auch in die Labels im UI einfliessen. "Casing ID" ist jeweils zu ersetzen durch:
E: "Casing Name"
D: "Name Verrohrung"
F: "Nom tubage"
IT: "Nome tubazione"


![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/318e3f76-2b37-443e-9334-fe3103fd3aa7)

**Comment by RBordoni** [comment]
Die im Kommentar genannten offenen Punkte wurden in #1047 und #1045 übertragen. Dieses Issue wird geschlossen.
