### ISSUE TITLE
Umbau des Bereichs „Backfill“

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#870]
Der Bereich „Backfill“ soll, vor allem im Backend, umgebaut werden. Davon betroffen sind das Datenbankschema, das API und das Frontend. Durch den Umbau soll das Datenbank-Schema vereinfacht und verständlicher werden. Durch den Umbau im DB-Schema soll auch gleich das API auf .NET migriert und das Frontend umgebaut werden, das löst vermutlich einige offene Bugs (z.B. #251).

Die Anpassungen am DB-Schema sind ebenfalls beschrieben in #253.

**Comment by gysimichael** [comment]
Es fehlt das Feld Casing Name, das hier auch wichtig wäre, um einen Bezug zu dem Casing, das verfüllt oder hinterfüllt wird, zu machen.
Hier wäre es wichtig, dass im Dropdown nicht alle Casing Elemente aufgeführt werden, sondern die mit dem gleichen Namen zusammengefasst werden. Auch bräuchte es eine Option (wie beim legacy API), ein offenes Bohrloch zu dekalrieren (offenes Bohrloch, open hole, forrage ouvert, perforazione aperto).
Desweitern werden die Einträge aktuell nach dem Zeitstempfel der Erfassung sotiert. Diese sollten nach Casing Name, und anschliessend nach Teufe sortiert werden, damit man die Einträge sinvoll lesen kann
