### ISSUE TITLE
"Completion" Table erstellen

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#877]
Die Einträge aus dem Completion-Bereich sollen aus der Stratigraphy-Table entfernt und in eine separate Tabelle ausgelagert werden. Mit diesem Task wird dazu die entsprechende Tabelle erstellt. Die effektiven Migrationen werden mit den Folgeissues gemacht.

**Comment by danjov** [comment]
Duplikat von https://github.com/geoadmin/suite-bdms/issues/876.
