### ISSUE TITLE
Verwaltung von Stratigraphien auf neue API Version umstellen

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#891]
Die Verwaltung der Eigenschaften einer Stratigraphie soll über das neue .NET API erfolgen.

- [x] #892
- [x] #893
- [x] #894
- [x] #895
- [x] #896
- [x] #926

**Comment by danjov** [comment]
@RBordoni Was zu testen ist: Das Erstellen, Editieren, Duplizieren und Löschen von Strategraphien im Stratigraphie-Header.

**Comment by RBordoni** [comment]
Test Version: 2.0.512
Duplizieren und Löschen geht. Hingegen erhalte ich beim Versuch eine neue Stratigrafie zu erstellen (+ Stratigraphy) und beim Editieren folgenden Meldungen, die ich vorher noch nie hatte:



![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/d3774cda-faa3-4ec0-a9b9-fc10aa4ac739)


![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/3b842f50-17f7-454a-a97c-1ee6c43fb822)

**Comment by danjov** [comment]
@RBordoni Mit welchem Benutzer hast du getestet? Die Meldung erscheint, wenn man versucht eine Bohrung zu editieren, die von einem anderen Benutzer _gelocked_ wurde.

**Comment by RBordoni** [comment]
Immer mit "Admin"

**Comment by RBordoni** [comment]
Entscheid Weekly 14.01.2024:
- Admin User soll alles dürfen, aus den Checks nehmen
- Timer für Editierung von 10 Min auf 60 Min erhöhen (oder mindestens 30 Min)

**Comment by RBordoni** [comment]
Test Version: 2.0.524:
Timer ist zwar erhöht. Die Restzeitanzeige startet aber immer noch bei zehn Minuten und fällt nach 10 Min in eine Minuszahl.


![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/ad9b1f4b-36b9-4af8-9c3c-393428c0e364)
