### ISSUE TITLE
Completion: Header umbauen

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#905]
Gemäss Entscheid aus https://miro.com/app/board/uXjVNDScao4=/

**Comment by gysimichael** [comment]
@tschumpr Sieht seht gut aus, gefällt mir!
Wie aufwändig wäre es, dass man die Reiter per Drag and Drop noch vor und zurück schieben könnte, um seine eigene Reihenfolge zu erstellen? Wäre ein nice to have, aber noch cool

**Comment by RBordoni** [comment]
> Wie aufwändig wäre es, dass man die Reiter per Drag and Drop noch vor und zurück schieben könnte, um seine eigene Reihenfolge zu erstellen? Wäre ein nice to have, aber noch cool

Für dieses Anliegen wurde ein neues Issue eröffnet #1058
