### ISSUE TITLE
Completion: Navigation umbauen

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#906]
Gemäss Entscheid aus https://miro.com/app/board/uXjVNDScao4=/

Wenn mit sinnvollem Aufwand möglich URL-Verlinkung der einzelnen Completion-Tabs: zB _completion/{completionId}#{tab}_ oder ähnlich

inkl.
- Bereinigung Client
- Datenmigration
- Bereinigung V1 & V2 API
- Bereinigung DB-Tabellen

**Comment by gysimichael** [comment]
top, danke!

**Comment by gysimichael** [comment]
gerade festgestellt, dass sowohl Hydrogeology abera uch Completion nicht kopiert werden wenn man eine Bohrung kopiert, macht aber absolut Sinn so und ist in Ordnung, denn diese Einträge können verschieden sein, die Geologie aber wohl sehr ähnlich. Somit alles gut diesbezüglich
