### ISSUE TITLE
Keine Angabe bei Stiration und Bohrlochende falsch übersetzt

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#919]
![Image](https://github.com/geoadmin/suite-bdms/assets/108096632/503c5e3f-25b3-4919-b359-588a1fbbbf99)

Bei Striation und Bohrlochende ist man nicht konsistent mit der Übersetzung.

Für Keine Angabe haben wir normalerweise:

IT: senza indicazioni
FR: sans indication
EN: not specified

weiss aber nicht wo das hinterlegt ist, bitte Übersetzung anpassen

**Comment by gysimichael** [comment]
Ich glaube ich habe es in den Übersetzungsfiles gefunden auf Position 279 "np" und auch gleich korrigiert. Müsste man kurz prüfen, ob das passt, wenn ja, hat sich das erledigt.

**Comment by gysimichael** [comment]
@danjov ich glaube patch-2 (FR) ist noch nicht durch - ging da was schief und braucht das einfach noch ein bisschen Geduld?

**Comment by danjov** [comment]
@gysimichael Alle Patches sollten auf der DEV-Umgebung verfügbar sein, da die aktuellste Version bereits deployed ist.

**Comment by gysimichael** [comment]
DE IT und EN sind umgesetzt, FR nicht...

**Comment by danjov** [comment]
@gysimichael Ich sehe gerade, dass der Branch [gysimichael-patch-2](https://github.com/geoadmin/suite-bdms/tree/gysimichael-patch-2) noch offen ist und noch kein PR dafür existiert. Aus diesem Grund ist der Change noch nicht auf DEV. Kannst du den entsprechenden PR erstellen? Danke :)

**Comment by gysimichael** [comment]
und wie mache ich das? Normalerweise werde ich zu dieser Option durchgeschleust, hier war das wohl nicht der fall...

**Comment by gysimichael** [comment]
jetzt hat alles geklappt. Danke!
