### ISSUE TITLE
Whiteout bei Filtern auf Prod

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#920]
Wenn man den Filter auf Prod im Editor Modus benutz, bswp. unter Lokalität bei Originalname die Bohrung Bülach suchen will, gibt es einen Whiteout.

**Comment by RBordoni** [comment]
@gysimichael Wir können es nicht reproduzieren. Auf zwei Maschinen getestet auf Prod und DEV.

**Comment by gysimichael** [comment]
Nach nochmaligem Testen und kurzer Demo an Renato könnt es sein, dass es mit der Ladegeschwindigkeit der Cluster auf der Karte zu tun hat. Wenn die Cluster da sind, geht alles, wenn die Bohrungen aufgelistet werden, aber die Cluster nicht sichtbar sind, gibt es im Editor Modus ein Whiteout

**Comment by RBordoni** [comment]
Ist auf DEV auch aufgetreten. Kann auf Prod erst beim nächsten dortigen Release getestet werden.

**Comment by gysimichael** [comment]
das funktioniert nun auf DEV! Vielen Dank!
