### ISSUE TITLE
IsBoreholeLockedAsync überprüfen und flächendeckend einsetzen

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#939]
Im .NET API muss für alle Borehole-related _create_, _update_, _copy_ und _delete_ Operations überprüft werden, ob das Borehole gerade gelocked ist und ob der User zur Bearbeitung berechtigt ist. In einzelnen Controllern wie StratigraphyController und CompletionController ist dies bereits drin, der Check soll aber ausgelagert und in allen anderen Controller mit Borehole-Bezug eingebaut werden (z.B. Instrumentation, Hydrogeologie, ...)

Betrifft den folgenden Code:
```
        try
        {
            // Check if associated borehole is locked
            var userName = HttpContext.GetUserName();
            if (await boreholeLockService.IsBoreholeLockedAsync(completion.BoreholeId, userName).ConfigureAwait(false))
            {
                return Problem("The borehole is locked by another user.");
            }
        }
        catch (UnauthorizedAccessException)
        {
            return Unauthorized("You are not authorized to copy this completion.");
        }
```

Dieses Refactoring soll erst gemacht werden wenn #913 abgeschlossen ist.

**Comment by danjov** [comment]
Im Legacy-API gibt es zwei Check-Funktionen: [`check_edit`](https://github.com/geoadmin/suite-bdms/blob/b86734a52b133360393cd4e1e426edf29dcb17c5/src/api-legacy/v1/handlers/producer.py#L35-L55) und [`check_lock`](https://github.com/geoadmin/suite-bdms/blob/b86734a52b133360393cd4e1e426edf29dcb17c5/src/api-legacy/v1/handlers/producer.py#L57-L161). Aktuell wurde nur die [`check_lock`](https://github.com/geoadmin/suite-bdms/blob/b86734a52b133360393cd4e1e426edf29dcb17c5/src/api-legacy/v1/handlers/producer.py#L57-L161)-Funktion ins neue API portiert, d.h. die [`check_edit`](https://github.com/geoadmin/suite-bdms/blob/b86734a52b133360393cd4e1e426edf29dcb17c5/src/api-legacy/v1/handlers/producer.py#L35-L55)-Funktion muss noch portiert und an den korrekten Stellen aufgerufen werden.
