### ISSUE TITLE
Login fails if route is present

### ISSUE THREAD

**Issue by Philippluca** [geoadmin/suite-bdms#956]
**Steps to reproduce**
1. Go to 'https://[appurl]/editor/'
2. Click on 'Login'

**Expected behavior**
The login form of the OIDC provider is shown.

**Current behavior**
OIDC provider shows request error "An error was encountered with the requested page."

**Fix**
Omit path in redirect url.
Use OIDC State

**Comment by RBordoni** [comment]
Bei mir scheint der Fix das Gegenteil zu bewirken. JETZT habe ich den Fehler und kann mich nicht mehr einloggen.

**Comment by Philippluca** [comment]
@RBordoni Ich habe die Einstellungen bei unserem Auth provider korrigiert. Es sollte jetzt funktionieren.
