### ISSUE TITLE
Sortieren funktioniert nicht

### ISSUE THREAD

**Issue by gysimichael** [geoadmin/suite-bdms#96]
sowohl im Editor Mode wie auch im Viewer  Mode geht bei Creator date die Sortierfunktion nicht richtig. Andere Spalten scheinen zu funktionieren

**Comment by RBordoni** [comment]
Sortierung der Spalte "Total depth MD [m]" geht auch nicht richtig.

**Comment by gysimichael** [comment]
scheint generell mit Zahlen und Daten ein Wurm drin zu sein, mit Text scheint es zu funktionieren

**Comment by gysimichael** [comment]
sieht gut aus, danke für die Umsetzung
