### ISSUE TITLE
Completion content cards not scrollable

### ISSUE THREAD

**Issue by Lehats** [geoadmin/suite-bdms#960]
Beim UI von Completions V2:
Wenn man mehrere Instrumentations hinzufügt, kann man die Cards nicht mehr scrollen. Die unterste Card ist dann nicht mehr komplett sichtbar/editierbar.

Gilt für Instrumentations, Backfills. Evt. auch Casing

![Image](https://github.com/geoadmin/suite-bdms/assets/37898460/d9c41bb2-5241-46b1-b5cc-bbfaba2c4b37)

**Comment by RBordoni** [comment]
Test Version: 2.0.539: 
Scrollmöglichkeit ist vorhanden.
Noch unschön ist das Fensterverhalten. Dies sowohl bei _Completion_, als auch bei _Hydrogeologie_. Separates Issue → #980
