### ISSUE TITLE
Fehler bei Seitenneuaufbau mit F5 bei Hydrogeology

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#967]
Version: 2.0.531

**Repro Steps:**

1. User = Admin, Editor Modus
2. Wähle eine beliebige Bohrung mit oder ohne Hydrogeologie-Einträgen
3. Wähle einen Menupunkt bei Hydrogeology, beispielsweise _Water ingress_
4. F5

**Erwartet:**
Die Seite wird neu aufgebaut

**Beobachtet:**
Die Seite wird neu aufgebaut und es erscheint eine Fehlermeldung.
Erfolgt nur bei Hydrogeolgy.
Bei der neuen Completion nicht.

![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/b1c61b90-66e2-4828-9ecd-273349ce63e1)

**Comment by RBordoni** [comment]
Test Version: 2.0.537: Fehler erscheint immer noch

**Comment by Lehats** [comment]
> Test Version: 2.0.537: Fehler erscheint immer noch. Oder lief der Release nicht durch bis DEV?

@RBordoni Kannst du vielleicht nochmals testen? Ich kann es nicht mehr reproduzieren. Ansonsten kannst du mir die Borehole Id mitteilen wenn es failt?

**Comment by RBordoni** [comment]
@Lehats  Ich kann es auch nicht mehr reproduzieren. Hat sich erledigt, ich schliesse das Isse.

**Comment by gysimichael** [comment]
Sieht gut aus, danke!
