### ISSUE TITLE
Allgemeine Components vereinheitlichen

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#972]
Momentan gibt es sehr viel doppelten Code oder unterschiedliche Stylings, zB für Formularfelder, Alerts, etc. Damit das Applikations-UI einheitlich daher kommt, sollen wiederverwendbare Komponenten, inkl. Cypress-Funktion (analog _setTextfield()_ im _testHelpers.js_ erstellt werden. Evt. muss die Ordnerstruktur im _client/src_ etwas angepasst werden, damit die Komponenten einfacher zu finden sind.

- [x] Form-Components (Input, Select und Checkbox) für Completion erstellen, inkl. Tests
- [x] Form-Components in der Hydrogeologie einbauen, allenfalls weitere Form-Components erstellen, inkl. Tests
- [x] Felder aus Completion-Display-Files in Components auslagern, inkl. data-cy und Tests anpassen
- [x] Prompt & Alert in Components-Ordner verschieben, inkl. Prompt-Funktionen aus Completion-Tests in separates Helper-File auslagern
- [x] Cards inkl. Buttons in Completion und Hydrogeologie vereinheitlichen

**Comment by RBordoni** [comment]
Priorität hat folgender Bug, der mit wiederverwendbaren Komponenten zu lösen ist:

**Repro Steps:**
1. Irgendeine Kachel in einer der neuen Completion-Tabs hinzufügen
2. "Von Tiefe ..." ausfüllen 
3. In ein anderes Feld klicken, beispielsweise "Bis Tiefe ..."
4. Daten eingeben
**Erwartet:**
Daten können eingegeben werden
**Beobachtet:**
Man muss ein zweites mal in das Feld klicken, um Daten eingeben zu können (Nach der Eingabe des ersten Characters teilweise sogar ein drittes mal)

**Comment by RBordoni** [comment]
Test Version: 2.0.539:
Werte können jetzt flüssig eingegeben werden. 
Hingegen bleiben gewisse Pflichtfelder rot, auch wenn ausgefüllt (namentlich Codelisten und Textfelder. Beim Fokuswechsel des Windowsfensters verschwinden zudem die Eingaben.


![Image](https://github.com/geoadmin/suite-bdms/assets/31883445/d4d10b47-707c-4c3e-bac9-4eec8106e380)

**Comment by gysimichael** [comment]
sieht gut aus, danke!
