### ISSUE TITLE
Beschreibung und Verbesserung der lokalen Entwicklungsumgebung

### ISSUE THREAD

**Issue by danjov** [geoadmin/suite-bdms#975]
Die lokale Entwicklungsumgebung soll dokumentiert und verbessert werden:
* Das .NET API und das Frontend sollen direkt aus VS2022 gestartet werden können (zB `*.esproj`-File für Frontend)
* Dev-Container braucht es nicht mehr
* Anpassung des entsprechenden Absatzes im [README](https://github.com/geoadmin/suite-bdms?tab=readme-ov-file#einrichten-der-entwicklungsumgebung)

**Comment by Philippluca** [comment]
@danjov @tschumpr Hatten wir entschieden mit diesem Issue die Migration auf Vite bereits anzugehen oder warten wir hier noch zu bzw. lösen machen dies mit einem separaten issue?

**Comment by danjov** [comment]
> @danjov @tschumpr Hatten wir entschieden mit diesem Issue die Migration auf Vite bereits anzugehen oder warten wir hier noch zu bzw. lösen machen dies mit einem separaten issue?

@Philippluca Dazu gibt's bereits ein separates Issue und kann mit diesem erledigt werden, siehe #866.
