### ISSUE TITLE
Casing in Hydrogeologie einbinden

### ISSUE THREAD

**Issue by tschumpr** [geoadmin/suite-bdms#977]
In den Hydrogeologie-Bereichen wird das Casing noch nicht korrekt verlinkt.

**Comment by gysimichael** [comment]
Ich kann nicht nachvollziehen, woher hier die Info für den Vorrohung gezogen wird.

In falle der Bohrung https://dev-boreholes.swissgeol.ch/editor/30840/hydrogeology/wateringress

gibt es 3 aaa, 2 bbb und ein bb

Bei der Verrohung habe ich aber nur 2 aa, 1 bbb und 1 bb

Kann mir vorstellen, das hier ein Durcheinander entsteht, wenn man zusätzlich noch Instrumente erfasst

**Comment by gysimichael** [comment]
@tschumpr Hier liegt glaube ein Verständnisproblem vor;

Ein Casing kann (muss aber nicht) aus verschiedenen Casing Elementen bestehen. Beispielsweise zuerst ein Vollrohr von 0-10m dann ein Siebrohr von 10-15m und am schluss nochmals ein Vollrohr von 15-25m

Das Casing hat einen Namen, sagen wir AAA, gemäss Einträge besteht es aber aus 3 Karten, den 3 Casing Elementen, die aber eine Einheit Bilden und so auch bei allen anderen Tabs dargestellt werden müssten.

**Comment by RBordoni** [comment]
Die im Kommentar genannten offenen Punkte wurden in https://github.com/geoadmin/suite-bdms/issues/1048  übertragen. Dieses Issue wird geschlossen.
