### ISSUE TITLE
Add Completion übernimmt Formularinhalt

### ISSUE THREAD

**Issue by RBordoni** [geoadmin/suite-bdms#997]
**Repro Steps:**

1. Bohrung mit einer Completion
2. Completion > Start editing 
3. Bestehende Completion editieren durch Klick auf Stift
4. Änderung vornehmen
5. "Add completion" klicken ohne Bearbeitung der bestehenden Completion zu beenden

**Erwartet:**
Meldung "Unsaved changes ..."

**Beobachtet:**
Neue Completion wird eröffnet und Formularinhalt von anderer Completion übernommen

**Comment by RBordoni** [comment]
Test Version: 2.0.555:
Beim "Save" (nach "You have unsaved changes. Do you want to save them?) funktioniert noch nicht alles richtig. 
Zwei Use Cases, die fehlerhaft sind:

a) Klicke ich während des Bearbeitens einer completion "+ Add Completion" und dann "Save" → erfolgt ein whiteout (leerer Browserinhalt)
b) zuerst "+ Add Completion", diese ausfüllen, nicht saven, Tab wechseln und dann "Save" → es saved nicht und nix passiert

@tschumpr zeige es bei Bedarf gerne live

**Comment by RBordoni** [comment]
Test Version: 2.0.559:
Obiges ist behoben. Was noch bleibt, Repro Steps:

1. Bohrung mit einer Completion
2. Neue Completion mit Add Completion"
3. , Name ausfüllen und Completoion Type nicht ausfüllen
4. nicht saven
5. Tab wechseln und dann "Save"

Beobachtet
es saved nicht (was richtig ist) danach kann aber nicht nochmals auf die anderen Tabs geklickt werden

**Comment by gysimichael** [comment]
Auf der Ebene Completion geht es, aber auf der Ebene von Casing, Instrument und Backfill ist es noch nicht umgesetzt

**Comment by RBordoni** [comment]
Verbleibendes ist in #1040 erfasst. Diese Task wird geschlossen.
